@DOC_TITLE@
SmartBattery Device Application Note
authentication.h File Reference
Detailed Description
Headerfile for authentication.c.
Contains defines, typedefinitions and functions prototypes for authentication.c.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file authentication.h.
#include "common.h"
#include "sbs_commands.h"
#include "battery_pack_parameters.h"
Enumerations
enum AUTH_Status { AUTH_Status_Start = 0x01, AUTH_Status_Executing = 0x02, AUTH_Status_Finished = 0x04, AUTH_Status_Error = 0x08 }
Functions
void AUTH_Execute (SBS_command_t *sbsCmd)
Run the chosen authentication algorithm.
SBS_command_t * AUTH_GetResponse (void)
Copy key from eeprom to sram.
Enumeration Type Documentation
enum AUTH_Status
Enumerator:
AUTH_Status_Start Should be the value of the status flag when sent from host, and is returned if the battery hasn't started the authentication algorithm yet.
AUTH_Status_Executing Status during execution
AUTH_Status_Finished The authentication algorithm is finished and the data ready to send to host
AUTH_Status_Error Status if any error occurs (depends on crypto used)
Definition at line 60 of file authentication.h.
                 {
    AUTH_Status_Start = 0x01,
    AUTH_Status_Executing = 0x02,
    AUTH_Status_Finished = 0x04,
    AUTH_Status_Error = 0x08
};
Function Documentation
void AUTH_Execute (SBS_command_t * sbsCmd)
Run the chosen authentication algorithm.
Runs the authentication algorithm on the data in sbsCmd and stores the result in authenticationResponse to be retrieved by AUTH_GetResponse().
The data in sbsCmd will be destroyed
Only runs the algorithm if the status byte is AUTH_Status_Start.
Parameters:
sbsCmd Pointer to SBS command parameters
Definition at line 158 of file authentication.c.
References AES_BLOCK_SIZE, AES_Encrypt(), AES_KEY_SIZE, AES_PrepareEncrypt(), AUTH_Status_Error, AUTH_Status_Finished, AUTH_Status_Start, HMAC_SHA2(), SBS_command_union::payload, SBSDATA_BLOCK_LENGTH, SHA_INPUT_BLOCK_SIZE, and SHA_INPUT_BLOCK_WORDS.
Referenced by main().
{
    uint8_t i;
    // Only run if status byte (the first byte) says so
    if(AUTH_Status_Start == sbsCmd->payload[0]) {
//******************************************************************************
// AES Encryption Start
//******************************************************************************
#       if defined(AUTH_USE_AES)
        // Copy the key  to the key buffer
        for(i = 0; i < AES_KEY_SIZE; ++i) {
            key_buffer[i] = key[i];
        }
        // Do the encryption
        AES_PrepareEncrypt( key_buffer ); // Does nothing, but should be called anyway if that changes in the future
        AES_Encrypt( &sbsCmd->payload[1], key_buffer );
        sbsCmd->payload[0] = AUTH_Status_Finished;
        // Store the encrypted message internally for later use
        // The variable "i" is used later to fill the rest of the payload with zeros
        for( i = 0; i <= AES_BLOCK_SIZE; i++)
        {
            authenticationResponse.payload[i] = sbsCmd->payload[i];
        }
        for( ; i < SBSDATA_BLOCK_LENGTH; ++i)
        {
            authenticationResponse.payload[i] = 0x00;
        }
//******************************************************************************
// AES Encryption End
//******************************************************************************
//******************************************************************************
// HMAC-SHA2 Encryption Start
//******************************************************************************
#       elif defined(AUTH_USE_HMAC_SHA2)
        // Copy the input data to the message buffer
        // If SHA_INPUT_BLOCK_SIZE is SBSDATA_BLOCK_LENGTH include
        // the status byte, otherwise skip it
        for( i = 0; i < SHA_INPUT_BLOCK_SIZE; ++i) {
#           if SHA_INPUT_BLOCK_SIZE == SBSDATA_BLOCK_LENGTH
                u_message.uc_message[i] = sbsCmd->payload[i];
#           else
                u_message.uc_message[i] = sbsCmd->payload[i+1];
#           endif
        }
        // Swap endianess of the message to comply with the standard
        HMAC_SHA2_swapEndianess(u_message.ul_message, SHA_INPUT_BLOCK_WORDS);
        // Run the algorithm
        HMAC_SHA2( u_message.ul_message, (uint32_t*)sbsCmd->payload );
        // Swap endianess of the result to comply with the standard
        // 32-bytes (256-bits, 8 32-bit words) is always the result from the HMAC-SHA2 algorithm
        HMAC_SHA2_swapEndianess((uint32_t*)sbsCmd->payload, 8);
        // Store the response internally for later use
        // Only store the 31 last bytes, as the first byte is a status byte.
        for( i = 1; i < 32; i++)
        {
            authenticationResponse.payload[i] = sbsCmd->payload[i-1];
        }
        // Mark it as finished
        authenticationResponse.payload[0] = AUTH_Status_Finished;
#       endif // If AUTH_USE_AES/AUTH_USE_HMAC_SHA2
//******************************************************************************
// HMAC-SHA2 Encryption End
//******************************************************************************
    } else {
        // Set payload to only return the status, which is "error"
        authenticationResponse.payload[0] = AUTH_Status_Error;
        for(i = 1 ; i < SBSDATA_BLOCK_LENGTH; ++i)
        {
            authenticationResponse.payload[i] = 0x00;
        }
    }
}
SBS_command_t* AUTH_GetResponse (void)
Copy key from eeprom to sram.
Return pointer to authentication response
Returns:
Pinter to response
Definition at line 117 of file authentication.c.
Referenced by handleSBSCommand().
{
    return &authenticationResponse;
}