@DOC_TITLE@
SmartBattery Device Application Note
battery_voltage_monitoring.c File Reference
Detailed Description
Battery cell voltage monitoring firmware module.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
6090
Date
2009-10-05 21:40:12 +0800 (Mon, 05 Oct 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file battery_voltage_monitoring.c.
#include "common.h"
#include "battery_voltage_monitoring.h"
#include "vadc.h"
#include "battery_pack_parameters.h"
Functions
bool BATTVMON_IsCellVoltageTooHigh (vadcIndex_t cell)
Investigate if any of the battery cells are too high.
bool BATTVMON_IsCellVoltageTooLow (vadcIndex_t cell)
Investigate if the battery cells are too low.
Function Documentation
bool BATTVMON_IsCellVoltageTooHigh (vadcIndex_t cell)
Investigate if any of the battery cells are too high.
Requires that a V-ADC scan has been run.
Parameters:
cell Which cell to check. Is not checked by this function, but readCellVoltage will return 0 if the cell is invalid (and thus this function will always return false in that case)
Returns:
True is returned if any of the cells have too high voltage, otherwise false.
Definition at line 92 of file battery_voltage_monitoring.c.
References VADC_readCellVoltage().
Referenced by handleNewCellVoltage().
{
    bool status = false;
    if( battParams.cellMaxVoltage < VADC_readCellVoltage( cell ) ){
        status = true; // Voltage of cell is too high!
    }
    return status;
}
bool BATTVMON_IsCellVoltageTooLow (vadcIndex_t cell)
Investigate if the battery cells are too low.
Requires that a V-ADC scan has been run.
Parameters:
cell Which cell to check. Is not checked by this function, but readCellVoltage will return 0 if the cell is invalid (and thus this function will always return true in that case)
Returns:
True is returned if any of the cells have too low voltage, otherwise false.
Definition at line 70 of file battery_voltage_monitoring.c.
References VADC_readCellVoltage().
Referenced by handleNewCellVoltage().
{
    bool status = false;
    if( battParams.cellMinVoltage > VADC_readCellVoltage( cell ) ){
        status = true; // Voltage of cell is too low!
    }
    return status;
}