@DOC_TITLE@
SmartBattery Device Application Note
battery_protection.h File Reference
Detailed Description
Header file for Battery Protection peripheral module driver.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file battery_protection.h.
#include "common.h"
Defines
#define BATTPROT_DisableAllInterrupts() (BPIMSK = 0x00)
Disable all Battery Protection interrupts.
#define BATTPROT_DisableChargeHighCurrentInterrupt() (BPIMSK &= ~(1<<CHCIE))
Disable charging high-current interrupt (Battery Protection Interrupt).
#define BATTPROT_DisableChargeHighCurrentProtection() (BPCR |= (1<<CHCD))
Disable the charging high-current.
#define BATTPROT_DisableChargeOverCurrentInterrupt() (BPIMSK &= ~(1<<COCIE))
Disable charging over-current interrupt (Battery Protection Interrupt).
#define BATTPROT_DisableChargeOverCurrentProtection() (BPCR |= (1<<COCD))
Disable the charging over-current.
#define BATTPROT_DisableDiscargeOverCurrentInterrupt() (BPIMSK &= ~(1<<DOCIE))
Disable discharging over-current interrupt (Battery Protection Interrupt).
#define BATTPROT_DisableDischargeHighCurrentInterrupt() (BPIMSK &= ~(1<<DHCIE))
Disable discharging high-current interrupt (Battery Protection Interrupt).
#define BATTPROT_DisableDischargeHighCurrentProtection() (BPCR |= (1<<DHCD))
Disable the discharging high-current.
#define BATTPROT_DisableDischargeOverCurrentProtection() (BPCR |= (1<<DOCD))
Disable the discharging over-current.
#define BATTPROT_DisableExternalInputProtection() (BPCR |= (1<<EPID))
Disable the external protection input.
#define BATTPROT_DisableShortCircuitInterrupt() (BPIMSK &= ~(1<<SCIE))
Disable short-circuit (Battery Protection Interrupt).
#define BATTPROT_DisableShortCircuitProtection() (BPCR |= (1<<SCD))
Disable the short-circuit protection.
#define BATTPROT_EnableAllInterrupts() (BPIMSK = (1<<SCIE)|(1<<COCIE)|(1<<CHCIE)|(1<<DOCIE)|(1<<DHCIE))
Enable all Battery Protection interrupts.
#define BATTPROT_EnableChargeHighCurrentInterrupt() (BPIMSK |= (1<<CHCIE))
Enable charging high-current interrupt (Battery Protection Interrupt).
#define BATTPROT_EnableChargeHighCurrentProtection() (BPCR &= ~(1<<CHCD))
Enable the charging high-current protection (default enabled).
#define BATTPROT_EnableChargeOverCurrentInterrupt() (BPIMSK |= (1<<COCIE))
Enable charging over-current interrupt (Battery Protection Interrupt).
#define BATTPROT_EnableChargeOverCurrentProtection() (BPCR &= ~(1<<COCD))
Enable the charging over-current protection (default enabled).
#define BATTPROT_EnableDiscargeOverCurrentInterrupt() (BPIMSK |= (1<<DOCIE))
Enable discharging over-current interrupt (Battery Protection Interrupt).
#define BATTPROT_EnableDischargeHighCurrentInterrupt() (BPIMSK |= (1<<DHCIE))
Enable discharging high-current interrupt (Battery Protection Interrupt).
#define BATTPROT_EnableDischargeHighCurrentProtection() (BPCR &= ~(1<<DHCD))
Enable the discharging high-current protection (default enabled).
#define BATTPROT_EnableDischargeOverCurrentProtection() (BPCR &= ~(1<<DOCD))
Enable the discharging over-current protection (default enabled).
#define BATTPROT_EnableExternalInputProtection() (BPCR &= ~(1<<EPID))
Enable the external protection input (default enabled).
#define BATTPROT_EnableShortCircuitInterrupt() (BPIMSK |= (1<<SCIE))
Enable short-circuit interrupt (Battery Protection Interrupt).
#define BATTPROT_EnableShortCircuitProtection() (BPCR &= ~(1<<SCD))
Enable the short-circuit protection (default enabled).
#define BATTPROT_HcrtMsecToHex(milliSeconds) ((uint8_t)(milliSeconds/2.0))
Conversion from mseconds to the register/hex value used when setting the register. Provide hex that gives a max time of n ms.
#define BATTPROT_OcrtMsecToHex(milliSeconds) ((uint8_t)(milliSeconds/0.5))
Conversion from mseconds to the register/hex value used when setting the register. Provide hex that gives a max time of n ms.
#define BATTPROT_REOCCURING_CHARGE_PROTECTION_GAP 3
#define BATTPROT_REOCCURING_CHARGE_PROTECTION_LIMIT 5
#define BATTPROT_ScrtUsecToHex(microSeconds) ((uint8_t)(microSeconds/62.5))
Conversion from useconds to the register/hex value used when setting the register. Provide hex that gives a max time of n us.
Typedefs
typedef enum
currentProtectionDetectionLevel_enum currentProtDetectLevel_t
Enumerator type for Battery protection level (BATTPROT).
Enumerations
enum currentProtectionDetectionLevel_enum {
BATTPROT_VMAX_5mV = 0xE0, BATTPROT_VMAX_10mV = 0xF1, BATTPROT_VMAX_15mV = 0xF2, BATTPROT_VMAX_20mV = 0xF3,
BATTPROT_VMAX_25mV = 0xF4, BATTPROT_VMAX_30mV = 0xF5, BATTPROT_VMAX_35mV = 0xF6, BATTPROT_VMAX_40mV = 0xF7,
BATTPROT_VMAX_45mV = 0xF8, BATTPROT_VMAX_50mV = 0xF9, BATTPROT_VMAX_55mV = 0xFA, BATTPROT_VMAX_60mV = 0xFB,
BATTPROT_VMAX_65mV = 0xFC, BATTPROT_VMAX_70mV = 0xFD, BATTPROT_VMAX_75mV = 0xFE, BATTPROT_VMAX_80mV = 0x77,
BATTPROT_VMAX_90mV = 0x78, BATTPROT_VMAX_100mV = 0x79, BATTPROT_VMAX_110mV = 0x7A, BATTPROT_VMAX_120mV = 0x7B,
BATTPROT_VMAX_130mV = 0x7C, BATTPROT_VMAX_140mV = 0x7D, BATTPROT_VMAX_160mV = 0x37, BATTPROT_VMAX_180mV = 0x38,
BATTPROT_VMAX_200mV = 0x39, BATTPROT_VMAX_220mV = 0x3A, BATTPROT_VMAX_240mV = 0x3B, BATTPROT_VMAX_260mV = 0x3C,
BATTPROT_VMAX_280mV = 0x3D, BATTPROT_VMAX_320mV = 0x17, BATTPROT_VMAX_360mV = 0x18, BATTPROT_VMAX_400mV = 0x19,
BATTPROT_VMAX_440mV = 0x1A
}
Functions
void BATTPROT_ClearChargeProtectionCounter (void)
Clear charge protection counter.
uint8_t BATTPROT_GetChargeProtectionCounter (void)
Get charge protection counter.
bool BATTPROT_IsProtectionTriggered (void)
Checks if Battery Protection has been triggered.
void BATTPROT_LockBatteryProtectionConfig (void)
Lock the battery protection settings (only unlocked by reset).
void BATTPROT_SetHighCurrentDetection (uint8_t dischargingLevel, uint8_t chargingLevel, uint8_t reacTime)
Set the charging high-current detection level and reaction time.
void BATTPROT_SetOverCurrentDetection (uint8_t dischargingLevel, uint8_t chargingLevel, uint8_t reacTime)
Set the discharging/charging over-current detection level and reaction time.
void BATTPROT_SetShortCircuitDetection (uint8_t dischargingLevel, uint8_t reacTime)
Set the short-circuit current detection level and reaction time.
Define Documentation
#define BATTPROT_DisableAllInterrupts () (BPIMSK = 0x00)
Disable all Battery Protection interrupts.
Definition at line 131 of file battery_protection.h.
#define BATTPROT_DisableChargeHighCurrentInterrupt () (BPIMSK &= ~(1<<CHCIE))
Disable charging high-current interrupt (Battery Protection Interrupt).
Definition at line 125 of file battery_protection.h.
#define BATTPROT_DisableChargeHighCurrentProtection () (BPCR |= (1<<CHCD))
Disable the charging high-current.
Definition at line 141 of file battery_protection.h.
#define BATTPROT_DisableChargeOverCurrentInterrupt () (BPIMSK &= ~(1<<COCIE))
Disable charging over-current interrupt (Battery Protection Interrupt).
Definition at line 123 of file battery_protection.h.
#define BATTPROT_DisableChargeOverCurrentProtection () (BPCR |= (1<<COCD))
Disable the charging over-current.
Definition at line 139 of file battery_protection.h.
#define BATTPROT_DisableDiscargeOverCurrentInterrupt () (BPIMSK &= ~(1<<DOCIE))
Disable discharging over-current interrupt (Battery Protection Interrupt).
Definition at line 127 of file battery_protection.h.
#define BATTPROT_DisableDischargeHighCurrentInterrupt () (BPIMSK &= ~(1<<DHCIE))
Disable discharging high-current interrupt (Battery Protection Interrupt).
Definition at line 129 of file battery_protection.h.
#define BATTPROT_DisableDischargeHighCurrentProtection () (BPCR |= (1<<DHCD))
Disable the discharging high-current.
Definition at line 145 of file battery_protection.h.
Referenced by main().
#define BATTPROT_DisableDischargeOverCurrentProtection () (BPCR |= (1<<DOCD))
Disable the discharging over-current.
Definition at line 143 of file battery_protection.h.
#define BATTPROT_DisableExternalInputProtection () (BPCR |= (1<<EPID))
Disable the external protection input.
Definition at line 135 of file battery_protection.h.
#define BATTPROT_DisableShortCircuitInterrupt () (BPIMSK &= ~(1<<SCIE))
Disable short-circuit (Battery Protection Interrupt).
Definition at line 121 of file battery_protection.h.
#define BATTPROT_DisableShortCircuitProtection () (BPCR |= (1<<SCD))
Disable the short-circuit protection.
Definition at line 137 of file battery_protection.h.
#define BATTPROT_EnableAllInterrupts () (BPIMSK = (1<<SCIE)|(1<<COCIE)|(1<<CHCIE)|(1<<DOCIE)|(1<<DHCIE))
Enable all Battery Protection interrupts.
Definition at line 130 of file battery_protection.h.
Referenced by main().
#define BATTPROT_EnableChargeHighCurrentInterrupt () (BPIMSK |= (1<<CHCIE))
Enable charging high-current interrupt (Battery Protection Interrupt).
Definition at line 124 of file battery_protection.h.
#define BATTPROT_EnableChargeHighCurrentProtection () (BPCR &= ~(1<<CHCD))
Enable the charging high-current protection (default enabled).
Definition at line 140 of file battery_protection.h.
#define BATTPROT_EnableChargeOverCurrentInterrupt () (BPIMSK |= (1<<COCIE))
Enable charging over-current interrupt (Battery Protection Interrupt).
Definition at line 122 of file battery_protection.h.
#define BATTPROT_EnableChargeOverCurrentProtection () (BPCR &= ~(1<<COCD))
Enable the charging over-current protection (default enabled).
Definition at line 138 of file battery_protection.h.
#define BATTPROT_EnableDiscargeOverCurrentInterrupt () (BPIMSK |= (1<<DOCIE))
Enable discharging over-current interrupt (Battery Protection Interrupt).
Definition at line 126 of file battery_protection.h.
#define BATTPROT_EnableDischargeHighCurrentInterrupt () (BPIMSK |= (1<<DHCIE))
Enable discharging high-current interrupt (Battery Protection Interrupt).
Definition at line 128 of file battery_protection.h.
#define BATTPROT_EnableDischargeHighCurrentProtection () (BPCR &= ~(1<<DHCD))
Enable the discharging high-current protection (default enabled).
Definition at line 144 of file battery_protection.h.
#define BATTPROT_EnableDischargeOverCurrentProtection () (BPCR &= ~(1<<DOCD))
Enable the discharging over-current protection (default enabled).
Definition at line 142 of file battery_protection.h.
#define BATTPROT_EnableExternalInputProtection () (BPCR &= ~(1<<EPID))
Enable the external protection input (default enabled).
Definition at line 134 of file battery_protection.h.
#define BATTPROT_EnableShortCircuitInterrupt () (BPIMSK |= (1<<SCIE))
Enable short-circuit interrupt (Battery Protection Interrupt).
Definition at line 120 of file battery_protection.h.
#define BATTPROT_EnableShortCircuitProtection () (BPCR &= ~(1<<SCD))
Enable the short-circuit protection (default enabled).
Definition at line 136 of file battery_protection.h.
#define BATTPROT_HcrtMsecToHex (milliSeconds) ((uint8_t)(milliSeconds/2.0))
Conversion from mseconds to the register/hex value used when setting the register. Provide hex that gives a max time of n ms.
Definition at line 117 of file battery_protection.h.
#define BATTPROT_OcrtMsecToHex (milliSeconds) ((uint8_t)(milliSeconds/0.5))
Conversion from mseconds to the register/hex value used when setting the register. Provide hex that gives a max time of n ms.
Definition at line 116 of file battery_protection.h.
#define BATTPROT_REOCCURING_CHARGE_PROTECTION_GAP 3
Definition at line 110 of file battery_protection.h.
Referenced by runEverySecond().
#define BATTPROT_REOCCURING_CHARGE_PROTECTION_LIMIT 5
If charge protection occurs 5 times "in a row", the charge fet will get disabled until a discharge current is detected.
Because the FET automatically will be disabled for one second after a over/high current has occured, it will not occur again the second after. So to be able to count haw many times it has occured in a row, more then BATTPROT_REOCCURING_CHARGE_PROTECTION_GAP seconds have to elapse until it is not considered as in a row again.
Definition at line 109 of file battery_protection.h.
Referenced by runEverySecond().
#define BATTPROT_ScrtUsecToHex (microSeconds) ((uint8_t)(microSeconds/62.5))
Conversion from useconds to the register/hex value used when setting the register. Provide hex that gives a max time of n us.
Definition at line 115 of file battery_protection.h.
Typedef Documentation
typedef enum currentProtectionDetectionLevel_enum currentProtDetectLevel_t
Enumerator type for Battery protection level (BATTPROT).
Enumeration Type Documentation
enum currentProtectionDetectionLevel_enum
Enumerator:
BATTPROT_VMAX_5mV
BATTPROT_VMAX_10mV
BATTPROT_VMAX_15mV
BATTPROT_VMAX_20mV
BATTPROT_VMAX_25mV
BATTPROT_VMAX_30mV
BATTPROT_VMAX_35mV
BATTPROT_VMAX_40mV
BATTPROT_VMAX_45mV
BATTPROT_VMAX_50mV
BATTPROT_VMAX_55mV
BATTPROT_VMAX_60mV
BATTPROT_VMAX_65mV
BATTPROT_VMAX_70mV
BATTPROT_VMAX_75mV
BATTPROT_VMAX_80mV
BATTPROT_VMAX_90mV
BATTPROT_VMAX_100mV
BATTPROT_VMAX_110mV
BATTPROT_VMAX_120mV
BATTPROT_VMAX_130mV
BATTPROT_VMAX_140mV
BATTPROT_VMAX_160mV
BATTPROT_VMAX_180mV
BATTPROT_VMAX_200mV
BATTPROT_VMAX_220mV
BATTPROT_VMAX_240mV
BATTPROT_VMAX_260mV
BATTPROT_VMAX_280mV
BATTPROT_VMAX_320mV
BATTPROT_VMAX_360mV
BATTPROT_VMAX_400mV
BATTPROT_VMAX_440mV
Definition at line 59 of file battery_protection.h.
{
    BATTPROT_VMAX_5mV   = 0xE0,
    BATTPROT_VMAX_10mV  = 0xF1,
    BATTPROT_VMAX_15mV  = 0xF2,
    BATTPROT_VMAX_20mV  = 0xF3,
    BATTPROT_VMAX_25mV  = 0xF4,
    BATTPROT_VMAX_30mV  = 0xF5,
    BATTPROT_VMAX_35mV  = 0xF6,
    BATTPROT_VMAX_40mV  = 0xF7,
    BATTPROT_VMAX_45mV  = 0xF8,
    BATTPROT_VMAX_50mV  = 0xF9,
    BATTPROT_VMAX_55mV  = 0xFA,
    BATTPROT_VMAX_60mV  = 0xFB,
    BATTPROT_VMAX_65mV  = 0xFC,
    BATTPROT_VMAX_70mV  = 0xFD,
    BATTPROT_VMAX_75mV  = 0xFE,
    BATTPROT_VMAX_80mV  = 0x77,
    BATTPROT_VMAX_90mV  = 0x78,
    BATTPROT_VMAX_100mV = 0x79,
    BATTPROT_VMAX_110mV = 0x7A,
    BATTPROT_VMAX_120mV = 0x7B,
    BATTPROT_VMAX_130mV = 0x7C,
    BATTPROT_VMAX_140mV = 0x7D,
    BATTPROT_VMAX_160mV = 0x37,
    BATTPROT_VMAX_180mV = 0x38,
    BATTPROT_VMAX_200mV = 0x39,
    BATTPROT_VMAX_220mV = 0x3A,
    BATTPROT_VMAX_240mV = 0x3B,
    BATTPROT_VMAX_260mV = 0x3C,
    BATTPROT_VMAX_280mV = 0x3D,
    BATTPROT_VMAX_320mV = 0x17,
    BATTPROT_VMAX_360mV = 0x18,
    BATTPROT_VMAX_400mV = 0x19,
    BATTPROT_VMAX_440mV = 0x1A
} currentProtDetectLevel_t;
Function Documentation
void BATTPROT_ClearChargeProtectionCounter (void)
Clear charge protection counter.
Definition at line 188 of file battery_protection.c.
References chargeProtectionCounter.
Referenced by runEverySecond().
{
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    chargeProtectionCounter = 0;
    __restore_interrupt(interruptState);
}
uint8_t BATTPROT_GetChargeProtectionCounter (void)
Get charge protection counter.
Definition at line 201 of file battery_protection.c.
References chargeProtectionCounter.
Referenced by runEverySecond().
{
    uint8_t ret;
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    ret = chargeProtectionCounter;
    __restore_interrupt(interruptState);
    return ret;
}
bool BATTPROT_IsProtectionTriggered (void)
Checks if Battery Protection has been triggered.
Checks if the Battery Protection module has detected short-circuit, overcurrent or/and high-current. If true is returned a detection has occurred. By checking if detection has occurred the internal detecting flag is cleared.
Return values:
bool Will return true if the Battery Protection has been triggered, false otherwise.
Definition at line 175 of file battery_protection.c.
References batteryProtectionTriggered.
Referenced by handleSBSCommand(), and runEverySecond().
{
    bool temp = batteryProtectionTriggered;
    batteryProtectionTriggered = false;
    return temp;
}
void BATTPROT_LockBatteryProtectionConfig (void)
Lock the battery protection settings (only unlocked by reset).
Return values:
void.
Definition at line 159 of file battery_protection.c.
{
    uint8_t temp = (0<<BPPLE)|(1<<BPPL);
    BPPLR = (1<<BPPLE)|(1<<BPPL);
    BPPLR = temp;
}
void BATTPROT_SetHighCurrentDetection (uint8_t dischargingLevel, uint8_t chargingLevel, uint8_t reacTime)
Set the charging high-current detection level and reaction time.
Parameters:
dischargingLevel is an enumerator type that sets the level in Amps.
chargingLevel is an enumerator type that sets the level in Amps.
reacTime is the value to write to the timing register (BATTPROT_HcrtMsecToHex).
Return values:
void
Definition at line 147 of file battery_protection.c.
Referenced by main().
{
    BPHCTR = reacTime;
    BPDHCD = dischargingLevel;
    BPCHCD = chargingLevel;
}
void BATTPROT_SetOverCurrentDetection (uint8_t dischargingLevel, uint8_t chargingLevel, uint8_t reacTime)
Set the discharging/charging over-current detection level and reaction time.
Parameters:
dischargingLevel is an enumerator type that sets the level in Amps.
chargingLevel is an enumerator type that sets the level in Amps.
reacTime is the value to write to the timing register (BATTPROT_OcrtMsecToHex).
Return values:
void
Definition at line 131 of file battery_protection.c.
Referenced by main().
{
    BPOCTR = reacTime;
    BPDOCD = dischargingLevel;
    BPCOCD = chargingLevel;
}
void BATTPROT_SetShortCircuitDetection (uint8_t dischargingLevel, uint8_t reacTime)
Set the short-circuit current detection level and reaction time.
Parameters:
dischargingLevel is an enumerator type that sets the level in Amps.
reacTime is the value to write to the timing register (BATTPROT_ScrtUsecToHex).
Return values:
void
Definition at line 116 of file battery_protection.c.
Referenced by main().
{
    BPSCTR = reacTime;
    BPSCD = dischargingLevel;
}