@DOC_TITLE@
SmartBattery Device Application Note
battery_protection.c File Reference
Detailed Description
Battery Protection peripheral module driver.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file battery_protection.c.
#include "common.h"
#include "battery_protection.h"
Functions
__interrupt void BATTPROT_BatteryProtection_ISR (void)
void BATTPROT_ClearChargeProtectionCounter (void)
Clear charge protection counter.
uint8_t BATTPROT_GetChargeProtectionCounter (void)
Get charge protection counter.
bool BATTPROT_IsProtectionTriggered (void)
Checks if Battery Protection has been triggered.
void BATTPROT_LockBatteryProtectionConfig (void)
Lock the battery protection settings (only unlocked by reset).
void BATTPROT_SetHighCurrentDetection (uint8_t dischargingLevel, uint8_t chargingLevel, uint8_t reacTime)
Set the charging high-current detection level and reaction time.
void BATTPROT_SetOverCurrentDetection (uint8_t dischargingLevel, uint8_t chargingLevel, uint8_t reacTime)
Set the discharging/charging over-current detection level and reaction time.
void BATTPROT_SetShortCircuitDetection (uint8_t dischargingLevel, uint8_t reacTime)
Set the short-circuit current detection level and reaction time.
Variables
bool batteryProtectionTriggered = false
uint8_t chargeProtectionCounter = 0
Function Documentation
__interrupt void BATTPROT_BatteryProtection_ISR (void)
Definition at line 64 of file battery_protection.c.
References batteryProtectionTriggered, and chargeProtectionCounter.
{
    batteryProtectionTriggered = true;
    // If short circuit is detected
    if( BPIFR & (1<<SCIF) )
    {
        // TODO: Add short circuit handler here if the standard handling (reenabling) is not sufficient.
    }
    // If Discharging overcurrent is detected
    if( BPIFR & (1<<DOCIF) )
    {
        // TODO: Add discharging overcurrent handler here if the standard handling (reenabling) is not sufficient.
    }
    // If charging overcurrent is detected
    if( BPIFR & (1<<COCIF) )
    {
        // TODO: Add charging overcurrent handler here if the standard handling (reenabling) is not sufficient.
        chargeProtectionCounter++;
    }
    // If Discharging high-current is detected
    if( BPIFR & (1<<DHCIF) )
    {
        // TODO: Add discharging high-current handler here if the standard handling (reenabling) is not sufficient.
        chargeProtectionCounter++;
    }
    // If charging high-current is detected
    if( BPIFR & (1<<CHCIF) )
    {
        // TODO: Add charging high-current handler here if the standard handling (reenabling) is not sufficient.
    }
    // Clear all Bettery Protection interrupt flags.
    BPIFR = (1<<SCIF)|(1<<DOCIF)|(1<<COCIF)|(1<<DHCIF)|(1<<CHCIF);
}
void BATTPROT_ClearChargeProtectionCounter (void)
Clear charge protection counter.
Definition at line 188 of file battery_protection.c.
References chargeProtectionCounter.
Referenced by runEverySecond().
{
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    chargeProtectionCounter = 0;
    __restore_interrupt(interruptState);
}
uint8_t BATTPROT_GetChargeProtectionCounter (void)
Get charge protection counter.
Definition at line 201 of file battery_protection.c.
References chargeProtectionCounter.
Referenced by runEverySecond().
{
    uint8_t ret;
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    ret = chargeProtectionCounter;
    __restore_interrupt(interruptState);
    return ret;
}
bool BATTPROT_IsProtectionTriggered (void)
Checks if Battery Protection has been triggered.
Checks if the Battery Protection module has detected short-circuit, overcurrent or/and high-current. If true is returned a detection has occurred. By checking if detection has occurred the internal detecting flag is cleared.
Return values:
bool Will return true if the Battery Protection has been triggered, false otherwise.
Definition at line 175 of file battery_protection.c.
References batteryProtectionTriggered.
Referenced by handleSBSCommand(), and runEverySecond().
{
    bool temp = batteryProtectionTriggered;
    batteryProtectionTriggered = false;
    return temp;
}
void BATTPROT_LockBatteryProtectionConfig (void)
Lock the battery protection settings (only unlocked by reset).
Return values:
void.
Definition at line 159 of file battery_protection.c.
{
    uint8_t temp = (0<<BPPLE)|(1<<BPPL);
    BPPLR = (1<<BPPLE)|(1<<BPPL);
    BPPLR = temp;
}
void BATTPROT_SetHighCurrentDetection (uint8_t dischargingLevel, uint8_t chargingLevel, uint8_t reacTime)
Set the charging high-current detection level and reaction time.
Parameters:
dischargingLevel is an enumerator type that sets the level in Amps.
chargingLevel is an enumerator type that sets the level in Amps.
reacTime is the value to write to the timing register (BATTPROT_HcrtMsecToHex).
Return values:
void
Definition at line 147 of file battery_protection.c.
Referenced by main().
{
    BPHCTR = reacTime;
    BPDHCD = dischargingLevel;
    BPCHCD = chargingLevel;
}
void BATTPROT_SetOverCurrentDetection (uint8_t dischargingLevel, uint8_t chargingLevel, uint8_t reacTime)
Set the discharging/charging over-current detection level and reaction time.
Parameters:
dischargingLevel is an enumerator type that sets the level in Amps.
chargingLevel is an enumerator type that sets the level in Amps.
reacTime is the value to write to the timing register (BATTPROT_OcrtMsecToHex).
Return values:
void
Definition at line 131 of file battery_protection.c.
Referenced by main().
{
    BPOCTR = reacTime;
    BPDOCD = dischargingLevel;
    BPCOCD = chargingLevel;
}
void BATTPROT_SetShortCircuitDetection (uint8_t dischargingLevel, uint8_t reacTime)
Set the short-circuit current detection level and reaction time.
Parameters:
dischargingLevel is an enumerator type that sets the level in Amps.
reacTime is the value to write to the timing register (BATTPROT_ScrtUsecToHex).
Return values:
void
Definition at line 116 of file battery_protection.c.
Referenced by main().
{
    BPSCTR = reacTime;
    BPSCD = dischargingLevel;
}
Variable Documentation
bool batteryProtectionTriggered = false
Definition at line 57 of file battery_protection.c.
Referenced by BATTPROT_BatteryProtection_ISR(), and BATTPROT_IsProtectionTriggered().
uint8_t chargeProtectionCounter = 0
Definition at line 58 of file battery_protection.c.
Referenced by BATTPROT_BatteryProtection_ISR(), BATTPROT_ClearChargeProtectionCounter(), and BATTPROT_GetChargeProtectionCounter().