@DOC_TITLE@
SmartBattery Device Application Note
battery_current_monitoring.c File Reference
Detailed Description
CC-ADC result processing firmware module.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
6090
Date
2009-10-05 21:40:12 +0800 (Mon, 05 Oct 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file battery_current_monitoring.c.
#include "common.h"
#include "battery_pack_parameters.h"
#include "battery_current_monitoring.h"
#include "ccadc.h"
Functions
void BATTCUR_CalculateShuntCoeffient (uint16_t shuntResistance, uint8_t VrefSel)
Calculate the Shunt Coefficient for CCADC_Value to mA conversion.
int32_t BATTCUR_GetAverageCurrent (void)
Provide an estimate for the average current throughout the last minute (18-bit signed).
int32_t BATTCUR_GetCurrent (void)
Provides the current from the last CC-ADC reading (18-bit signed).
int32_t BATTCUR_GetOffsetCalibratedCurrent (void)
Provides the offset calibrated current from the last CC-ADC reading.
void BATTCUR_InitializeAverageCurrent (int32_t current)
Init the average current counter.
bool BATTCUR_IsCurrentLow (int32_t current)
Is the current below the limit that defines standby operation (time to enter low power mode?).
bool BATTCUR_IsDischargeOngoing (void)
Is the current charging or discharging the battery.
int32_t BATTCUR_mA2RccTicks (int16_t mA_in)
Convert mA to Rcc CCADC ticks.
int32_t BATTCUR_mA2Ticks (int16_t mA_in)
Convert mA to CCADC tick.
void BATTCUR_StoreCurrent (int32_t current)
Stores the current from the last CC-ADC reading (mV, 18-bit signed).
int16_t BATTCUR_Ticks2mA (int32_t ticks)
Convert CCADC ticks to mA.
void BATTCUR_UpdateAverageCurrent (int32_t current)
Calculates and stores the average current during the last minut (18-bit signed).
Variables
int32_t averageCurrent
uint16_t CCADC2mACoefficient
bool discharge
int32_t lastCurrent
int32_t lastOffsetCalibratedCurrent
Function Documentation
void BATTCUR_CalculateShuntCoeffient (uint16_t shuntResistance, uint8_t VrefSel)
Calculate the Shunt Coefficient for CCADC_Value to mA conversion.
The goal for this function is to find a coefficient that can be used in the following formula: CCADC_Value*coefficient = mA But since coefficient is a very small number, it is scaled up by 2^16, so the formula is: (CCADC_Value*coefficient)/2^16 = mA
Formula for Shunt Coefficient for CCADC_Value to mA conversion CCADC2mACoefficient = I(mA)*10^6/CCADC_Value = ref(mV)*10^6*2^16/(shunt(uohm)*2^17)
ref(mV): the internal reference voltage of CCADC with the unit "mV" shunt(uohm): the current sensor resistance with the unit "microOhm" 10^6: compensation for using the shunt with "microOhm" 2^17: the CCADC measurement result range 2^16: up-scaling to increase accuracy
Parameters:
shuntResistance Shunt resistance in microOhm
VrefSel Selects the voltage reference to use
Definition at line 224 of file battery_current_monitoring.c.
References CCADC2mACoefficient, CCADC_VOLTREF_110mV, and CCADC_VOLTREF_220mV.
Referenced by handleSBSCommand(), and main().
{
        // CCADC2mACoefficient = I(mA)*10^6/tick
        //                    = ref(mV)*10^6*2^16/(shunt(uohm)*2^17)
        // define: dividend = ref(mV)*10^6*2^16/*2^17
        // So:     CCADC2mACoefficient = dividend/shunt(uohm)
        // ref(mV):the internal reference voltage of CCADC with the unit "mV"
        // shunt(uohm): the current sensor resistance with the unit "microOhm"
        // 10^6:compensation for using the shunt with "microOhm"
        // 2^17:the CCADC measurement result range
        // 2^16:up-scaling to increase accuracy
    uint32_t dividend;
        // VrefSel==0, select 220mV as CCADC internal voltage reference
        // VrefSel==1, Select 110mV as CCADC internal voltage reference
        if(VrefSel==CCADC_VOLTREF_220mV){
            dividend = CCADC_VOLTREF_220mV * 500000;
    }else if(VrefSel==CCADC_VOLTREF_110mV){
            dividend = CCADC_VOLTREF_110mV * 500000;
        }
    dividend += (shuntResistance >> 1); // Add halv divisor to get rounding
    CCADC2mACoefficient = (uint16_t) (dividend/shuntResistance);
}
int32_t BATTCUR_GetAverageCurrent (void)
Provide an estimate for the average current throughout the last minute (18-bit signed).
Returns:
The average current flowing in/out of the battery pack (represented as mV accros the shunt).
Definition at line 150 of file battery_current_monitoring.c.
References AVERAGE_CURRENT_SCALING, and averageCurrent.
Referenced by handleSBSCommand(), main(), runEveryMinute(), SMBR_AbsSOC(), SMBR_AvgCurrent(), SMBR_AvgTTE(), SMBR_AvgTTF(), SMBR_RelSOC(), and SMBR_RemCap().
{
    if(averageCurrent < 0) {
        // TODO: perhaps round this division, but the value is not used for anything important so skip that for now
        return -(-averageCurrent >> AVERAGE_CURRENT_SCALING);
    } else {
        return (averageCurrent >> AVERAGE_CURRENT_SCALING);
    }
}
int32_t BATTCUR_GetCurrent (void)
Provides the current from the last CC-ADC reading (18-bit signed).
Returns:
The current flowing in/out of the battery pack (represented as mV accros the shunt).
Definition at line 94 of file battery_current_monitoring.c.
References lastCurrent.
Referenced by GASG_AtRateOK(), main(), SMBR_Current(), and SMBR_RunTTE().
{
    return lastCurrent;
}
int32_t BATTCUR_GetOffsetCalibratedCurrent (void)
Provides the offset calibrated current from the last CC-ADC reading.
Returns:
The current flowing in/out of the battery pack (represented as mV accros the shunt).
Definition at line 106 of file battery_current_monitoring.c.
References lastOffsetCalibratedCurrent.
Referenced by ConvertDigitalToCurrent(), handleNewCCADCResult(), handleSBSCommand(), and main().
{
    return lastOffsetCalibratedCurrent;
}
void BATTCUR_InitializeAverageCurrent (int32_t current)
Init the average current counter.
Parameters:
current First current
Definition at line 184 of file battery_current_monitoring.c.
References AVERAGE_CURRENT_SCALING, and averageCurrent.
Referenced by main().
{
    averageCurrent = current * (1<<AVERAGE_CURRENT_SCALING);
}
bool BATTCUR_IsCurrentLow (int32_t current)
Is the current below the limit that defines standby operation (time to enter low power mode?).
Parameters:
current The current to check if below standby operation limit (in CCADC ticks)
Returns:
Returns true if the current is below the "low" limit.
Definition at line 169 of file battery_current_monitoring.c.
References battParam_sramstruct::activeCurrentThresholdInTicks, and battParams_sram.
Referenced by handleNewCCADCResult().
{
    if(0 > current) {
        current = -current;
    }
    return ( (int32_t)battParams_sram.activeCurrentThresholdInTicks > current );
}
bool BATTCUR_IsDischargeOngoing (void)
Is the current charging or discharging the battery.
Uses the offset calibrated current
Returns:
Returns true if the current flow is in the discharging direction.
Definition at line 196 of file battery_current_monitoring.c.
References discharge.
Referenced by handleNewCCADCResult(), handleNewCellTemperature(), handleNewCellVoltage(), handleNewCoreTemperature(), and handleSBSCommand().
{
    return discharge;
}
int32_t BATTCUR_mA2RccTicks (int16_t mA_in)
Convert mA to Rcc CCADC ticks.
Parameters:
mA_in mA to convert to Rcc ticks
Definition at line 303 of file battery_current_monitoring.c.
References BATTCUR_mA2Ticks().
Referenced by CCADC_Init().
{
    uint32_t temp = (uint32_t) BATTCUR_mA2Ticks(mA_in);
    // Rcc ticks are 2^5 times as "big" as accumululating ticks
    temp >>= 5;
    return temp;
}
int32_t BATTCUR_mA2Ticks (int16_t mA_in)
Convert mA to CCADC tick.
Formula: ccadc_ticks = (mA*2^16)/CCADC2mACoefficient
Note:
mA cannot be higher than +- 16384 (ie, dont use more than 14 bits excluding the sign bit)
Parameters:
mA_in mA to convert to CCADC accumulating ticks
Definition at line 289 of file battery_current_monitoring.c.
References CCADC2mACoefficient.
Referenced by BATTCUR_mA2RccTicks(), BATTPARAM_InitSramParameters(), GASG_CalculateRemainingCapacityValues(), GASG_TimeToEmpty(), GASG_TimeToFull(), and handleNewCCADCResult().
{
    int32_t temp = (int32_t)mA_in*(1ul<<16); // 2^16
    temp /= (int32_t)CCADC2mACoefficient;
    return temp;
}
void BATTCUR_StoreCurrent (int32_t current)
Stores the current from the last CC-ADC reading (mV, 18-bit signed).
Parameters:
current The current flowing in/out of the battery pack (represented as mV accros the shunt).
Definition at line 77 of file battery_current_monitoring.c.
References CCADC_GetAccOffset(), discharge, lastCurrent, and lastOffsetCalibratedCurrent.
Referenced by main().
{
    lastCurrent = current;
    lastOffsetCalibratedCurrent = current + CCADC_GetAccOffset();
    if( 0 >= lastOffsetCalibratedCurrent) {
        discharge = true;
    } else {
        discharge = false;
    }
}
int16_t BATTCUR_Ticks2mA (int32_t ticks)
Convert CCADC ticks to mA.
Formula: (ccadc_ticks*CCADC2mACoefficient)/2^16 = mA
Note:
The ticks value must not be more than 15-bits, or else the calculation may overflow.
Parameters:
ticks CCADC accumulating ticks to convert to mA
Definition at line 262 of file battery_current_monitoring.c.
References CCADC2mACoefficient.
Referenced by ConvertDigitalToCurrent(), GASG_AtRateOK(), handleSBSCommand(), SMBR_AvgCurrent(), SMBR_AvgTTE(), SMBR_AvgTTF(), SMBR_Current(), and SMBR_RunTTE().
{
    ticks *= CCADC2mACoefficient;
    if(ticks >= 0) {
        ticks += (1ul<<15);
        ticks >>= 16;
    } else {
        ticks = -ticks;
        ticks += (1ul<<15);
        ticks >>= 16;
        ticks = -ticks;
    }
    return (int16_t)ticks;
}
void BATTCUR_UpdateAverageCurrent (int32_t current)
Calculates and stores the average current during the last minut (18-bit signed).
Assumes that the time base for the sampling is app 1 second. The average is calculated using an "exponential filter" and is an estimate for the average current. This method instead of a real average to reduce memory consumption.
Parameters:
current The current flowing in/out of the battery pack (represented as mV accros the shunt).
Definition at line 122 of file battery_current_monitoring.c.
References AVERAGE_CURRENT_SCALING, and averageCurrent.
Referenced by handleNewCCADCResult().
{
    // An exponential filter is used to
    // average = 31/32 * old value + 1/32 * new value.
    // But to remove the truncation error, the current is scaled up
    averageCurrent *= 31;
    averageCurrent += current * (1<<AVERAGE_CURRENT_SCALING);
    // Right-shifting works nice for dividing positive numbers, and oppositing if negative is
    // a lot faster than doing a division
    if(averageCurrent > 0) {
        // Add half divisor to get proper mathematical rounding
        averageCurrent += 16;
        averageCurrent >>= 5; // /32
    } else if (averageCurrent < 0) {
        averageCurrent = -averageCurrent;
        // Add half divisor to get proper mathematical rounding
        averageCurrent += 16;
        averageCurrent >>= 5; // /32
        averageCurrent = -averageCurrent;
    }
}
Variable Documentation
int32_t averageCurrent
Definition at line 62 of file battery_current_monitoring.c.
Referenced by BATTCUR_GetAverageCurrent(), BATTCUR_InitializeAverageCurrent(), and BATTCUR_UpdateAverageCurrent().
uint16_t CCADC2mACoefficient
Definition at line 64 of file battery_current_monitoring.c.
Referenced by BATTCUR_CalculateShuntCoeffient(), BATTCUR_mA2Ticks(), and BATTCUR_Ticks2mA().
bool discharge
Definition at line 61 of file battery_current_monitoring.c.
Referenced by BATTCUR_IsDischargeOngoing(), BATTCUR_StoreCurrent(), handleNewCellTemperature(), and handleNewCellVoltage().
int32_t lastCurrent
Definition at line 59 of file battery_current_monitoring.c.
Referenced by BATTCUR_GetCurrent(), and BATTCUR_StoreCurrent().
int32_t lastOffsetCalibratedCurrent
Definition at line 60 of file battery_current_monitoring.c.
Referenced by BATTCUR_GetOffsetCalibratedCurrent(), and BATTCUR_StoreCurrent().