@DOC_TITLE@
SmartBattery Device Application Note
ntc_rh163h103f.h File Reference
Detailed Description
Headerfile for ntc_rh163h103f.c.
Contains defines, typedefinitions and functions prototypes for ntc_rh163h103f.c.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file ntc_rh163h103f.h.
#include "common.h"
Functions
int16_t NTC_ReadTemperatureCelsius (uint16_t adc_voltage)
Convert ADC reading to degress celsius.
uint16_t NTC_ReadTemperatureKelvin (uint16_t adc_voltage)
Convert ADC reading to degress kelvin.
Function Documentation
int16_t NTC_ReadTemperatureCelsius (uint16_t ui_input_value)
Convert ADC reading to degress celsius.
This function uses the temperature data tables to find the corresponding temperature in °C. The resolution is given by the minor step size. The result is given as °C * number of minor steps/°C The data tables were generated by using typical numbers from the thermistor datasheet.
The function will return MinimumTemperature if temp is below minimum temp and will return MaximumTemperature if temperature is above maximum
Parameters:
ui_input_value Scaled mV
Returns:
Temperature (in 0.1 Celcius)
Definition at line 108 of file ntc_rh163h103f.c.
References NTC_MAJOR_STEPS, NTC_MAX_TEMPERATURE, NTC_MAX_TEMPERATURE_INDEX, NTC_MIN_TEMPERATURE, NTC_MIN_TEMPERATURE_INDEX, NTC_MINOR_STEPS, and ucft_voltage.
Referenced by NTC_ReadTemperatureKelvin().
{
    // Points to index of the voltage representing the closest major temp step below the last temperature
    // At reset it will be set to 20 degrees, as ambient temperature most likely is between 20 and 25 degrees
    static uint8_t uc_last_major_temp = (uint8_t)((20-NTC_MIN_TEMPERATURE)/NTC_MAJOR_STEPS);
    int16_t i_temperature;
    // If temperature is below minimum legal value, return that (minimum temperature = maximum voltage)
    if(ui_input_value >= ucft_voltage[NTC_MIN_TEMPERATURE_INDEX]) {
        return NTC_MIN_TEMPERATURE * NTC_MINOR_STEPS;
    }
    // If temperature is above maximum legal value, return that (minimum voltage = maximum temperature)
    if(ui_input_value <= ucft_voltage[NTC_MAX_TEMPERATURE_INDEX]) {
        return NTC_MAX_TEMPERATURE * NTC_MINOR_STEPS;
    }
    // Want uc_last_major_temp to point to the major temperature step just below the voltage ui_input_value represents
    // If voltage is higher than at uc_last_major_temp, search downwards
    // else, search upwards
    if(ui_input_value > ucft_voltage[uc_last_major_temp] ) {
        do {
            uc_last_major_temp--;
        } while(ui_input_value >= ucft_voltage[uc_last_major_temp]);
    } else {
        do {
            uc_last_major_temp++;
        } while(ui_input_value <= ucft_voltage[uc_last_major_temp]);
        uc_last_major_temp--; //Point to a lower temp/higher voltage than what ui_input_value_represents
    }
    // Requires TEMP_MIN_TEMPERATURE to be negative
    i_temperature = (uc_last_major_temp + NTC_MIN_TEMPERATURE/NTC_MAJOR_STEPS)*NTC_MINOR_STEPS*NTC_MAJOR_STEPS;
    // ui_input_value will now be between ucft_voltage[uc_last_major_temp] and ucft_voltage[uc_last_major_temp+1]
    // Linear interpolation to get temperature to add to i_temperature: (MinorSteps*MajorSteps*diff + roundFix)/divisor
    uint16_t diff = ucft_voltage[uc_last_major_temp] - ui_input_value;
    uint16_t divisor = ucft_voltage[uc_last_major_temp] - ucft_voltage[uc_last_major_temp+1];
    uint16_t roundFix = divisor>>1;
    i_temperature += (NTC_MAJOR_STEPS*NTC_MINOR_STEPS*diff + roundFix)/divisor;
    return(i_temperature);                                  // Return the converted temperature as temperature in °C * number of minor steps per °C
}
uint16_t NTC_ReadTemperatureKelvin (uint16_t ui_input_value)
Convert ADC reading to degress kelvin.
This function will just call NTC_ReadTemperatureCelsius and then add 273,1 degrees to the result
Parameters:
ui_input_value Scaled mV
Returns:
Temperature (in 0.1 Kelvin)
Definition at line 163 of file ntc_rh163h103f.c.
References NTC_ReadTemperatureCelsius().
Referenced by handleNewCellTemperature().
{
    return (uint16_t)(NTC_ReadTemperatureCelsius(ui_input_value) + 2731);
}