@DOC_TITLE@
SmartBattery Device Application Note
rc_calibration.h File Reference
Detailed Description
Defines and prototypes for rc_calibration.c.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file rc_calibration.h.
#include "common.h"
Defines
#define FAST_RC_NO_SEGMENTS (256/(1 << FAST_RC_SEGMENT_BIT))
Number of segments in Fast RC.
#define FAST_RC_SEGMENT_BIT (5)
FOSCCAL bit deciding range. Used for segment search.
#define FAST_RC_TARGET_MHZ SYSTEM_CLK_MHz
System clock frequency in Hz.
#define MAX_FAST_RC_ERROR (10)
Max error tolerated on Fast RC in ~0,1%, i.e. 10 ~= 1%.
#define RC_CALIB_CYCLES (8)
Number of calibration cycles cycles for OSI calibration.
#define RCCAL_IS_RUNNING() (TIMSK0 & (1<<ICIE0))
Checks if calibration is running (ie, if the input capture interrupt is enabled).
#define SLOW_RC (1 << OSISEL0)
For selecting Fast RC calibration source.
#define SLOW_RC_NOMINAL_PERIOD (7813)
Nominal period time for the Slow RC oscillator (1/131072), scaled by 2^10.
#define T0_PRESCALER (T0_PRESCALER_1)
#define ULP_RC (0 << OSISEL0)
For selecting Fast RC calibration source.
Typedefs
typedef enum TIM0_prescaler_enum TIM0_prescaler_t
Enumerations
enum RCCAL_CalibState_t { RCCAL_CALIB_INIT, RCCAL_CALIB_WORKING, RCCAL_CALIB_FINISHED, RCCAL_CALIB_FAILURE }
enum RCCAL_IC_State_t { RCCAL_IC_INITIAL_CAPTURE, RCCAL_IC_CAPTURES, RCCAL_IC_FINISHED }
enum TIM0_prescaler_enum {
T0_PRESCALER_0 = ((0 << CS02)|(0 << CS01)|(0 << CS00)), T0_PRESCALER_1 = ((0 << CS02)|(0 << CS01)|(1 << CS00)), T0_PRESCALER_8 = ((0 << CS02)|(1 << CS01)|(0 << CS00)), T0_PRESCALER_64 = ((0 << CS02)|(1 << CS01)|(1 << CS00)),
T0_PRESCALER_256 = ((1 << CS02)|(0 << CS01)|(0 << CS00)), T0_PRESCALER_1024 = ((1 << CS02)|(0 << CS01)|(1 << CS00))
}
Functions
uint16_t RCCAL_CalculateSlowRCperiod (int16_t temperature)
Calculate Slow RC period time.
uint16_t RCCAL_CalculateUlpRCperiod (int16_t temperature)
Calculate Ultra-low power RC (Ulp RC) period time.
void RCCAL_CalibrateFastRCruntime (uint16_t cal_RC_period)
Calibrate the Fast RC against the Slow RC oscillator runtime.
RCCAL_CalibState_t RCCAL_GetState ()
Returns the current state of fast rc calibration.
void RCCAL_StartCalibrateFastRC ()
Start the Fast RC calibration.
Define Documentation
#define FAST_RC_NO_SEGMENTS (256/(1 << FAST_RC_SEGMENT_BIT))
Number of segments in Fast RC.
Definition at line 75 of file rc_calibration.h.
#define FAST_RC_SEGMENT_BIT (5)
FOSCCAL bit deciding range. Used for segment search.
Definition at line 74 of file rc_calibration.h.
#define FAST_RC_TARGET_MHZ SYSTEM_CLK_MHz
System clock frequency in Hz.
Fast RC target frequency in Hz. Only whole MHz currently allowed.
Definition at line 71 of file rc_calibration.h.
Referenced by RCCAL_CalibrateFastRCruntime().
#define MAX_FAST_RC_ERROR (10)
Max error tolerated on Fast RC in ~0,1%, i.e. 10 ~= 1%.
Definition at line 76 of file rc_calibration.h.
#define RC_CALIB_CYCLES (8)
Number of calibration cycles cycles for OSI calibration.
Definition at line 78 of file rc_calibration.h.
Referenced by RCCAL_InputCapture_ISR().
#define RCCAL_IS_RUNNING () (TIMSK0 & (1<<ICIE0))
Checks if calibration is running (ie, if the input capture interrupt is enabled).
Definition at line 102 of file rc_calibration.h.
Referenced by main().
#define SLOW_RC (1 << OSISEL0)
For selecting Fast RC calibration source.
Definition at line 80 of file rc_calibration.h.
Referenced by RCCAL_CalibrateFastRCruntime().
#define SLOW_RC_NOMINAL_PERIOD (7813)
Nominal period time for the Slow RC oscillator (1/131072), scaled by 2^10.
Definition at line 72 of file rc_calibration.h.
#define T0_PRESCALER (T0_PRESCALER_1)
Definition at line 68 of file rc_calibration.h.
Referenced by RCCAL_StartOSIsampleClockPeriod().
#define ULP_RC (0 << OSISEL0)
For selecting Fast RC calibration source.
Definition at line 81 of file rc_calibration.h.
Typedef Documentation
typedef enum TIM0_prescaler_enum TIM0_prescaler_t
Enumeration Type Documentation
enum RCCAL_CalibState_t
Enumerator:
RCCAL_CALIB_INIT
RCCAL_CALIB_WORKING
RCCAL_CALIB_FINISHED
RCCAL_CALIB_FAILURE
Definition at line 83 of file rc_calibration.h.
             {
    RCCAL_CALIB_INIT,
    RCCAL_CALIB_WORKING,
    RCCAL_CALIB_FINISHED,
    RCCAL_CALIB_FAILURE
} RCCAL_CalibState_t;
enum RCCAL_IC_State_t
Enumerator:
RCCAL_IC_INITIAL_CAPTURE
RCCAL_IC_CAPTURES
RCCAL_IC_FINISHED
Definition at line 91 of file rc_calibration.h.
             {
    RCCAL_IC_INITIAL_CAPTURE,
    RCCAL_IC_CAPTURES,
    RCCAL_IC_FINISHED
} RCCAL_IC_State_t;
enum TIM0_prescaler_enum
Enumerator:
T0_PRESCALER_0
T0_PRESCALER_1
T0_PRESCALER_8
T0_PRESCALER_64
T0_PRESCALER_256
T0_PRESCALER_1024
Definition at line 59 of file rc_calibration.h.
{
    T0_PRESCALER_0 = ((0 << CS02)|(0 << CS01)|(0 << CS00)),
    T0_PRESCALER_1 = ((0 << CS02)|(0 << CS01)|(1 << CS00)),
    T0_PRESCALER_8 = ((0 << CS02)|(1 << CS01)|(0 << CS00)),
    T0_PRESCALER_64 = ((0 << CS02)|(1 << CS01)|(1 << CS00)),
    T0_PRESCALER_256 = ((1 << CS02)|(0 << CS01)|(0 << CS00)),
    T0_PRESCALER_1024 = ((1 << CS02)|(0 << CS01)|(1 << CS00))
} TIM0_prescaler_t;
Function Documentation
uint16_t RCCAL_CalculateSlowRCperiod (int16_t temperature)
Calculate Slow RC period time.
Calculate Slow RC period time given a temperature. The formula for calculation of Slow RC period is used with the signature data (loaded from the signature row) to calculate the actual period as described in the data sheet and application note. The result is in ms * 1024. It can thus be seen as ms in 16 bit fixed point format, with 10 fractional bits, i.e. 0x XXXX XX.xx xxxx xxxx.
Parameters:
temperature Temperature in Kelvin
Returns:
Slow RC period in ms*1024
Definition at line 85 of file rc_calibration.c.
References READ_SIGNATUREBYTE(), READ_SIGNATUREWORD(), SIG_SLOW_RC_L, SIG_SLOW_RC_PRED_L, SIG_TEMPERATURE_HOT, and ZERO_KELVIN.
Referenced by main().
{
    uint16_t slow_RC_period;
    int16_t  slow_RC_temperature_coeff;
    uint16_t calib_temperature;
    uint8_t interrupt_status = __save_interrupt();  // Disable interrupts.
    __disable_interrupt();
    //Read necessary data from the signature row. The delay cycles are to avoid
    //accessing the SPMCSR register within 6 cycles of previous write, since it
    //is locked for further writing during these cycles.
    slow_RC_period = READ_SIGNATUREWORD(SIG_SLOW_RC_L);
    slow_RC_temperature_coeff = READ_SIGNATUREWORD(SIG_SLOW_RC_PRED_L);
    calib_temperature = READ_SIGNATUREBYTE(SIG_TEMPERATURE_HOT) + ZERO_KELVIN;
    __restore_interrupt(interrupt_status);
    return (uint16_t)(slow_RC_period - ((temperature - calib_temperature)*slow_RC_temperature_coeff)/64);
}
uint16_t RCCAL_CalculateUlpRCperiod (int16_t temperature)
Calculate Ultra-low power RC (Ulp RC) period time.
Calculate Ulp RC period time given a temperature. The formula for calculation of Ulp RC period is used with the signature data (loaded from the signature row) to calculate the actual period as described in the data sheet and application note. The result is in ms * 1024. It can thus be seen as ms in 16 bit fixed point format, with 10 fractional bits, i.e. 0x XXXX XX.xx xxxx xxxx.
Parameters:
temperature Temperature in Kelvin
Returns:
Ulp RC period in ms*1024
Definition at line 123 of file rc_calibration.c.
References READ_SIGNATUREBYTE(), READ_SIGNATUREWORD(), SIG_TEMPERATURE_HOT, SIG_ULP_RC_L, SIG_ULP_RC_PRED_L, and ZERO_KELVIN.
Referenced by handleSBSCommand(), and main().
{
        uint16_t ulp_RC_period;
    int16_t  ulp_RC_temperature_coeff;
    uint16_t calib_temperature;
    uint8_t interrupt_status = __save_interrupt();  // Disable interrupts.
    __disable_interrupt();
    //Read necessary data from the signature row. The delay cycles are to avoid
    //accessing the SPMCSR register within 6 cycles of previous write, since it
    //is locked for further writing during these cycles.
    ulp_RC_period = READ_SIGNATUREWORD(SIG_ULP_RC_L);
    ulp_RC_temperature_coeff = READ_SIGNATUREWORD(SIG_ULP_RC_PRED_L);
    calib_temperature = READ_SIGNATUREBYTE(SIG_TEMPERATURE_HOT) + ZERO_KELVIN;
    __restore_interrupt(interrupt_status);
    return (uint16_t)(ulp_RC_period - ((temperature - calib_temperature)*ulp_RC_temperature_coeff)/64);
}
void RCCAL_CalibrateFastRCruntime (uint16_t cal_RC_period)
Calibrate the Fast RC against the Slow RC oscillator runtime.
Since the value we're searching for is probably close to the current we do a linear search. It searches the segment where FOSCCAL default is and the one below. When searching downwards we use the FOSC SEGMENT signature byte to avoid a jump in frequency when reaching the lower segment and thus giving a longer continous search range. FOSC segment is the first value in the previous segment that gives a lower frequency than the lowest value in the FOSCCAL default segment. If we reach the bottom of the lower segment or the top of the default segment we select the default FOSCCAL value and return failed as this range should provide a more than sufficient range for adjusting FOSCCAL over all temperatures, so something is wrong.
Note that no other boundary check is done, but even if the FOSCCAL value is outside the search range the frequency should be correctly calibrated, although jumps in frequency results will be encountered. If the FOSCCAL value is between the lowest value in FOSCCAL default segment and the FOSC SEGMENT, a value in that range might be selected.
Note:
Do not call with different cal_RC_period during the "working" part of the function. If the slow RC period change during calibration, re-run RCCAL_StartCalibrateFastRC() to re-initialize some variables.
Parameters:
cal_RC_period Slow RC period in ms * 1024
Definition at line 182 of file rc_calibration.c.
References FAST_RC_TARGET_MHZ, LastICResult, RCCAL_CALIB_FAILURE, RCCAL_CALIB_FINISHED, RCCAL_CALIB_INIT, RCCAL_CALIB_WORKING, RCCAL_CalibState, RCCAL_IC_FINISHED, RCCAL_IC_State, RCCAL_StartOSIsampleClockPeriod(), READ_SIGNATUREBYTE(), SIG_FOSC_SEGMENT, SIG_FOSCCAL_DEFAULT, and SLOW_RC.
Referenced by main().
{
    static uint8_t fosccal_segment;
    static uint8_t fosccal_default;
    static int16_t error;
    static int16_t last_error;
    static uint8_t fosccal_saved;
    uint8_t interrupt_status;
    switch(RCCAL_CalibState) {
    case RCCAL_CALIB_INIT:
        //Read necessary data from the signature row. The delay cycles are to avoid
        //accessing the SPMCSR register within 6 cycles of previous write, since it
        //is locked for further writing during these cycles.
            interrupt_status = __save_interrupt();  // Disable interrupts.
        __disable_interrupt();
        fosccal_default = READ_SIGNATUREBYTE(SIG_FOSCCAL_DEFAULT);
        fosccal_segment = READ_SIGNATUREBYTE(SIG_FOSC_SEGMENT);
        __restore_interrupt(interrupt_status);
        RCCAL_StartOSIsampleClockPeriod(SLOW_RC);
        RCCAL_CalibState = RCCAL_CALIB_WORKING;
        last_error = 32767; // last_error is invalid after a temperature change
        break;
    case RCCAL_CALIB_WORKING:
        {
            if(RCCAL_IC_FINISHED == RCCAL_IC_State) {
                uint8_t bottom_limit = fosccal_segment & 0xE0;
                uint8_t top_limit =  (fosccal_default & 0xE0) + 0x1F;
                uint16_t target_period = cal_RC_period * FAST_RC_TARGET_MHZ;    // Only whole MHz accounted for.
                error = LastICResult - target_period;
                // If absolute of last error is lower than absolute of current error, use the fosccal value from last test
                // (this happens when going from for example -4 error to +5 error)
                if(last_error < 0 && error > 0) {
                    if(-last_error < error) {
                        FOSCCAL = fosccal_saved;
                        RCCAL_CalibState = RCCAL_CALIB_FINISHED;
                        break;
                    }
                }
                if(last_error > 0 && error < 0) {
                    if(last_error < -error) {
                        FOSCCAL = fosccal_saved;
                        RCCAL_CalibState = RCCAL_CALIB_FINISHED;
                        break;
                    }
                }
                if(error > 0) {
                    // Search downwards.
                    uint8_t check_value = bottom_limit + 0x1F;
                    last_error = error;
                    fosccal_saved = FOSCCAL;
                    if ( FOSCCAL-- == check_value ) {
                        FOSCCAL = fosccal_segment;  // Use fosccal segment value to avoid a step in frequency when going to lower segment.
                    } else if (FOSCCAL < bottom_limit) {
                        FOSCCAL = fosccal_default;  // The range have been searched without success, so we select default fosccal value.
                        RCCAL_CalibState = RCCAL_CALIB_FAILURE;
                    }
                    RCCAL_StartOSIsampleClockPeriod(SLOW_RC);
                } else if (error < 0) {
                    // Search upwards.
                    uint8_t check_value = fosccal_segment + 0x01;
                    last_error = error;
                    fosccal_saved = FOSCCAL;
                    if ( FOSCCAL++ == check_value ) {
                        FOSCCAL = fosccal_default & 0xE0; // Use fosccal segment value to avoid a step in frequency when going to upper segment.
                    } else if ( FOSCCAL > top_limit ) {
                        FOSCCAL = fosccal_default;  // The range have been searched without success, so we select default fosccal value.
                        RCCAL_CalibState = RCCAL_CALIB_FAILURE;
                    }
                    RCCAL_StartOSIsampleClockPeriod(SLOW_RC);
                } else {
                    // error is equal to zero, so stop at this value
                    RCCAL_CalibState = RCCAL_CALIB_FINISHED;
                    break;
                }
            }
        }
        break;
    default:
        // If it gets here it's no error, probably the calibration is finished
        break;
    }
}
RCCAL_CalibState_t RCCAL_GetState ()
Returns the current state of fast rc calibration.
Definition at line 286 of file rc_calibration.c.
References RCCAL_CalibState.
Referenced by main().
{
    return RCCAL_CalibState;
}
void RCCAL_StartCalibrateFastRC ()
Start the Fast RC calibration.
Definition at line 150 of file rc_calibration.c.
References RCCAL_CALIB_INIT, and RCCAL_CalibState.
Referenced by main().
{
    RCCAL_CalibState = RCCAL_CALIB_INIT;
}