@DOC_TITLE@
SmartBattery Device Application Note
rtc.c File Reference
Detailed Description
Simple RTC.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file rtc.c.
#include "rtc.h"
#include "common.h"
Functions
bool RTC_AddSecond ()
Add one second to the time.
uint16_t RTC_GetMinutes ()
Return number of minutes since start.
Variables
static uint16_t minutes = 0
Number of minutes since startup modulus 2^16.
Function Documentation
bool RTC_AddSecond ()
Add one second to the time.
Should be called once every second from the timesource
Returns:
True if it's a new minute, false otherwise
Definition at line 77 of file rtc.c.
References minutes.
Referenced by runEverySecond().
                     {
    static uint8_t seconds = 0;
    ++seconds;
    if(seconds == 60) {
        ++minutes;
        seconds = 0;
        return true;
    }
    return false;
}
uint16_t RTC_GetMinutes ()
Return number of minutes since start.
Will overflow and start over from 0 after 65535 minutes (1092 hours or 45,5 days)
Definition at line 67 of file rtc.c.
References minutes.
Referenced by VBSoC_ResetTimer(), and VBSoC_Update().
{
    return minutes;
}
Variable Documentation
uint16_t minutes = 0 [static]
Number of minutes since startup modulus 2^16.
Definition at line 56 of file rtc.c.