@DOC_TITLE@
SmartBattery Device Application Note
SMBExample.h File Reference
Detailed Description
Atmel Corporation
File : SMBslave.h
Compiler : IAR EWAAVR 4.10b
Support mail : avr@atmel.com
Supported devices : All AVR devices with a TWI module can be used. The example is written for ATmega32
AppNote : AVR316 - SMBus slave
Description : Header file for SMBExample.c.
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Definition in file SMBExample.h.
#include "SMBSlave.h"
Defines
#define SMB_COMMAND_MULTIPLY_BY_TWO 0x60
#define SMB_COMMAND_READ_EE_BYTE 0x40
#define SMB_COMMAND_READ_EE_WORD 0x41
#define SMB_COMMAND_RETURN_SWITCHES 0x20
#define SMB_COMMAND_RETURN_VENDOR_STRING 0x10
#define SMB_COMMAND_SET_EE_POINTER 0x30
#define SMB_COMMAND_SUM_OF_BYTES 0x70
#define SMB_COMMAND_WRITE_LED_BLOCK 0x52
#define SMB_COMMAND_WRITE_LED_BYTE 0x50
#define SMB_COMMAND_WRITE_LED_WORD 0x51
Functions
void OutputLedBlock (SMBData *smb)
void OutputLedByte (SMBData *smb)
void OutputLedWord (SMBData *smb)
void ProcessMessage (SMBData *smb)
Prepares response to all supported protocols except Receive Byte.
void ProcessReceiveByte (SMBData *smb)
Prepares the response to a Receive Byte protocol..
void ReadEepromByte (SMBData *smb)
void ReadEepromWord (SMBData *smb)
void ReturnParameterTimesTwo (SMBData *smb)
void ReturnSumOfBytes (SMBData *smb)
void ReturnSwitchesPressed (SMBData *smb)
void ReturnVendorString (SMBData *smb)
void SetEepromPointer (SMBData *smb)
void UndefinedCommand (SMBData *smb)
Define Documentation
#define SMB_COMMAND_MULTIPLY_BY_TWO 0x60
Definition at line 36 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_READ_EE_BYTE 0x40
Definition at line 31 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_READ_EE_WORD 0x41
Definition at line 32 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_RETURN_SWITCHES 0x20
Definition at line 29 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_RETURN_VENDOR_STRING 0x10
Definition at line 28 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_SET_EE_POINTER 0x30
Definition at line 30 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_SUM_OF_BYTES 0x70
Definition at line 37 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_WRITE_LED_BLOCK 0x52
Definition at line 35 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_WRITE_LED_BYTE 0x50
Definition at line 33 of file SMBExample.h.
Referenced by ProcessMessage().
#define SMB_COMMAND_WRITE_LED_WORD 0x51
Definition at line 34 of file SMBExample.h.
Referenced by ProcessMessage().
Function Documentation
void OutputLedBlock (SMBData * smb)
void OutputLedByte (SMBData * smb)
void OutputLedWord (SMBData * smb)
void ProcessMessage (SMBData * smb)
Prepares response to all supported protocols except Receive Byte.
This function gets called whenever a Write byte, Write word, Read byte, Read word, Process call, Block write, Block read or Block write, block read process call protocol is in progress. The function is called rigth after a Stop or Repeated start condition is received.
This function, along with ProcessReceiveByte implements the application specific parts of the SMBus slave. For this reason, it can get very large. To remedy this, it has been broken up into one inlined function per command code.
Since the TWI module does not diffrentiate between a Stop condition and a repeated start condition, it is important that smb->state is set in this function, to reflect the state of the SMBus driver.
When this function is called, the data receieved is available through smb->rxBuffer array. All data received (excluding SLA+W) is available. The total number of valid bytes in smb->rxBuffer is available in smb->rxLength. The command code is always available in smb->rxBuffer[0]. The rest of the array is filled according to the SMBus specification.
For Write byte, Write word and Block write, data must simply be copied to their destination. smb->state should then be set to SMB_STATE_IDLE before returning.
For Read byte, Read word, Process call, Block read and Block write, block read process call, a response must be made ready and put in smb-txBuffer. The data in smb->txBuffer includes all data to be sent back by the SMBus driver (excluding PEC). The smb->txLength variable must be set to the total number of bytes to be transmitted (excluding PEC). When the response is complete, the smb-> state variable should be set to SMB_STATE_WRITE_READ_REQUESTED before returning.
In the following examples, it is explained how to prepare a response to these protocols.
Read byte:
smb->txBuffer[0] = Data byte
smb->txLength = 1
Read word / Process call:
smb->txBuffer[0] = Data byte low
smb->txBuffer[1] = Data byte high
smb->txLength = 2
Block read / Block write, block read process call:
smb->txBuffer[0] = Byte count (n)
smb->txBuffer[1] = Data byte 1
:
:
smb->txBuffer[n] = Data byte n
smb->txLength = n + 1
Parameters:
smb Pointer to the SMBus driver's SMBData struct.
Note:
While this runs the SMBCLK is held low, and it is thus important to keep the functions short enough not to violate the SMBus T_LOW:SEXT of 25ms. If this happens, the master will time out and drop the lines, and since the AVR's TWI module is I2C compatible there is no timeout in the TWI module. The AVR can then hold the SMBDAT line low waiting for clock, and thus block the bus indefinitely.
Definition at line 124 of file SMBExample.c.
References OutputLedBlock(), OutputLedByte(), OutputLedWord(), ReadEepromByte(), ReadEepromWord(), ReturnParameterTimesTwo(), ReturnSumOfBytes(), ReturnSwitchesPressed(), ReturnVendorString(), SetEepromPointer(), SMB_COMMAND_MULTIPLY_BY_TWO, SMB_COMMAND_READ_EE_BYTE, SMB_COMMAND_READ_EE_WORD, SMB_COMMAND_RETURN_SWITCHES, SMB_COMMAND_RETURN_VENDOR_STRING, SMB_COMMAND_SET_EE_POINTER, SMB_COMMAND_SUM_OF_BYTES, SMB_COMMAND_WRITE_LED_BLOCK, SMB_COMMAND_WRITE_LED_BYTE, SMB_COMMAND_WRITE_LED_WORD, and UndefinedCommand().
Referenced by SMBus_ISR().
{
    if (smb->state == SMB_STATE_WRITE_REQUESTED)
    {
        switch (smb->rxBuffer[0]) // Command code.
        {
            case SMB_COMMAND_RETURN_VENDOR_STRING:  // Block read, vendor ID.
                ReturnVendorString(smb);
                break;
            case SMB_COMMAND_RETURN_SWITCHES:  // Read byte, buttons.
                ReturnSwitchesPressed(smb);
                break;
            case SMB_COMMAND_SET_EE_POINTER:  // Write word, EEPROM pointer.
                SetEepromPointer(smb);
                break;
            case SMB_COMMAND_READ_EE_BYTE:  // Read byte, EEPROM data.
                ReadEepromByte(smb);
                break;
            case SMB_COMMAND_READ_EE_WORD:  // Read word, EEPROM data.
                ReadEepromWord(smb);
                break;
            case SMB_COMMAND_WRITE_LED_BYTE:  // Write byte, LEDs.
                OutputLedByte(smb);
                break;
            case SMB_COMMAND_WRITE_LED_WORD:  // Write word, LEDs.
                OutputLedWord(smb);
                break;
            case SMB_COMMAND_WRITE_LED_BLOCK:  // Block write, LEDs.
                OutputLedBlock(smb);
                break;
            case SMB_COMMAND_MULTIPLY_BY_TWO: // Process call, Multiply by two.
                ReturnParameterTimesTwo(smb);
                break;
            case SMB_COMMAND_SUM_OF_BYTES:  // Block write, block read process call. Sum of bytes.
                ReturnSumOfBytes(smb);
                break;
            default:
                UndefinedCommand(smb);
                break;
        }
    }
    else
    {
        smb->state = SMB_STATE_IDLE;
    }
}
void ProcessReceiveByte (SMBData * smb)
Prepares the response to a Receive Byte protocol..
This function gets called whenever a SLA+R has been received right after a Start condition. If the Receive byte protocol is supported, data should be put in smb->txBuffer[0] and smb->txLength should be set to 1.
Parameters:
smb Pointer to the SMBus driver's SMBData struct.
Note:
While this runs the SMBCLK is held low, and it is thus important to keep the functions short enough not to violate the SMBus T_LOW:SEXT of 25ms. If this happens, the master will time out and drop the lines, and since the AVR's TWI module is I2C compatible there is no timeout in the TWI module. The AVR can then hold the SMBDAT line low waiting for clock, and thus block the bus indefinitely.
Definition at line 52 of file SMBExample.c.
Referenced by SMBus_ISR().
{
    smb->txBuffer[0] = ~PIND;
    smb->txLength = 1;
}
void ReadEepromByte (SMBData * smb)
void ReadEepromWord (SMBData * smb)
void ReturnParameterTimesTwo (SMBData * smb)
void ReturnSumOfBytes (SMBData * smb)
void ReturnSwitchesPressed (SMBData * smb)
void ReturnVendorString (SMBData * smb)
void SetEepromPointer (SMBData * smb)
void UndefinedCommand (SMBData * smb)