@DOC_TITLE@
SmartBattery Device Application Note
SMBSlave.c File Reference
Detailed Description
Atmel Corporation
File : SMBslave.c
Compiler : IAR EWAAVR 4.10b
Support mail : avr@atmel.com
Supported devices : All AVR devices with a TWI module can be used. The example is written for ATmega32
AppNote : AVR316 - SMBus slave
Description : SMBus general driver implementation. Takes care of transmission and reception of data.
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Definition in file SMBSlave.c.
#include <ioavr.h>
#include <inavr.h>
#include "SMBSlave.h"
#include "device_specific.h"
Functions
static void SMBcrc (unsigned char data)
void SMBDisable (void)
Disable the SMBus driver.
void SMBEnable (void)
Enable the SMBus driver.
unsigned char SMBError (void)
Returns the error flag for the last message.
__interrupt void SMBus_ISR (void)
TWI interrupt routine.
void SMBusInit ()
Initialize TWI module.
Variables
SMBData smb
SMBus driver data.
Function Documentation
static void SMBcrc (unsigned char data) [static]
Referenced by SMBus_ISR().
void SMBDisable (void)
Disable the SMBus driver.
This function disables communications involving this device on the SMBus. Note that the slave address will still be ACKed according to the SMBus 2.0 specification.
Definition at line 62 of file SMBSlave.c.
References smb.
{
    smb.enable = FALSE;
}
void SMBEnable (void)
Enable the SMBus driver.
This function enables communications involving this device on the SMBus.
Definition at line 50 of file SMBSlave.c.
References smb.
{
    smb.enable = TRUE;
}
unsigned char SMBError (void)
Returns the error flag for the last message.
Returns the error flag for the last SMBus communication.
Return values:
1 There was an error in the last communication
0 The last SMBus communication was successful.
Definition at line 75 of file SMBSlave.c.
References smb.
{
    return smb.error;
}
__interrupt void SMBus_ISR (void)
TWI interrupt routine.
The TWI interrupt routine
Definition at line 86 of file SMBSlave.c.
References ProcessMessage(), ProcessReceiveByte(), smb, and SMBcrc().
{
    unsigned char enableACK;
    unsigned char temp;
    // Enable ACKing if not explicitly disabled later in this ISR.
    enableACK = TRUE;
    // Is this the start of a protocol?
    if (smb.state == SMB_STATE_IDLE)
    {
        // Reset SMBus variables.
        smb.txLength = 0;
        smb.txCount = 0;
        smb.rxCount = 0;
        smb.error = FALSE;
#ifdef SMB_SUPPORT_PEC
        smb.pec = 0;
#endif //SMB_SUPPORT_PEC
    }
    // Use the TWI status information to make desicions.
    switch (TWSR & 0xf8)
    {
        case 0x60:      // SLA + W received, ACK returned
        {
            // State should be IDLE when SLA+W is received. If SLA+W is received
            // and state is not IDLE, an error has probably occured in an earlier
            // transmission that could not be detected at the time. Nothing can be
            // done to rescue the last transmission, but the SMBus driver variables
            // should be reset so the ongoing transmission can complete correctly.
          if (smb.state != SMB_STATE_IDLE)
          {
              smb.txLength = 0;
              smb.txCount = 0;
              smb.rxCount = 0;
              smb.error = FALSE;
#ifdef SMB_SUPPORT_PEC
              smb.pec = 0;
#endif //SMB_SUPPORT_PEC
          }
          smb.state = SMB_STATE_WRITE_REQUESTED;
#ifdef SMB_SUPPORT_PEC
          SMBcrc(SMB_OWN_ADDRESS_W);
#endif //SMB_SUPPORT_PEC
          break;
        }
        case 0x80:      // Previously addressed with own SLA+W, data received, ACK returned
        {
            // Store data received in receive buffer and increase receive count.
            temp = TWDR;
            smb.rxBuffer[smb.rxCount] = temp;
            smb.rxCount++;
#ifdef SMB_SUPPORT_PEC
            // Calculate PEC.
            SMBcrc(temp);
#endif
            // If the receive buffer is full, disable ACKing of the next data byte.
            if (smb.rxCount == SMB_RX_BUFFER_LENGTH)
            {
                enableACK = FALSE;
            }
            break;
        }
        case 0x88:      // Previously addressed with own SLA+W, data received, NACK returned.
        {
            smb.error = TRUE;
            smb.state = SMB_STATE_IDLE;
            break;
        }
        case 0xa0:   // P or Sr received while still addressed.
        {
            ProcessMessage(&smb);
            break;
        }
        case 0xa8:  // Own SLA +R received, ACK returned.
        {
            // Calculate PEC of own address + R.
#ifdef SMB_SUPPORT_PEC
            SMBcrc(SMB_OWN_ADDRESS_R);
#endif
            if (smb.state == SMB_STATE_IDLE) // Receive byte.
            {
                ProcessReceiveByte(&smb);
                smb.state = SMB_STATE_READ_REQUESTED;
            }
            // Make the first byte of txBuffer ready for transmission.
            temp = smb.txBuffer[0];
            TWDR = temp;
            smb.txCount++;
#ifdef SMB_SUPPORT_PEC
            // Calculate PEC of sent byte.
            SMBcrc(temp);
#endif
            break;
        }
        case 0xb8:      // Data byte in TWDR transmitted, ACK received.
        {
            if (smb.txCount == smb.txLength)
            {
#ifdef SMB_SUPPORT_PEC
                TWDR = smb.pec;     // If PEC is enabled, an ACK is OK here.
#else
                smb.error = TRUE;   // If PEC is disabled, an ACK here is an error.
#endif //SMB_SUPPORT_PEC
                enableACK = FALSE;
            }
            else
            {
                temp = smb.txBuffer[smb.txCount];
                TWDR = temp;
                smb.txCount++;
#ifdef SMB_SUPPORT_PEC
                SMBcrc(temp);
#endif //SMB_SUPPORT_PEC
            }
            break;
        }
        case 0xc0:      // Data byte in TWDR transmitted, NACK received.
        {
            if (smb.txCount != smb.txLength)
            {
                // Error, NACK is only expected after last data byte or PEC.
                smb.error = TRUE;
            }
            smb.state = SMB_STATE_IDLE;
            break;
        }
        case 0xc8:      // Last data byte in TWDR transmitted, ACK received.
        {
            smb.error = TRUE;
            smb.state = SMB_STATE_IDLE;
            break;
        }
        case 0x00:      // Bus error due to an illegal START or STOP condition.
        {
            TWCR |= (1 << TWSTO);
            smb.error = TRUE;
            smb.state = SMB_STATE_IDLE;
            break;
        }
        default:        // Unexpected TWSR value, error.
        {
            smb.error = TRUE;
            smb.state = SMB_STATE_IDLE;
            break;
        }
    }
    // Issue next TWI command.
    if (enableACK)
    {
        // Set TWEA flag and don't clear TWINT (if set) at the same time.
        temp = TWCR;
        temp |= (1 << TWEA);
        temp &= ~(1 << TWINT);
        TWCR = temp;
    }
    else
    {
        // Clear TWEA flag and make sure that TWINT is not cleared at the same time.
        TWCR &= ~((1 << TWEA) | (1 << TWINT));
    }
    TWCR |= (1 << TWEN) | (1 << TWIE) | (1 << TWINT);
}
void SMBusInit ()
Initialize TWI module.
This function initializes the TWI module for SMBus operation.
Definition at line 37 of file SMBSlave.c.
{
    // Set own slave address
    TWAR = SMB_OWN_ADDRESS << 1;
    // Enable TWI-interface, enable ACK, enable interrupt, clear interrupt flag
    TWCR = (1 << TWINT) | (1 << TWEN) | (1 << TWIE) | (1 << TWEA);
}
Variable Documentation
SMBData smb
SMBus driver data.
Definition at line 31 of file SMBSlave.c.
Referenced by SMBDisable(), SMBEnable(), SMBError(), and SMBus_ISR().