@DOC_TITLE@
SmartBattery Device Application Note
smbus.c File Reference
Detailed Description
The communication file reads a command from the SMB bus and sends r/w, data and length information to SBS layer.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
6090
Date
2009-10-05 21:40:12 +0800 (Mon, 05 Oct 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file smbus.c.
#include "common.h"
#include "smbus.h"
#include "SBS_commands.h"
#include "interpreter.h"
#include "timer.h"
#include "battery_pack_parameters.h"
#include "gas_gauging.h"
Defines
#define MODULE_SMBUS
#define SMB_GenBusTimeout 1
#define SMB_GotCmdData 4
#define SMB_SetUpReply 2
Enumerations
enum {
TW_IDLE = 0, TW_Wait4Stop, TW_Wait4Cmd, TW_Wait4RW,
TW_Wait4Data, TW_ReplyData
}
Functions
uint8_t Comm_Flag (void)
Check Communication Status.
bool Comm_Handle (SBS_command_t *sbsCmdDestination)
Parse command.
void Comm_Init (void)
Initialize TWI module.
bool Comm_IsIdle (void)
Check Communication State.
void Comm_SbsBlockCommandReply (SBS_command_t *sbsReply)
Reply to a SBS read block command.
void Comm_SbsWordCommandReply (SBS_command_t *sbsReply)
Reply to a SBS read word command.
uint8_t SMB_PEC (uint8_t lastCRC, uint8_t newByte)
void SMB_RestoreBus (void)
__interrupt void TWI_ISR (void)
__interrupt void TWICD_ISR (void)
Variables
uint8_t CurrentCmd = 0xFF
uint8_t SMLOCK = 0
uint8_t TEST50US = 0
uint8_t TW_RxBuf [36]
int8_t TW_RxBufCnt = 0
uint8_t TW_RxBufIndex = 0
uint8_t TW_TxBuf [36]
uint8_t TW_TxBufCnt = 0
uint8_t TW_TxBufIndex = 0
volatile uint8_t TWI_CmdFlags
uint8_t TWISR_state = TW_IDLE
uint8_t UsePEC = 0
Define Documentation
#define MODULE_SMBUS
Definition at line 51 of file smbus.c.
#define SMB_GenBusTimeout 1
Definition at line 85 of file smbus.c.
#define SMB_GotCmdData 4
Definition at line 87 of file smbus.c.
#define SMB_SetUpReply 2
Definition at line 86 of file smbus.c.
Enumeration Type Documentation
anonymous enum
Enumerator:
TW_IDLE
TW_Wait4Stop
TW_Wait4Cmd
TW_Wait4RW
TW_Wait4Data
TW_ReplyData
Definition at line 333 of file smbus.c.
{TW_IDLE=0, TW_Wait4Stop, TW_Wait4Cmd, TW_Wait4RW, TW_Wait4Data, TW_ReplyData };
Function Documentation
uint8_t Comm_Flag (void)
Check Communication Status.
This function returns 0, if it is nothing to handle. If it is > 0, then execute Comm_Handle()
Returns:
0 if there is nothing to handle, > 0 there is
Definition at line 669 of file smbus.c.
References TWISR_state.
{
    return TWISR_state;  // TW_IDLE=0
}
bool Comm_Handle (SBS_command_t * sbsCmdDestination)
Parse command.
Check the command and send message to SBS for the protocol layer
It is important that if this function return true (receive is complete) that it is handles before this function is called again
Parameters:
sbsCmdDestination Where to save the incoming data
Returns:
True if a new command has been received and transferred to the destination buffer.
Definition at line 216 of file smbus.c.
References SBS_command_union::command, CurrentCmd, SBS_command_union::payload, SBS_READ, SBS_WRITE, SetGenericTimer(), SMB_GenBusTimeout, SMB_GotCmdData, SMB_PEC(), SMB_SetUpReply, SMBfaultTimer, TW_RxBuf, TW_RxBufCnt, TW_RxBufIndex, TW_TxBufCnt, TW_TxBufIndex, TWI_CmdFlags, and UsePEC.
{
    bool receiveComplete = false;
    uint8_t temp = 0;
    switch(TWI_CmdFlags)
    {
        case SMB_GenBusTimeout: //The ISR detected an error condition.
        TWI_CmdFlags = 0;           //clear the flag that brought us here.
        sbsCmdDestination->command = (SBS_commands_t) 0xFF;         //clear command register
        //start the 26mS timer.  When it is done, the Timer handler will re-init the TWI peripheral.
        SetGenericTimer(SMBfaultTimer, 26);
        break;
        case SMB_SetUpReply:       //interpret a 'Read' Command.
        TWI_CmdFlags = 0;           //clear the flag that brought us here.
        TW_TxBufIndex = 0;          //initialize
        TW_TxBufCnt = 0;            //initialize
        sbsCmdDestination->command = (SBS_commands_t) (CurrentCmd | SBS_READ);
        receiveComplete = true;
        break;
        case SMB_GotCmdData:    //process some received command+data.
        //NOTE: as of 6/17/2005, TWI_CmdFlags should NOT be cleared until we are
        // completely done processing this message, else the TWI ISR will overwrite
        // the RX buffer and won't respond with BUSY as it should.  Note also that
        // the TWI is fully re-enabled when entering here, so we MUST NOT write
        // to any of the TWI h/w registers or we could create havoc.  -rgf
        if(UsePEC)              //check the CRC of the received packet.
        {
            temp = 0;               //use this as our CRC value.
            do{
                temp = SMB_PEC(temp, TW_RxBuf[TW_RxBufIndex++]);
            }while(TW_RxBufCnt != TW_RxBufIndex);
            if(temp)    //The result of a CRC check SHOULD be =0 if all was ok.
            {
                //start the 26mS timer to generate a bus timeout error.
                SetGenericTimer(SMBfaultTimer, 26);
                receiveComplete = false;
                TWI_CmdFlags = 0;           //clear the flag that brought us here.
                break;
            }
        }
        //If more bytes than a word, a block has been received and omit length byte
        // Addr + Cmd + DataWord = 4 bytes
        if(TW_RxBufCnt > 4){
            TW_RxBufIndex = 3;      //Start of data in block
        }else{
            TW_RxBufIndex = 2;      //Start of data in word
        }
        temp = 0;
        do{
            sbsCmdDestination->payload[temp++] = TW_RxBuf[TW_RxBufIndex++];
        }while(TW_RxBufCnt != TW_RxBufIndex);
        sbsCmdDestination->command = (SBS_commands_t) (CurrentCmd | SBS_WRITE);
        receiveComplete = true;
        //At this point it looks like everything went OK.
        TW_RxBufIndex = 0;      //Wipe out anything in the buffer, just in case.
        TW_RxBufCnt = 0;
        TWI_CmdFlags = 0;           //clear the flag that brought us here.
        break;
        default:
        receiveComplete = false;
    }
    return receiveComplete;
}
void Comm_Init (void)
Initialize TWI module.
This function initializes the TWI module for SMBus operation.
Definition at line 104 of file smbus.c.
References SMB_RestoreBus().
{
    SMB_RestoreBus();
}
bool Comm_IsIdle (void)
Check Communication State.
This function returns true, if it is no ongoing comm. Then it is safe to enter psave
Returns:
true if idle, false if busy
Definition at line 656 of file smbus.c.
References TW_IDLE, and TWISR_state.
{
    return (TW_IDLE == TWISR_state);
}
void Comm_SbsBlockCommandReply (SBS_command_t * sbsReply)
Reply to a SBS read block command.
Parameters:
sbsReply Is a pointer to the SBS_command_t struct containing the data to transmit.
Definition at line 150 of file smbus.c.
References CurrentCmd, SBS_command_union::payload, SBSDATA_BLOCK_LENGTH, SMB_PEC(), TW_TxBuf, TW_TxBufCnt, and TW_TxBufIndex.
{
    uint8_t temp = 0;
    temp = SMB_PEC(temp, (TWAR & 0xFE));    //use the SLA+W address
    temp = SMB_PEC(temp, CurrentCmd);
    temp = SMB_PEC(temp, (TWAR | 1));   //use the SLA+R address
    TW_TxBuf[0] = SBSDATA_BLOCK_LENGTH;//Block Length
    temp = SMB_PEC(temp, TW_TxBuf[0]);
    TW_TxBufIndex = 1;
    TW_TxBufCnt = SBSDATA_BLOCK_LENGTH+1;
    do {
        TW_TxBuf[TW_TxBufIndex] = (uint8_t) sbsReply->payload[TW_TxBufIndex-1];
        temp = SMB_PEC(temp, TW_TxBuf[TW_TxBufIndex++]);
    }while(TW_TxBufIndex != TW_TxBufCnt);
    TW_TxBuf[TW_TxBufIndex] = temp; //append the CRC value on the end.
    TW_TxBufCnt++;          //increase the byte count for the PEC.
    TW_TxBufIndex = 0;      //Reset the buffer pointer.
    TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);  //have TWI continue from where it stalled.
}
void Comm_SbsWordCommandReply (SBS_command_t * sbsReply)
Reply to a SBS read word command.
Parameters:
sbsReply Is a pointer to the SBS_command_t struct containing the data to transmit.
Definition at line 181 of file smbus.c.
References CurrentCmd, SBS_command_union::payload, SMB_PEC(), TW_TxBuf, TW_TxBufCnt, and TW_TxBufIndex.
{
    uint8_t temp = 0;
    TW_TxBuf[0] = (uint8_t) sbsReply->payload[0];
    TW_TxBuf[1] = (uint8_t) sbsReply->payload[1];;
    temp = SMB_PEC(temp, (TWAR & 0xFE));    //use the SLA+W address
    temp = SMB_PEC(temp, CurrentCmd);
    temp = SMB_PEC(temp, (TWAR | 1));   //use the SLA+R address
    //Calculate PEC for Word
    temp = SMB_PEC(temp, TW_TxBuf[0]);
    temp = SMB_PEC(temp, TW_TxBuf[1]);
    TW_TxBuf[2] = temp;     //Append the CRC value on the end.
    TW_TxBufCnt = 3;        //Set the byte count for the Word + PEC.
    TW_TxBufIndex = 0;      //Reset the buffer pointer.
    TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);  //have TWI continue from where it stalled.
}
uint8_t SMB_PEC (uint8_t lastCRC, uint8_t newByte)
Definition at line 709 of file smbus.c.
References SMB_PEC_CRC_POLYNOME.
Referenced by Comm_Handle(), Comm_SbsBlockCommandReply(), and Comm_SbsWordCommandReply().
{
    // Initial XOR
    lastCRC ^= newByte;
    for(uint8_t i = 0; i < 8; i++){
        if (lastCRC & 0x80){
            lastCRC = (lastCRC << 1) ^ SMB_PEC_CRC_POLYNOME;
        }else{
            lastCRC <<= 1;
        }
    }
    return lastCRC;
}
void SMB_RestoreBus (void)
Definition at line 679 of file smbus.c.
References BATTERY_ADDR, TW_IDLE, and TWISR_state.
{
    TWCR = 0;               //shut down the peripheral
    TWISR_state = TW_IDLE;  //force an init of the state machine
    TWAR = BATTERY_ADDR<<1;
    TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);// | (1<<TWSTO); // re-enable
    //Note that we must be careful not to generate some kind of bus error
    // as a result of waking back up, or we will get into an endless loop
    // by generating another bus timeout if the IDLE state doesn't like
    // something it sees when it comes back to life.
}
__interrupt void TWI_ISR (void)
Definition at line 339 of file smbus.c.
References CurrentCmd, HIGHEST_SMB_CMD, SCRG, SCRW, SCWG, SCWW, SetGenericTimer(), SM_Cmd_Table, SMB_GenBusTimeout, SMB_GotCmdData, SMB_SetUpReply, SMBfaultTimer, SMBslave, TW_IDLE, TW_ReplyData, TW_RxBuf, TW_RxBufCnt, TW_RxBufIndex, TW_TxBuf, TW_TxBufCnt, TW_TxBufIndex, TW_Wait4Cmd, TW_Wait4Data, TW_Wait4RW, TW_Wait4Stop, TWI_CmdFlags, TWISR_state, TWS_RACK, TWS_RCMD, TWS_RDATA, TWS_REPEAT, TWS_RNAK, TWS_RSTOP, TWS_SLA_R, TWS_SLA_W, and UsePEC.
{
    //Command-related feature flags
    static uint8_t TWISR_CmdFeatures = 0;
    uint8_t Status;
    uint8_t tmp;
    //This identifies what caused the interrupt to fire.
    Status = TWSR & 0xF8;
    switch(TWISR_state){
        default:
        //If not SLA_W or RSTOP, is an error!
        case TW_IDLE:
        // Saw Slave address match with a Write bit
        if(TWS_SLA_W == Status)
        {
            if(TWI_CmdFlags == SMB_GotCmdData)
            {
                SetGenericTimer(SMBfaultTimer, 26);
                //Assert that we're 'busy' to SMBus Master by leaving TWEA *off* until we get a STOP.
                //Note that this is 'legal' because we have ALREADY sent an ACK to our Slave Address,
                // as is required by the SMBus specification.
                TWISR_state = TW_Wait4Stop;
                TWCR = (1<<TWINT) | (1<<TWEN) | (1<<TWIE);  //must NOT re-enable ACKing!
                break;
            }
            // Still waiting for command data.
            else
            {
                TWISR_state = TW_Wait4Cmd;
            }
        }
        //Saw a Stop, possibly left over from previous cmd.
        else if(TWS_RSTOP == Status)
        {
            //Everything is probably OK.  Take no action.
        }
        // Had some type of error!
        else
        {
            TWI_CmdFlags = SMB_GenBusTimeout;  //Generate a bus timeout.
            TWCR = (1<<TWEA) | (1<<TWEN);      //Disable int, and DON'T clear the TWINT flag!
            TWISR_state = TW_IDLE;             //Reset the state machine.
            break;
        }
        TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);  //must re-enable ACKing
        break;
        case TW_Wait4Stop:
        //Saw a Stop, possibly left over from previous cmd.
        if(TWS_RSTOP == Status)
        {
            TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);  //must re-enable ACKing
            TWISR_state = TW_IDLE;          //Reset the state machine.
        }
        //Error! Did not see a stop as expected. NACKing the rest.
        else
        {
            TWCR = (1<<TWINT) | (1<<TWEN) | (1<<TWIE);  //must NOT re-enable ACKing yet!
        }
        break;
        //SLAVE-mode states follow.
        // Upon entry, we expect to have received a Cmd byte.
        case TW_Wait4Cmd:
        //It appears that we have received a Command byte now.
        if(TWS_RCMD == Status)
        {
            tmp = TWDR;
            //Is the Cmd within valid range?
            if(tmp <= HIGHEST_SMB_CMD)
            {
                CurrentCmd = tmp;       //Save a copy.
                tmp = SM_Cmd_Table[tmp][0]; //Grab the Command Characteristics/Features flags.
                if(tmp & SMBslave)      //Is the Command valid for Slaves?
                {               //The command appears to be valid.
                    TWISR_CmdFeatures = tmp;    //Save the Feature flags for use in Wait4RW state.
                    TWISR_state = TW_Wait4RW;   //set up next state
                    TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);  //enable ACKing
                    break;
                }
            }
        }
        //In all cases except those that 'break' (above), it's an error.
        TWI_CmdFlags = SMB_GenBusTimeout;  //Generate a bus timeout.
        TWCR = (1<<TWEA) | (1<<TWEN);      //Disable int, and DON'T clear the TWINT flag!
        TWISR_state = TW_IDLE;             //Reset the state machine.
        break;
        //We will now find out if we will RX more, or we need to TX a reply instead.
        case TW_Wait4RW:
        //It is a WRITE-type command. Prep the RX buffer to accept more data.
        if(TWS_RDATA == Status)
        {
            //NOTE: except for OptionalMfgFunction5, all WRITE cmds are 2-byte, plus optional PEC.
            //Place all bytes of the transaction into the buffer so we can do a PEC on it if needed.
            TW_RxBuf[0] = TWAR & 0xFE;  //store everything incl. the slave address for computing PEC.
            TW_RxBuf[1] = CurrentCmd;   //store the previously-send Command.
            TW_RxBuf[2] = TWDR;     //store this first DATA byte
            TW_RxBufIndex = 3;      //use RxBufIndex as the index to store data in the buffer.
            //Is it a Write-WORD command type?
            if(TWISR_CmdFeatures & SCWW)
            {
                TW_RxBufCnt = 1;        //We expect 1 more data byte, and possibly PEC after that.
            }
            //Is it a write-BLOCK command (must be OptionalMfgFunction5 then)
            else if(TWISR_CmdFeatures & SCWG)
            {
                tmp = TWDR;
                if((tmp >= 1) && (tmp <= 32))
                    TW_RxBufCnt = TWDR;
                else
                {
                    TWI_CmdFlags = SMB_GenBusTimeout;  //Generate a bus timeout.
                    TWCR = (1<<TWEA) | (1<<TWEN);      //Disable int, and DON'T clear the TWINT flag!
                    TWISR_state = TW_IDLE;             //Reset the state machine.
                    break;
                }
            }
            //Error! This Command doesn't allow EITHER word OR group/block Writes! It's Read-only!
            else
            {
                TWI_CmdFlags = SMB_GenBusTimeout;  //Generate a bus timeout.
                TWCR = (1<<TWEA) | (1<<TWEN);      //Disable int, and DON'T clear the TWINT flag!
                TWISR_state = TW_IDLE;             //Reset the state machine.
                break;
            }
            TWISR_state = TW_Wait4Data;
            TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);  //enable ACKing
        }
        //We saw a re-Start, so must be getting ready for a Read cmd.
        else if(TWS_REPEAT == Status)
        {
            //Must now interpret previously-sent CurrentCmd & set up Reply data.
            //Is it a 'ReadWord' or 'ReadGroup' command type?
            if(TWISR_CmdFeatures & (SCRW | SCRG))
            {
                TWI_CmdFlags = SMB_SetUpReply;    //Foreground decoder will set up TWCR.
                TWISR_state = TW_ReplyData;       //Move to next state.
            }
            //Error! Not a valid read command.
            else
            {
                TWI_CmdFlags = SMB_GenBusTimeout;  //Generate a bus timeout.
                TWCR = (1<<TWEA) | (1<<TWEN);      //Disable int, and DON'T clear the TWINT flag!
                TWISR_state = TW_IDLE;             //Reset the state machine.
                break;
            }
            TWCR = (1<<TWEA) | (1<<TWEN);         //disable int, and DON'T clear the TWINT flag!
        }
        // Some type of error!
        else
        {
            TWI_CmdFlags = SMB_GenBusTimeout;  //Generate a bus timeout.
            TWCR = (1<<TWEA) | (1<<TWEN);      //Disable int, and DON'T clear the TWINT flag!
            TWISR_state = TW_IDLE;             //Reset the state machine.
            break;
        }
        break;
        //We are in Slave Receive operating mode.
        case TW_Wait4Data:
        // Received a data byte.
        if(TWS_RDATA == Status)
        {
            tmp = TWDR;
            //Are we past the PEC byte and still getting more data?
            if(--TW_RxBufCnt < -1)
            {
                TWI_CmdFlags = SMB_GenBusTimeout;  //Generate a bus timeout.
                TWCR = (1<<TWEA) | (1<<TWEN);      //Disable int, and DON'T clear the TWINT flag!
                TWISR_state = TW_IDLE;             //Reset the state machine.
                break;
            }
            //Store the byte in the buffer.
            TW_RxBuf[TW_RxBufIndex++] = tmp;
        }
        //Got a STOP; All done RXing data now.
        else if(TWS_RSTOP == Status)
        {
            //Note: If we get a STOP prematurely, then we simply ignore the command,
            //since it is too late to inform the Master of the error.
            if((TW_RxBufCnt > 0) || (TW_RxBufCnt < -1))
            {
                // We got a premature STOP or too much data; ERROR!
                // Error handling if needed.
            }
            else
            {
                if(0 == TW_RxBufCnt){
                    UsePEC = 0;            //there is no PEC coming for this packet.
                }else if(-1 == TW_RxBufCnt){
                    UsePEC = 1;            //PEC was included.
                }
                TW_RxBufCnt = TW_RxBufIndex;      //re-use the Write Index's value as the Valid Byte Count.
                TW_RxBufIndex = 0;                //clear the index in preparation for interpreting it.
                TWI_CmdFlags = SMB_GotCmdData;    //tell Foreground to process this now.
                //Note that when (TWI_CmdFlags == SMB_GotCmdData), TWI ISR will respond with BUSY condition.
            }
            TWISR_state = TW_IDLE;      //Reset the state machine in all cases.
        }
        //Some type of error during transmission!
        else
        {
            TWI_CmdFlags = SMB_GenBusTimeout;  //Generate a bus timeout.
            TWCR = (1<<TWEA) | (1<<TWEN);      //Disable int, and DON'T clear the TWINT flag!
            TWISR_state = TW_IDLE;             //Reset the state machine.
            break;
        }
        TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);  //enable ACKing
        break;
        // We are now in Slave Transmit operating mode.
        // The foreground code has set up the response that we are now sending.
        // Note: TW_TxBufCnt *always* includes the PEC byte! Since we don't
        // know whether the Master actually WANTS the PEC byte or not, we will
        // always TRY to send it, regardless of the state of the UsePEC flag.
        // If the Master does NOT want it, we will get a NAK while the PEC
        // byte is still in the buffer.  In the rare case where we send it all,
        // including the PEC byte, but we still get an ACK back, the TWI module
        // will be off-line anyway due to not setting the TWEA bit after sending PEC,
        // and we will therefore be unable to flag that an error has occurred.
        case TW_ReplyData:
        //Send out Reply data
        if((TWS_SLA_R == Status) || (TWS_RACK == Status))
        {
            //Get data next byte from buffer and send data out.
            TWDR = TW_TxBuf[TW_TxBufIndex++];
            //Have we emptied the buffer, incl. PEC?
            if(--TW_TxBufCnt == 0)
            {   // Yes, so don't set TWEA.
                TWCR = (1<<TWINT) | (1<<TWEN) | (1<<TWIE);
            }
            else
            {   // No, so assert TWEA.
                TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);
            }
        }
        //We may have gotten this validly or as an Error.
        else if(TWS_RNAK == Status)
        {
            //Not an error. Master didn't want PEC; clear UsePEC flag!
            if(TW_TxBufCnt == 1)
            {
                TW_TxBufCnt = 0;    //clear the buffer too.
                UsePEC = 0;
            }
            //Not an error. Master wanted PEC (and got it); assert UsePEC.
            else if(TW_TxBufCnt == 0)
            {
                UsePEC = 1;
            }
            //Some kind of error occurred; we got NAK too early!
            else
            {
                //Note: the TWI module is now OFF-LINE, so we can't inform Host of this error!!
            }
            //In all cases, go back to IDLE.
            TWISR_state = TW_IDLE;
            TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);
        }
        // if(TWS_FINAL == Status)  //ERROR: we got an ACK but we have no more data!
        // Since the TWI module is now in "Not Addressed Slave" mode, we can't flag the error
        // back to the Master DURING this transaction; we WILL assert an error status though.
        else
        {
            TWISR_state = TW_IDLE;  //Reset the state machine.
            TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);
        }
        break;
    } // end of switch(TWISR_state)
}
__interrupt void TWICD_ISR (void)
Definition at line 122 of file smbus.c.
{
    //clear bits per sbdat110, 4.4.2
    //SMBvariables[SMBV_BattMode][hibyte] &= ~(0xE3);
    if(TWBCSR & (1<<TWBCIP))    //this int was caused by bus DISCONNECT event.
    {
        TWBCSR &= ~(1<<TWBCIP);
//SH        ChangePowerMode(POWERMODE_IDLE,0);
    }
    else    //this int occurred due to a bus CONNECT event.
    {
        TWBCSR |= (1<<TWBCIP);
//SH        ChangePowerMode(POWERMODE_ACTIVE,0);
    }
}
Variable Documentation
uint8_t CurrentCmd = 0xFF
Definition at line 89 of file smbus.c.
uint8_t SMLOCK = 0
Definition at line 62 of file smbus.c.
uint8_t TEST50US = 0
Definition at line 61 of file smbus.c.
uint8_t TW_RxBuf[36]
Definition at line 74 of file smbus.c.
int8_t TW_RxBufCnt = 0
Definition at line 75 of file smbus.c.
uint8_t TW_RxBufIndex = 0
Definition at line 76 of file smbus.c.
uint8_t TW_TxBuf[36]
Definition at line 70 of file smbus.c.
uint8_t TW_TxBufCnt = 0
Definition at line 71 of file smbus.c.
uint8_t TW_TxBufIndex = 0
Definition at line 72 of file smbus.c.
volatile uint8_t TWI_CmdFlags
Definition at line 84 of file smbus.c.
uint8_t TWISR_state = TW_IDLE
Definition at line 335 of file smbus.c.
uint8_t UsePEC = 0
Definition at line 90 of file smbus.c.