@DOC_TITLE@
SmartBattery Device Application Note
smbus.h File Reference
Detailed Description
Headerfile for smbus.c.
Atmel Corporation
Application note:
AVR453: Smart Battery Reference Design
Documentation:
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5736
Date
2009-06-24 14:47:16 +0800 (Wed, 24 Jun 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file smbus.h.
#include "SBS_commands.h"
Defines
#define ALARM_MODE 0x20
#define BATTERY_ADDR 0x16
#define CAPACITY_MODE 0x80
#define CHARGE_CONTROLLER_ENABLED 0x01
#define CHARGER_ADDR 0x12
#define CHARGER_MODE 0x40
#define CONDITION_FLAG 0x80
#define DISCHARGING 0x40
#define FULLY_CHARGED 0x20
#define FULLY_DISCHARGED 0x10
#define hibyte 1
#define HIGHEST_SMB_CMD 0x3F
#define HOST_ADDR 0x10
#define INITIALIZED 0x80
#define INTERNAL_CHARGE_CONTROLLER 0x01
#define lobyte 0
#define OVER_CHARGED_ALARM 0x80
#define OVER_TEMP_ALARM 0x10
#define PRIMARY_BATTERY 0x02
#define PRIMARY_BATTERY_SUPPORT 0x02
#define REMAINING_CAPACITY_ALARM 0x02
#define REMAINING_TIME_ALARM 0x01
#define SBS_READ (0x80)
#define SBS_WRITE (0x00)
#define SMB_PEC_CRC_POLYNOME 0x07
The CRC polynome used in PEC calculation.
#define SMB_PEC_ROUTINE_SLOW
Define the wanted speed vs. code size wanted for the PEC calculation.
#define SMBerr_AccessDenied 0x04
#define SMBerr_BadSize 0x06
#define SMBerr_Busy 0x01
#define SMBerr_OK 0x00
#define SMBerr_OverUnderflow 0x05
#define SMBerr_ReservedCommand 0x02
#define SMBerr_UnknownError 0x07
#define SMBerr_UnsuptdCommand 0x03
#define SMBV_AbsSOC 14
#define SMBV_AtRate 4
#define SMBV_AtRateOK 7
#define SMBV_AtRateTTE 6
#define SMBV_AtRateTTF 5
#define SMBV_AvgCurrent 11
#define SMBV_AvgTTE 18
#define SMBV_AvgTTF 19
#define SMBV_BattMode 3
#define SMBV_BattStatus 22
#define SMBV_ChgCurrent 20
#define SMBV_ChgVoltage 21
#define SMBV_Current 10
#define SMBV_CycleCount 23
#define SMBV_DesignCap 24
#define SMBV_DesignVolt 25
#define SMBV_DeviceChem 34
#define SMBV_DeviceName 33
#define SMBV_FullChgCap 16
#define SMBV_MaxError 12
#define SMBV_MfrAccess 0
#define SMBV_MfrData 35
#define SMBV_MfrDate 27
#define SMBV_MfrName 32
#define SMBV_Opt1 0x3F
#define SMBV_Opt2 0x3E
#define SMBV_Opt3 0x3D
#define SMBV_Opt4 0x3C
#define SMBV_Opt5 0x2F
#define SMBV_RelSOC 13
#define SMBV_RemCap 15
#define SMBV_RemCapAlm 1
#define SMBV_RemTimeAlm 2
#define SMBV_RunTTE 17
#define SMBV_SerialNo 28
#define SMBV_SpecInfo 26
#define SMBV_Temperature 8
#define SMBV_Voltage 9
#define TERMINATE_CHARGE_ALARM 0x40
#define TERMINATE_DISCHARGE_ALARM 0x08
#define TWC_GO 0x85
#define TWC_READ_NoACK 0x85
#define TWC_RESTART 0xB5
#define TWC_START 0xA5
#define TWC_STOP 0x94
#define TWS_BERR 0x00
#define TWS_FINAL 0xC8
#define TWS_LOST_ARB 0x38
#define TWS_MASK 0xF8
#define TWS_NSTAT 0xF8
#define TWS_RACK 0xB8
#define TWS_RCMD 0x80
#define TWS_RDATA 0x80
#define TWS_READ_ACK 0x40
#define TWS_READ_NAK 0x48
#define TWS_REPEAT 0xA0
#define TWS_RESTART 0x10
#define TWS_RNAK 0xC0
#define TWS_RSTOP 0xA0
#define TWS_RXDATA_ACK 0x50
#define TWS_RXDATA_NACK 0x58
#define TWS_SLA_R 0xA8
#define TWS_SLA_W 0x60
#define TWS_START 0x08
#define TWS_TXDATA_ACK 0x28
#define TWS_TXDATA_NAK 0x30
#define TWS_WRITE_ACK 0x18
#define TWS_WRITE_NAK 0x20
Functions
uint8_t Comm_Flag (void)
Check Communication Status.
bool Comm_Handle (SBS_command_t *sbsCmdDestination)
Parse command.
void Comm_Init (void)
Initialize TWI module.
bool Comm_IsIdle (void)
Check Communication State.
void Comm_SbsBlockCommandReply (SBS_command_t *sbsReply)
Reply to a SBS read block command.
void Comm_SbsWordCommandReply (SBS_command_t *sbsReply)
Reply to a SBS read word command.
void InitSMBus (void)
uint8_t SMB_PEC (uint8_t lastCRC, uint8_t newByte)
void SMB_RestoreBus (void)
Define Documentation
#define ALARM_MODE 0x20
Definition at line 183 of file smbus.h.
#define BATTERY_ADDR 0x16
Definition at line 123 of file smbus.h.
#define CAPACITY_MODE 0x80
Definition at line 185 of file smbus.h.
#define CHARGE_CONTROLLER_ENABLED 0x01
Definition at line 181 of file smbus.h.
#define CHARGER_ADDR 0x12
Definition at line 122 of file smbus.h.
#define CHARGER_MODE 0x40
Definition at line 184 of file smbus.h.
#define CONDITION_FLAG 0x80
Definition at line 190 of file smbus.h.
#define DISCHARGING 0x40
Definition at line 209 of file smbus.h.
#define FULLY_CHARGED 0x20
Definition at line 210 of file smbus.h.
#define FULLY_DISCHARGED 0x10
Definition at line 211 of file smbus.h.
#define hibyte 1
Definition at line 173 of file smbus.h.
#define HIGHEST_SMB_CMD 0x3F
Definition at line 75 of file smbus.h.
#define HOST_ADDR 0x10
Definition at line 121 of file smbus.h.
#define INITIALIZED 0x80
Definition at line 207 of file smbus.h.
#define INTERNAL_CHARGE_CONTROLLER 0x01
Definition at line 188 of file smbus.h.
#define lobyte 0
Definition at line 172 of file smbus.h.
#define OVER_CHARGED_ALARM 0x80
Definition at line 198 of file smbus.h.
#define OVER_TEMP_ALARM 0x10
Definition at line 200 of file smbus.h.
#define PRIMARY_BATTERY 0x02
Definition at line 182 of file smbus.h.
#define PRIMARY_BATTERY_SUPPORT 0x02
Definition at line 189 of file smbus.h.
#define REMAINING_CAPACITY_ALARM 0x02
Definition at line 202 of file smbus.h.
#define REMAINING_TIME_ALARM 0x01
Definition at line 203 of file smbus.h.
#define SBS_READ (0x80)
Definition at line 71 of file smbus.h.
#define SBS_WRITE (0x00)
Definition at line 70 of file smbus.h.
#define SMB_PEC_CRC_POLYNOME 0x07
The CRC polynome used in PEC calculation.
Definition at line 228 of file smbus.h.
Referenced by SMB_PEC().
#define SMB_PEC_ROUTINE_SLOW
Define the wanted speed vs. code size wanted for the PEC calculation.
Definition at line 231 of file smbus.h.
#define SMBerr_AccessDenied 0x04
Definition at line 221 of file smbus.h.
#define SMBerr_BadSize 0x06
Definition at line 223 of file smbus.h.
#define SMBerr_Busy 0x01
Definition at line 215 of file smbus.h.
#define SMBerr_OK 0x00
Definition at line 214 of file smbus.h.
#define SMBerr_OverUnderflow 0x05
Definition at line 222 of file smbus.h.
#define SMBerr_ReservedCommand 0x02
Definition at line 216 of file smbus.h.
#define SMBerr_UnknownError 0x07
Definition at line 225 of file smbus.h.
#define SMBerr_UnsuptdCommand 0x03
Definition at line 219 of file smbus.h.
#define SMBV_AbsSOC 14
Definition at line 141 of file smbus.h.
#define SMBV_AtRate 4
Definition at line 130 of file smbus.h.
#define SMBV_AtRateOK 7
Definition at line 133 of file smbus.h.
#define SMBV_AtRateTTE 6
Definition at line 132 of file smbus.h.
#define SMBV_AtRateTTF 5
Definition at line 131 of file smbus.h.
#define SMBV_AvgCurrent 11
Definition at line 138 of file smbus.h.
#define SMBV_AvgTTE 18
Definition at line 146 of file smbus.h.
#define SMBV_AvgTTF 19
Definition at line 147 of file smbus.h.
#define SMBV_BattMode 3
Definition at line 129 of file smbus.h.
#define SMBV_BattStatus 22
Definition at line 150 of file smbus.h.
#define SMBV_ChgCurrent 20
Definition at line 148 of file smbus.h.
#define SMBV_ChgVoltage 21
Definition at line 149 of file smbus.h.
#define SMBV_Current 10
Definition at line 137 of file smbus.h.
#define SMBV_CycleCount 23
Definition at line 151 of file smbus.h.
#define SMBV_DesignCap 24
Definition at line 153 of file smbus.h.
#define SMBV_DesignVolt 25
Definition at line 154 of file smbus.h.
#define SMBV_DeviceChem 34
Definition at line 161 of file smbus.h.
#define SMBV_DeviceName 33
Definition at line 160 of file smbus.h.
#define SMBV_FullChgCap 16
Definition at line 144 of file smbus.h.
#define SMBV_MaxError 12
Definition at line 139 of file smbus.h.
#define SMBV_MfrAccess 0
Definition at line 126 of file smbus.h.
#define SMBV_MfrData 35
Definition at line 162 of file smbus.h.
#define SMBV_MfrDate 27
Definition at line 156 of file smbus.h.
#define SMBV_MfrName 32
Definition at line 159 of file smbus.h.
#define SMBV_Opt1 0x3F
Definition at line 167 of file smbus.h.
#define SMBV_Opt2 0x3E
Definition at line 166 of file smbus.h.
#define SMBV_Opt3 0x3D
Definition at line 165 of file smbus.h.
#define SMBV_Opt4 0x3C
Definition at line 164 of file smbus.h.
#define SMBV_Opt5 0x2F
Definition at line 163 of file smbus.h.
#define SMBV_RelSOC 13
Definition at line 140 of file smbus.h.
#define SMBV_RemCap 15
Definition at line 142 of file smbus.h.
#define SMBV_RemCapAlm 1
Definition at line 127 of file smbus.h.
#define SMBV_RemTimeAlm 2
Definition at line 128 of file smbus.h.
#define SMBV_RunTTE 17
Definition at line 145 of file smbus.h.
#define SMBV_SerialNo 28
Definition at line 157 of file smbus.h.
#define SMBV_SpecInfo 26
Definition at line 155 of file smbus.h.
#define SMBV_Temperature 8
Definition at line 135 of file smbus.h.
#define SMBV_Voltage 9
Definition at line 136 of file smbus.h.
#define TERMINATE_CHARGE_ALARM 0x40
Definition at line 199 of file smbus.h.
#define TERMINATE_DISCHARGE_ALARM 0x08
Definition at line 201 of file smbus.h.
#define TWC_GO 0x85
Definition at line 115 of file smbus.h.
#define TWC_READ_NoACK 0x85
Definition at line 116 of file smbus.h.
#define TWC_RESTART 0xB5
Definition at line 119 of file smbus.h.
#define TWC_START 0xA5
Definition at line 117 of file smbus.h.
#define TWC_STOP 0x94
Definition at line 118 of file smbus.h.
#define TWS_BERR 0x00
Definition at line 110 of file smbus.h.
#define TWS_FINAL 0xC8
Definition at line 109 of file smbus.h.
#define TWS_LOST_ARB 0x38
Definition at line 92 of file smbus.h.
#define TWS_MASK 0xF8
Definition at line 82 of file smbus.h.
#define TWS_NSTAT 0xF8
Definition at line 83 of file smbus.h.
#define TWS_RACK 0xB8
Definition at line 107 of file smbus.h.
#define TWS_RCMD 0x80
Definition at line 104 of file smbus.h.
#define TWS_RDATA 0x80
Definition at line 103 of file smbus.h.
#define TWS_READ_ACK 0x40
Definition at line 94 of file smbus.h.
#define TWS_READ_NAK 0x48
Definition at line 95 of file smbus.h.
#define TWS_REPEAT 0xA0
Definition at line 106 of file smbus.h.
#define TWS_RESTART 0x10
Definition at line 87 of file smbus.h.
#define TWS_RNAK 0xC0
Definition at line 108 of file smbus.h.
#define TWS_RSTOP 0xA0
Definition at line 105 of file smbus.h.
#define TWS_RXDATA_ACK 0x50
Definition at line 96 of file smbus.h.
#define TWS_RXDATA_NACK 0x58
Definition at line 97 of file smbus.h.
#define TWS_SLA_R 0xA8
Definition at line 102 of file smbus.h.
#define TWS_SLA_W 0x60
Definition at line 101 of file smbus.h.
#define TWS_START 0x08
Definition at line 86 of file smbus.h.
#define TWS_TXDATA_ACK 0x28
Definition at line 90 of file smbus.h.
#define TWS_TXDATA_NAK 0x30
Definition at line 91 of file smbus.h.
#define TWS_WRITE_ACK 0x18
Definition at line 88 of file smbus.h.
#define TWS_WRITE_NAK 0x20
Definition at line 89 of file smbus.h.
Function Documentation
uint8_t Comm_Flag (void)
Check Communication Status.
This function returns 0, if it is nothing to handle. If it is > 0, then execute Comm_Handle()
Returns:
0 if there is nothing to handle, 1 is there is
This function returns 0, if it is nothing to handle. If it is > 0, then execute Comm_Handle()
Returns:
0 if there is nothing to handle, > 0 there is
Definition at line 331 of file communication.c.
References TWISR_state.
Referenced by main().
{
    return 0;
}
bool Comm_Handle (SBS_command_t * sbsCmdDestination)
Parse command.
Check the command and send message to SBS for the protocol layer
It is important that if this function return true (receive is complete) that it is handles before this function is called again
Parameters:
sbsCmdDestination Where to save the incoming data
Returns:
True if a new command has been received and transferred to the destination buffer.
Check the command and send message to SBS for the protocol layer
It is important that if this function return true (receive is complete) that it is handles before this function is called again
Parameters:
sbsCmdDestination Where to save the incoming data
Returns:
True if a new command has been received and transferred to the destination buffer.
Definition at line 194 of file communication.c.
References SBS_command_union::command, CurrentCmd, SBS_command_union::payload, SBS_READ, SBS_WRITE, SetGenericTimer(), SMB_GenBusTimeout, SMB_GotCmdData, SMB_PEC(), SMB_SetUpReply, SMBfaultTimer, TW_RxBuf, TW_RxBufCnt, TW_RxBufIndex, TW_TxBufCnt, TW_TxBufIndex, TWI_CmdFlags, and UsePEC.
Referenced by main().
{
    bool receiveComplete = false;
    /*
    // Clear the flag as early as possible to allow it to be set again and this
    // function called again
    CLEAR_FLAG(SW_UART_status, SW_UART_RX_COMPLETE );
    if( READ_FLAG(SW_UART_status, SW_UART_FRAME_ERROR) ) {
        // If a frame error has been received, treat it as a break and wait for
        // next command
        CLEAR_FLAG(SW_UART_status, SW_UART_FRAME_ERROR);
        CLEAR_FLAG(SW_UART_status, SW_UART_RX_BUFFER_OVERFLOW);
        COMM_State = COMM_WAITING_FOR_COMMAND;
    } else if( READ_FLAG(SW_UART_status, SW_UART_RX_BUFFER_OVERFLOW) ) {
        // If a buffer overflow occured, wait for a break
        CLEAR_FLAG(SW_UART_status, SW_UART_RX_BUFFER_OVERFLOW);
        COMM_State = COMM_WAITING_FOR_BREAK;
    } else {
        // Handle received data if any
        while( SW_UART_Data_Available() ) {
            if(receiveComplete) {
                // If receive is complete, but there is still data in the RX buffer,
                // something went wrong so reset everything and wait for a break
                CLEAR_FLAG(SW_UART_status, SW_UART_FRAME_ERROR);
                CLEAR_FLAG(SW_UART_status, SW_UART_RX_BUFFER_OVERFLOW);
                receiveComplete = false;
                SW_UART_Flush_Buffers();
                COMM_State = COMM_WAITING_FOR_BREAK;
            } else if( READ_FLAG(SW_UART_status, SW_UART_FRAME_ERROR) ) {
                // If a frame error has been received, treat it as a break and wait for
                // next command
                CLEAR_FLAG(SW_UART_status, SW_UART_FRAME_ERROR);
                CLEAR_FLAG(SW_UART_status, SW_UART_RX_BUFFER_OVERFLOW);
                COMM_State = COMM_WAITING_FOR_COMMAND;
            } else if( READ_FLAG(SW_UART_status, SW_UART_RX_BUFFER_OVERFLOW) ) {
                // If a buffer overflow occured, wait for a break
                CLEAR_FLAG(SW_UART_status, SW_UART_RX_BUFFER_OVERFLOW);
                COMM_State = COMM_WAITING_FOR_BREAK;
            } else {
                // Get the received data
                uint8_t data = SW_UART_Getchar();
                switch( COMM_State ) {
                case COMM_WAITING_FOR_BREAK:
                    {
                        // Do nothing. Break is handled outside the case switch
                        break;
                    }
                case COMM_WAITING_FOR_COMMAND:
                    {
                        // Allow to transmit data
                        CLEAR_FLAG(SW_UART_status, SW_UART_DECLINE_NEW_TX_DATA);
                        // Save command
                        sbsCmdDestination->command = (SBS_commands_t)data;
                        if( data & 0x80 ) {
                            // Read command
                            receiveComplete = true;
                            COMM_State = COMM_WAITING_FOR_COMMAND;
                        } else {
                            // Write command
                            COMM_State = COMM_RECEIVING_DATA;
                            COMM_ReceivedBytes = 0;
                            // Since only write commands are handled here, no need to remove
                            // the read/write bit when checking for block
                            if(   SBS_IsCommandStaticStringType((SBS_commands_t)(data))
                                 || SBS_IsCommandBlockDataType((SBS_commands_t)(data)) )
{
                                // Block command
                                COMM_BytesToReceive = SBSDATA_BLOCK_LENGTH ;
                            } else {
                                // Word command
                                COMM_BytesToReceive = 2;
                            }
                        }
                        //Send command back to the host and initialize the PEC
                        SW_UART_Transmit( data );
                        COMM_CalculatedPEC = 0;
                        CRC8_Update( &COMM_CalculatedPEC, data);
                        break;
                    }
                case COMM_RECEIVING_DATA:
                    {
                        if(COMM_ReceivedBytes == COMM_BytesToReceive) {
                            // All data bytes have been received, this is the PEC
                            if( data == COMM_CalculatedPEC ) {
                                receiveComplete = true;
                                // The function that handles receiveComplete has to send ACK
                                //  for write commands
                            } else {
                                // If the PEC was wrong, send NACK
                                SW_UART_Transmit(COMM_NACK);
                                COMM_State = COMM_WAITING_FOR_COMMAND;
                            }
                        } else {
                            // Add received byte to receive buffer and update PEC
                            sbsCmdDestination->payload[COMM_ReceivedBytes++] = data;
                            CRC8_Update(&COMM_CalculatedPEC, data);
                        }
                        break;
                    }
                } // switch(COMM_state)
            }
        } // while( SW_UART_Data_Available() )
    }
    */
    return receiveComplete;
}
void Comm_Init (void)
Initialize TWI module.
This function initializes the TWI module for SMBus operation.
Definition at line 106 of file communication.c.
References SMB_RestoreBus().
Referenced by main().
{
    SMB_RestoreBus();
    TWBCSR = (1<<TWBCIF) | (1<<TWBCIE) | (1<<TWBDT1) | (1<<TWBDT0) | (0<<TWBCIP);
}
bool Comm_IsIdle (void)
Check Communication State.
This function returns true, if it is no ongoing comm. Then it is safe to enter psave
Returns:
true if idle, false if busy
Definition at line 318 of file communication.c.
References TW_IDLE, and TWISR_state.
Referenced by main().
{
    return 1;
}
void Comm_SbsBlockCommandReply (SBS_command_t * sbsReply)
Reply to a SBS read block command.
Parameters:
sbsReply Is a pointer to the SBS_command_t struct containing the data to transmit.
Definition at line 153 of file communication.c.
References CurrentCmd, SBS_command_union::payload, SBSDATA_BLOCK_LENGTH, SMB_PEC(), TW_TxBuf, TW_TxBufCnt, and TW_TxBufIndex.
Referenced by handleSBSCommand().
{
/*  // Send the Data Payload and update PEC
    for( uint8_t i=0; i < SBSDATA_BLOCK_LENGTH; i++)
    {
        SW_UART_Transmit( sbsReply->payload[i] );
        CRC8_Update(&COMM_CalculatedPEC, sbsReply->payload[i] );
    }
    // Send the PEC
    SW_UART_Transmit( COMM_CalculatedPEC );
    */
}
void Comm_SbsWordCommandReply (SBS_command_t * sbsReply)
Reply to a SBS read word command.
Parameters:
sbsReply Is a pointer to the SBS_command_t struct containing the data to transmit.
Definition at line 170 of file communication.c.
References CurrentCmd, SBS_command_union::payload, SMB_PEC(), TW_TxBuf, TW_TxBufCnt, and TW_TxBufIndex.
Referenced by handleSBSCommand().
{
/*  // Send the Data Payload
    SW_UART_Transmit( sbsReply->payload[0] );
    SW_UART_Transmit( sbsReply->payload[1] );
    // Calculate the PEC and send it
    CRC8_Update( &COMM_CalculatedPEC, sbsReply->payload[0] );
    CRC8_Update( &COMM_CalculatedPEC, sbsReply->payload[1] );
    SW_UART_Transmit( COMM_CalculatedPEC );
    */
}
void InitSMBus (void)
uint8_t SMB_PEC (uint8_t lastCRC, uint8_t newByte)
Definition at line 709 of file smbus.c.
References SMB_PEC_CRC_POLYNOME.
Referenced by Comm_Handle(), Comm_SbsBlockCommandReply(), and Comm_SbsWordCommandReply().
{
    // Initial XOR
    lastCRC ^= newByte;
    for(uint8_t i = 0; i < 8; i++){
        if (lastCRC & 0x80){
            lastCRC = (lastCRC << 1) ^ SMB_PEC_CRC_POLYNOME;
        }else{
            lastCRC <<= 1;
        }
    }
    return lastCRC;
}
void SMB_RestoreBus (void)
Definition at line 826 of file communication.c.
References BATTERY_ADDR, TW_IDLE, and TWISR_state.
Referenced by Comm_Init(), and generictimer0expired().
{
    TWCR = 0;               //shut down the peripheral
    TWISR_state = TW_IDLE;  //force an init of the state machine
    TWAR = BATTERY_ADDR<<1;
    TWCR = (1<<TWINT) | (1<<TWEA) | (1<<TWEN) | (1<<TWIE);  // | (1<<TWSTO)  re-enable
    //Note that we must be careful not to generate some kind of bus error
    // as a result of waking back up, or we will get into an endless loop
    // by generating another bus timeout if the IDLE state doesn't like
    // something it sees when it comes back to life.
}