@DOC_TITLE@
SmartBattery Device Application Note
timer.c File Reference
Detailed Description
Timer routines.
Application note:
AVR438: Smart Battery Reference Design
Documentation:
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file timer.c.
#include "common.h"
#include "smbus.h"
#include "timer.h"
Defines
#define MODULE_TIMER
Typedefs
typedef void(* ptr2funcV_V)(void)
Functions
void generictimer0expired (void)
void generictimer1expired (void)
void generictimer2expired (void)
void generictimer3expired (void)
void generictimer4expired (void)
void generictimer5expired (void)
void generictimer6expired (void)
void generictimer7expired (void)
unsigned char GetGenericTimer (unsigned char index)
__interrupt void PCINT0_ISR (void)
void SetGenericTimer (unsigned char index, unsigned int delay)
void SetLEDbrightness (unsigned char value)
void SetLEDs (unsigned char LEDflags)
uint8_t ShowLedBusy (void)
__interrupt void T1_COMPB_ISR (void)
__interrupt void T1CMPA_ISR (void)
void T1init (void)
__interrupt void T1OVF_ISR (void)
Variables
ptr2funcV_V GenericExpire [8]
Define Documentation
#define MODULE_TIMER
Definition at line 52 of file timer.c.
Typedef Documentation
typedef void(* ptr2funcV_V)(void)
Definition at line 256 of file timer.c.
Function Documentation
void generictimer0expired (void)
Definition at line 202 of file timer.c.
References SMB_RestoreBus().
{
  SMB_RestoreBus();
}
void generictimer1expired (void)
Definition at line 207 of file timer.c.
{
//open for your use
}
void generictimer2expired (void)
Definition at line 212 of file timer.c.
{
//open for your use
}
void generictimer3expired (void)
Definition at line 217 of file timer.c.
{
//open for your use
}
void generictimer4expired (void)
Definition at line 222 of file timer.c.
{
//open for your use
}
void generictimer5expired (void)
Definition at line 227 of file timer.c.
{
//open for your use
}
void generictimer6expired (void)
Definition at line 232 of file timer.c.
{
//open for your use
}
void generictimer7expired (void)
Definition at line 237 of file timer.c.
{
//open for your use
}
unsigned char GetGenericTimer (unsigned char index)
Definition at line 250 of file timer.c.
References generictimer.
{
  return generictimer[index];
}
__interrupt void PCINT0_ISR (void)
Definition at line 143 of file timer.c.
References ButtonIsPushed.
{
    if(ButtonIsPushed()){
        PORTB |= 0x1F;
        LedTimeout = 1;
        TIMSK1 &= ~((1<<OCIE1A) | (1<<OCIE1B));//Disable both interrupts
        TIFR1 |= (1<<OCIE1A) | (1<<OCIE1B); //Clear flags
        TIMSK1 |= (1<<OCIE1B);//Enable CompB interrupt
        PCICR &= ~(0x01); // Disable pin change interrupt
    }
}
void SetGenericTimer (unsigned char index, unsigned int delay)
Definition at line 243 of file timer.c.
References generictimer.
Referenced by Comm_Handle(), SMB_CmdInterpreter(), and TWI_ISR().
{
  ++delay;
  delay >>= 1;  //convert from 1mS interval to 2mS resolution
  generictimer[index] = (unsigned char) delay;
}
void SetLEDbrightness (unsigned char value)
Definition at line 116 of file timer.c.
{
  //Don't let the LED brightness go higher than 250, just so that
  // we don't collide with the overflow interrupt.
  if(value <= 250)
    OCR1A = value;
  else
    OCR1A = 250;
}
void SetLEDs (unsigned char LEDflags)
Definition at line 126 of file timer.c.
References LEDs.
Referenced by main(), and T1init().
{
  LEDs = 0;
  if(LEDflags > 10) LEDs |= 0x01;
  if(LEDflags > 30) LEDs |= 0x02;
  if(LEDflags > 50) LEDs |= 0x04;
  if(LEDflags > 70) LEDs |= 0x08;
  if(LEDflags > 90) LEDs |= 0x10;
}
uint8_t ShowLedBusy (void)
Definition at line 106 of file timer.c.
Referenced by main().
{
    if (LedTimeout == 0){
        return false;
    }else{
        return true;
    }
}
__interrupt void T1_COMPB_ISR (void)
Definition at line 180 of file timer.c.
References ButtonIsPushed, LED_ON_TIMEOUT, LED_STATUS_TIMEOUT, and LEDs.
{
    if(ButtonIsPushed() && (LedTimeout <= LED_STATUS_TIMEOUT)){
        LedTimeout++;
    }else{
        if(LedTimeout >= LED_STATUS_TIMEOUT){
            PORTB = ~(ErrFlags & 0x1F);
        }else{
            PORTB = ~(LEDs & 0x1F);
        }
        LedTimeout = LED_ON_TIMEOUT;
        TIMSK1 &= ~((1<<OCIE1A) | (1<<OCIE1B));//Disable this interrupt
        TIFR1 |= (1<<OCIE1A) | (1<<OCIE1B); //Clear flags
        TIMSK1 |= (1<<OCIE1A);//Enable CompA interrupt
    }
}
__interrupt void T1CMPA_ISR (void)
Definition at line 162 of file timer.c.
{
    //PINB |= 0x1F;
    if(--LedTimeout == 0){
        PORTB |= 0x1F;
        TIMSK1 &= ~((1<<OCIE1A) | (1<<OCIE1B)); //Disable all comp interrupts
        PCICR |= 0x01; //Enable pin change interrupts again
    }
}
void T1init (void)
Definition at line 82 of file timer.c.
References SetLEDs().
Referenced by main().
{
    // Initialize LED pins
    PORTB |= 0x1F;
    DDRB |= 0x1F;
    SetLEDs(50);
    //Initialize button input pullup and pin change interrupt
    DDRA &= ~(1<<PORTA3);
    PORTA |= (1<<PORTA3);
    PCMSK0 = 0x08; //Enable Pin change interrupt on pin 3
    PCICR = 0x01; //Enable Pin change 0 interrupt
    // Configure the timers used for the LEDs
    TCCR1A = 0;
    TCCR1B = 2;     //prescale = 8
    OCR1A = 10;     //use 75% brightness level so we can see the waveform for testing
    OCR1B = 240;        //available for PWM use by FETs
    TIFR1 = 0x0F;       //force all timer interrupt flags to be cleared.
    TIMSK1 = (1<<TOIE1);// (1<<OCIE1A)|(1<<OCIE1B);     //enable interrupts as needed.
}
__interrupt void T1OVF_ISR (void)
Definition at line 277 of file timer.c.
References GenericExpire, and generictimer.
{
  unsigned int temp;
  unsigned char i;
  for(i=0; i<8; i++)
  {
    temp = generictimer[i];
    if(0 != temp)
    {
      temp--;
      generictimer[i] = temp;
      if(temp == 0) //when it hits 0, flag it!
        (GenericExpire[i])();
    }
  }
}
Variable Documentation
ptr2funcV_V GenericExpire[8]
Initial value:
{
  generictimer0expired,
  generictimer1expired,
  generictimer2expired,
  generictimer3expired,
  generictimer4expired,
  generictimer5expired,
  generictimer6expired,
  generictimer7expired
}
Definition at line 259 of file timer.c.
Referenced by T1OVF_ISR().