@DOC_TITLE@
SmartBattery Device Application Note
timer.h File Reference
Detailed Description
Headerfile for timer.c.
Application note:
AVR438: Smart Battery Reference Design
Documentation:
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file timer.h.
Defines
#define ButtonIsNotPushed() (PINA & (1<<PORTA3))
#define ButtonIsPushed() ((PINA & (1<<PORTA3))!= (1<<PORTA3))
#define genericTimer2 2
#define genericTimer3 3
#define genericTimer4 4
#define genericTimer5 5
#define genericTimer6 6
#define genericTimer7 7
#define LED_ON_TIMEOUT 2000
#define LED_STATUS_TIMEOUT 1024
#define OneQtrSecond 1
#define SMBfaultTimer 0
Functions
unsigned char GetGenericTimer (unsigned char index)
void SetGenericTimer (unsigned char index, unsigned int delay)
void SetLEDbrightness (unsigned char value)
void SetLEDs (unsigned char flags)
uint8_t ShowLedBusy (void)
void T1init (void)
Variables
unsigned char generictimer [8]
unsigned char LEDs
Define Documentation
#define ButtonIsNotPushed () (PINA & (1<<PORTA3))
Definition at line 59 of file timer.h.
#define ButtonIsPushed () ((PINA & (1<<PORTA3))!= (1<<PORTA3))
Definition at line 58 of file timer.h.
Referenced by PCINT0_ISR(), and T1_COMPB_ISR().
#define genericTimer2 2
Definition at line 82 of file timer.h.
#define genericTimer3 3
Definition at line 83 of file timer.h.
#define genericTimer4 4
Definition at line 84 of file timer.h.
#define genericTimer5 5
Definition at line 85 of file timer.h.
#define genericTimer6 6
Definition at line 86 of file timer.h.
#define genericTimer7 7
Definition at line 87 of file timer.h.
#define LED_ON_TIMEOUT 2000
Definition at line 61 of file timer.h.
Referenced by T1_COMPB_ISR().
#define LED_STATUS_TIMEOUT 1024
Definition at line 60 of file timer.h.
Referenced by T1_COMPB_ISR().
#define OneQtrSecond 1
Definition at line 81 of file timer.h.
#define SMBfaultTimer 0
Definition at line 80 of file timer.h.
Referenced by Comm_Handle(), SMB_CmdInterpreter(), and TWI_ISR().
Function Documentation
unsigned char GetGenericTimer (unsigned char index)
Definition at line 250 of file timer.c.
References generictimer.
{
  return generictimer[index];
}
void SetGenericTimer (unsigned char index, unsigned int delay)
Definition at line 243 of file timer.c.
References generictimer.
Referenced by Comm_Handle(), SMB_CmdInterpreter(), and TWI_ISR().
{
  ++delay;
  delay >>= 1;  //convert from 1mS interval to 2mS resolution
  generictimer[index] = (unsigned char) delay;
}
void SetLEDbrightness (unsigned char value)
Definition at line 116 of file timer.c.
{
  //Don't let the LED brightness go higher than 250, just so that
  // we don't collide with the overflow interrupt.
  if(value <= 250)
    OCR1A = value;
  else
    OCR1A = 250;
}
void SetLEDs (unsigned char flags)
Definition at line 126 of file timer.c.
References LEDs.
Referenced by main(), and T1init().
{
  LEDs = 0;
  if(LEDflags > 10) LEDs |= 0x01;
  if(LEDflags > 30) LEDs |= 0x02;
  if(LEDflags > 50) LEDs |= 0x04;
  if(LEDflags > 70) LEDs |= 0x08;
  if(LEDflags > 90) LEDs |= 0x10;
}
uint8_t ShowLedBusy (void)
Definition at line 106 of file timer.c.
Referenced by main().
{
    if (LedTimeout == 0){
        return false;
    }else{
        return true;
    }
}
void T1init (void)
Definition at line 82 of file timer.c.
References SetLEDs().
Referenced by main().
{
    // Initialize LED pins
    PORTB |= 0x1F;
    DDRB |= 0x1F;
    SetLEDs(50);
    //Initialize button input pullup and pin change interrupt
    DDRA &= ~(1<<PORTA3);
    PORTA |= (1<<PORTA3);
    PCMSK0 = 0x08; //Enable Pin change interrupt on pin 3
    PCICR = 0x01; //Enable Pin change 0 interrupt
    // Configure the timers used for the LEDs
    TCCR1A = 0;
    TCCR1B = 2;     //prescale = 8
    OCR1A = 10;     //use 75% brightness level so we can see the waveform for testing
    OCR1B = 240;        //available for PWM use by FETs
    TIFR1 = 0x0F;       //force all timer interrupt flags to be cleared.
    TIMSK1 = (1<<TOIE1);// (1<<OCIE1A)|(1<<OCIE1B);     //enable interrupts as needed.
}
Variable Documentation
unsigned char generictimer[8]
Referenced by GetGenericTimer(), SetGenericTimer(), and T1OVF_ISR().
unsigned char LEDs
Referenced by SetLEDs(), and T1_COMPB_ISR().