@DOC_TITLE@
SmartBattery Device Application Note
vadc.c File Reference
Detailed Description
Routines for VADC measurements.
This file contains all functions used for sapmling VADC inputs, that is Cells, normal vadc iputs that can be used for thermistor measurements, and lastly the internal temperature reference.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
6090
Date
2009-10-05 21:40:12 +0800 (Mon, 05 Oct 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file vadc.c.
#include "common.h"
#include "ATmega32HVB_signature.h"
#include "vadc.h"
Functions
err_t DUVR_DisableCheck (void)
Check if DUVR mode can be disabled and if so disable it.
bool VADC_Cell1VoltageReady (void)
Return true if new cell1 voltage readings are available.
bool VADC_CellTempReady (void)
Return true if new cell temperature readings are available.
void VADC_ClearReadyFlags ()
Clear the ready flags.
uint8_t VADC_GetScanConfig ()
Return the current ScanConfig.
void VADC_InitializeVadcCoefficients (void)
Return true if new cell2 voltage readings are available.
__interrupt void VADC_ISR (void)
Interrupt Service Function to measure VADC values.
uint16_t VADC_readCellVoltage (vadcIndex_t cellIndex)
Calculation of cell voltage.
uint16_t VADC_readSystemTemperature (void)
Calculation of chip temperature.
void VADC_ScanConfig (vadcIndex_t CellInputs, vadcIndex_t VadcInputs, vadcIndex_t vtempScan)
Select VADC channels to be scanned.
vadcState_t VADC_ScanState (void)
Check VADC scan status.
err_t VADC_StartScan (void)
Start a scan of all VADC channels.
bool VADC_VTempReady (void)
Return true if new core temperature reading s available.
Variables
static uint16_t cellGain [BATTPARAM_CELLS_IN_SERIES]
Gain coefficients for Cells.
static uint16_t cellMeasurement [BATTPARAM_CELLS_IN_SERIES]
Cell input samples from the vadc ISR.
static int8_t cellOffset [BATTPARAM_CELLS_IN_SERIES]
Offset for cells.
static uint16_t cellVoltage [BATTPARAM_CELLS_IN_SERIES]
Cell input voltage. Set to 0xFFFF if not calculated from latest cellMeasurement.
static uint8_t vadcScanConfig
VADC channel sampling config.
struct VADC_Status vadcStatus
static uint16_t vptatCoeff
Internal temperature sensor coefficient.
static uint16_t vtempMeasurement
VTEMP input sample from the vadc ISR.
Function Documentation
err_t DUVR_DisableCheck (void)
Check if DUVR mode can be disabled and if so disable it.
If the voltage on the cells are sufficiently high after a reset the Deep Under-Voltage Recovery (DUVR) mode should be disabled and possibly the Charge FET (CFET) enabled. This function assumes a VADC scan has been performed and uses the cell samples to calculate cell voltages.
Returns:
SUCCESS or FAILURE
Definition at line 560 of file vadc.c.
References CELL1, CELL2, CELL3, CELL4, FAILURE, SUCCESS, VADC_readCellVoltage(), and VB_DUVR_DFET.
Referenced by disableDUVRIfPossible().
{
    bool disableDuvr;
    bool enableDischargeFet;
    uint16_t temp_cell;
    temp_cell = VADC_readCellVoltage(CELL1);
    if ( temp_cell > battParams.cellDuvrDisableVoltage ) {
        disableDuvr = true;
        //FCSR |= (1 << CFE) | (1 << DUVRD);
        if ( temp_cell > (battParams.cellDuvrDisableVoltage + VB_DUVR_DFET) ) {
            enableDischargeFet = true;
        } else {
            enableDischargeFet = false;
        }
    } else {
        disableDuvr = false;
    }
    // If cell1 was above duvr disable limits, check if cell2 is
# if BATTPARAM_CELLS_IN_SERIES >= 2
    temp_cell = VADC_readCellVoltage(CELL2);
    if( disableDuvr ) {
        if ( temp_cell <= battParams.cellDuvrDisableVoltage ) {
            disableDuvr = false;
        } else if(enableDischargeFet) {
            if ( temp_cell <= (battParams.cellDuvrDisableVoltage + VB_DUVR_DFET) ) {
                enableDischargeFet = false;
            }
        }
    }
# endif
# if BATTPARAM_CELLS_IN_SERIES >= 3
    temp_cell = VADC_readCellVoltage(CELL3);
    if( disableDuvr ) {
        if ( temp_cell <= battParams.cellDuvrDisableVoltage ) {
            disableDuvr = false;
        } else if(enableDischargeFet) {
            if ( temp_cell <= (battParams.cellDuvrDisableVoltage + VB_DUVR_DFET) ) {
                enableDischargeFet = false;
            }
        }
    }
# endif
# if BATTPARAM_CELLS_IN_SERIES >= 4
    temp_cell = VADC_readCellVoltage(CELL4);
    if( disableDuvr ) {
        if ( temp_cell <= battParams.cellDuvrDisableVoltage ) {
            disableDuvr = false;
        } else if(enableDischargeFet) {
            if ( temp_cell <= (battParams.cellDuvrDisableVoltage + VB_DUVR_DFET) ) {
                enableDischargeFet = false;
            }
        }
    }
# endif
    if( disableDuvr ) {
        if( enableDischargeFet ) {
            FCSR = (1<<CFE) | (1<<DFE) | (1<<DUVRD);
        } else {
            FCSR = (1<<CFE) | (1<<DUVRD);
        }
        return SUCCESS;
    } else {
        return FAILURE;
    }
}
bool VADC_Cell1VoltageReady (void)
Return true if new cell1 voltage readings are available.
Definition at line 339 of file vadc.c.
References VADC_Status::cell1VoltageReady, and vadcStatus.
Referenced by main().
{
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    bool flagState = vadcStatus.cell1VoltageReady;
    __restore_interrupt( interruptState );
    return flagState;
}
bool VADC_CellTempReady (void)
Return true if new cell temperature readings are available.
Definition at line 313 of file vadc.c.
References VADC_Status::cellTempReady, and vadcStatus.
Referenced by main().
{
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    bool flagState = vadcStatus.cellTempReady;
    __restore_interrupt( interruptState );
    return flagState;
}
void VADC_ClearReadyFlags ()
Clear the ready flags.
Definition at line 150 of file vadc.c.
References VADC_Status::cell1VoltageReady, VADC_Status::cell2VoltageReady, VADC_Status::cell3VoltageReady, VADC_Status::cell4VoltageReady, VADC_Status::cellTempReady, vadcStatus, and VADC_Status::vtempReady.
Referenced by main(), and VADC_StartScan().
{
#if CELL_INPUTS >= 4
    vadcStatus.cell4VoltageReady = false;
#endif
#if CELL_INPUTS >= 3
    vadcStatus.cell3VoltageReady = false;
#endif
#if CELL_INPUTS >= 2
    vadcStatus.cell2VoltageReady = false;
#endif
    vadcStatus.cell1VoltageReady = false;
    vadcStatus.cellTempReady = false;
    vadcStatus.vtempReady = false;
}
uint8_t VADC_GetScanConfig ()
Return the current ScanConfig.
Definition at line 144 of file vadc.c.
References vadcScanConfig.
{
    return vadcScanConfig;
}
void VADC_InitializeVadcCoefficients (void)
Return true if new cell2 voltage readings are available.
Return true if new cell3 voltage readings are available
Return true if new cell4 voltage readings are available
Initialization of variables for cell voltage, adc voltage and vtemp calculations. The coefficients are stored in (file) global variables. Interrupts are disabled and re-enabled if needed afterwards.
Definition at line 405 of file vadc.c.
References cellGain, cellOffset, READ_SIGNATUREBYTE(), READ_SIGNATUREWORD(), SIG_VADC_ADC0_GAIN_L, SIG_VADC_ADC0_OFFSET, SIG_VADC_ADC1_GAIN_L, SIG_VADC_ADC1_OFFSET, SIG_VADC_CELL1_GAIN_L, SIG_VADC_CELL1_OFFSET, SIG_VADC_CELL2_GAIN_L, SIG_VADC_CELL2_OFFSET, SIG_VADC_CELL3_GAIN_L, SIG_VADC_CELL3_OFFSET, SIG_VADC_CELL4_GAIN_L, SIG_VADC_CELL4_OFFSET, SIG_VPTAT_L, and vptatCoeff.
Referenced by main().
{
    uint8_t interrupt_status = __save_interrupt();  // Disable interrupts.
    __disable_interrupt();
    cellGain[0] = READ_SIGNATUREWORD(SIG_VADC_CELL1_GAIN_L);
    cellOffset[0] = READ_SIGNATUREBYTE(SIG_VADC_CELL1_OFFSET);
#if CELL_INPUTS >= 2
    cellGain[1] = READ_SIGNATUREWORD(SIG_VADC_CELL2_GAIN_L);
    cellOffset[1] = READ_SIGNATUREBYTE(SIG_VADC_CELL2_OFFSET);
#endif
#if CELL_INPUTS >= 3
    cellGain[2] = READ_SIGNATUREWORD(SIG_VADC_CELL3_GAIN_L);
    cellOffset[2] = READ_SIGNATUREBYTE(SIG_VADC_CELL3_OFFSET);
#endif
#if CELL_INPUTS >= 4
    cellGain[3] = READ_SIGNATUREWORD(SIG_VADC_CELL4_GAIN_L);
    cellOffset[3] = READ_SIGNATUREBYTE(SIG_VADC_CELL4_OFFSET);
#endif
    vptatCoeff = READ_SIGNATUREWORD(SIG_VPTAT_L);
#if VADC_INPUTS >= 1
    vadcGain[0] = READ_SIGNATUREWORD(SIG_VADC_ADC0_GAIN_L);
    vadcOffset[0] = READ_SIGNATUREBYTE(SIG_VADC_ADC0_OFFSET);
#endif
#if VADC_INPUTS >= 2
    vadcGain[1] = READ_SIGNATUREWORD(SIG_VADC_ADC1_GAIN_L);
    vadcOffset[1] = READ_SIGNATUREBYTE(SIG_VADC_ADC1_OFFSET);
#endif
    __restore_interrupt(interrupt_status);
}
__interrupt void VADC_ISR (void)
Interrupt Service Function to measure VADC values.
This ISR scans all vadc channels selected by vadcScanConfig and then disables itself. It continues from the input selected in VADC_StartScan(). The order is fixed; VTEMP, ADC0, ADC1, CELL1 and CELL2 last. Measurements are stored in global variables vtempMeasurement, vadcMeasurement and cellMeasurement. Cells are measured last to give the possiblity to disable cell balancing (if applicable).
Definition at line 210 of file vadc.c.
References CELL1, VADC_Status::cell1VoltageReady, CELL2, VADC_Status::cell2VoltageReady, CELL3, VADC_Status::cell3VoltageReady, CELL4, VADC_Status::cell4VoltageReady, cellMeasurement, VADC_Status::cellTempReady, cellVoltage, VADC_Status::state, VADC0, VADC1, VADC_NOT_RUNNING, VADC_RUNNING, VADC_SCAN_FAILED, vadcScanConfig, vadcStatus, VTEMP, vtempMeasurement, and VADC_Status::vtempReady.
{
    uint8_t state;
    state = VADMUX;
    switch (state) {
    case VTEMP :
        vtempMeasurement = VADC;
        if (vadcScanConfig & (1 << VADC0) ) {
            VADMUX = VADC0;
        } else {
            VADMUX = CELL1;
        }
        vadcStatus.vtempReady = true;
        break;
#if VADC_INPUTS != 0
    case VADC0 :
        vadcMeasurement[0] = VADC;
        if ( vadcScanConfig & (1 << VADC1) ) {
            VADMUX = VADC1;
        } else {
            VADMUX = CELL1;
            vadcStatus.cellTempReady = true;
        }
        break;
  #if VADC_INPUTS >= 2
    case VADC1 :
        vadcMeasurement[1] = VADC;
        VADMUX = CELL1;
        vadcStatus.cellTempReady = true;
        break;
  #endif // VADC_INPUTS >= 2
#endif // VADC_INPUTS != 0
    case CELL1 :
        cellMeasurement[0] = VADC;
        cellVoltage[0] = 0xFFFF;
        vadcStatus.cell1VoltageReady = true;
        if ( vadcScanConfig & (1 << CELL2) ) {
            VADMUX = CELL2;
        } else {
            vadcStatus.state = VADC_NOT_RUNNING;
        }
        break;
#if CELL_INPUTS >= 2
    case CELL2 :
        cellMeasurement[1] = VADC;
        cellVoltage[1] = 0xFFFF;
        vadcStatus.cell2VoltageReady = true;
        if ( vadcScanConfig & (1 << CELL3) ) {
            VADMUX = CELL3;
        } else {
            vadcStatus.state = VADC_NOT_RUNNING;
        }
        break;
#endif // CELL_INPUTS >= 2
#if CELL_INPUTS >= 3
    case CELL3 :
        cellMeasurement[2] = VADC;
        cellVoltage[2] = 0xFFFF;
        vadcStatus.cell3VoltageReady = true;
        if ( vadcScanConfig & (1 << CELL4) ) {
            VADMUX = CELL4;
        } else {
            vadcStatus.state = VADC_NOT_RUNNING;
        }
        break;
#endif // CELL_INPUTS >= 3
#if CELL_INPUTS >= 4
    case CELL4 :
        cellMeasurement[3] = VADC;
        cellVoltage[3] = 0xFFFF;
        vadcStatus.cell4VoltageReady = true;
        vadcStatus.state = VADC_NOT_RUNNING;
        break;
#endif // CELL_INPUTS >= 4
        default:
        vadcStatus.state = VADC_SCAN_FAILED;
        break;
    }
    if (vadcStatus.state == VADC_RUNNING) {
        VADCSR |= (1 << VADSC);         // Start next conversion now.
    } else {
        VADCSR &= ~(1 << VADEN);        // Disable VADC (until next scan).
    }
}
uint16_t VADC_readCellVoltage (vadcIndex_t cellIndex)
Calculation of cell voltage.
Parameters:
cellIndex Which cell to calculate voltage for. The cellMeasurement array is used as source.
Returns:
Voltage for selected cell index [mV] or zero if not valid.
Definition at line 450 of file vadc.c.
References CELL1, CELL_INPUTS, cellGain, cellMeasurement, cellOffset, cellVoltage, and VADC_SCALE_BITS.
Referenced by BATTVMON_IsCellVoltageTooHigh(), BATTVMON_IsCellVoltageTooLow(), DUVR_DisableCheck(), GASG_AtRateOK(), handleNewCCADCResult(), handleNewCellVoltage(), handleSBSCommand(), SMBR_Voltage(), VBSoC_EstimatedSoC(), VBSoC_Init(), and VBSoC_Update().
{
    uint32_t calc;
    cellIndex -= CELL1;
    if (cellIndex < CELL_INPUTS) {
        uint8_t interruptState = __save_interrupt();
        __disable_interrupt();
        // If cellVoltage is invalid, get the measurement so we can calculate the cell voltage
        // If it's valid, return it as quick as possible
        // TODO: a bit ugly with the double __restore_interrupt, but i couldn't figure out a simplier (fast) way
        if (0xFFFF == cellVoltage[cellIndex] ) {
            calc = cellMeasurement[cellIndex];
        } else {
            __restore_interrupt(interruptState);
            return cellVoltage[cellIndex];
        }
        __restore_interrupt(interruptState);
        // Don't allow negative values
        if(calc < cellOffset[cellIndex]) {
            calc = 0;
        } else {
            calc -= cellOffset[cellIndex];
            calc *= cellGain[cellIndex];
            calc >>= VADC_SCALE_BITS;
        }
        cellVoltage[cellIndex] = (uint16_t)calc;
    } else {
        calc = 0;
    }
    return (uint16_t)calc;
}
uint16_t VADC_readSystemTemperature (void)
Calculation of chip temperature.
The vtempMeasurement variable sampled from the internal temperature sensor is used to calculate the chip temperature.
Returns:
Temperature in 0.1 kelvin [K].
Definition at line 535 of file vadc.c.
References VADC_SCALE_BITS, vptatCoeff, and vtempMeasurement.
Referenced by handleNewCoreTemperature().
{
    uint32_t calc;
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    calc = vtempMeasurement;
    __restore_interrupt(interruptState);
    calc *= (uint32_t)vptatCoeff*10; // Times 10 to get result in 0.1Kelvin
    calc >>= VADC_SCALE_BITS;
    return (uint16_t)(calc);
}
void VADC_ScanConfig (vadcIndex_t CellInputs, vadcIndex_t VadcInputs, vadcIndex_t vtempScan)
Select VADC channels to be scanned.
Configuration of which VADC channel(s) to be sampled is stored in the file global variable vadcScanConfig. Enums used from vadcIndex_t .
Parameters:
CellInputs Name of highest cell to be sampled.
VadcInputs Name of Highest vadc input to be sampled.
vtempScan Scan internal temperature sensor if VTEMP.
Definition at line 108 of file vadc.c.
References CELL1, CELL2, CELL3, CELL4, VADC0, VADC1, vadcScanConfig, and VTEMP.
Referenced by configureVADC(), and main().
{
    vadcScanConfig = 0;
#if CELL_INPUTS >= 4
    if ( CellInputs == CELL4 ) {
        vadcScanConfig |= (1 << CELL4) | (1 << CELL3) | (1 << CELL2) | (1 << CELL1);
    }
#endif
#if CELL_INPUTS >= 3
    if ( CellInputs == CELL3 ) {
        vadcScanConfig |= (1 << CELL3) | (1 << CELL2) | (1 << CELL1);
    }
#endif
#if CELL_INPUTS >= 2
    if ( CellInputs == CELL2 ) {
        vadcScanConfig |= (1 << CELL2) | (1 << CELL1);
    }
#endif
    if ( CellInputs == CELL1 ) {
        vadcScanConfig |= (1 << CELL1);
    }
    if (VadcInputs == VADC1) {
        vadcScanConfig |= (1 << VADC1)| (1 << VADC0);
    }
    if (VadcInputs == VADC0) {
        vadcScanConfig |= (1 << VADC0);
    }
    if (vtempScan == VTEMP) {
        vadcScanConfig |= (1 << VTEMP);
    }
}
vadcState_t VADC_ScanState (void)
Check VADC scan status.
The internal VADC_Status struct
Returns:
vadcStatus.state
Definition at line 307 of file vadc.c.
References VADC_Status::state, and vadcStatus.
Referenced by handleNewCellVoltage(), and main().
{
    return vadcStatus.state;
}
err_t VADC_StartScan (void)
Start a scan of all VADC channels.
VADC is set up and interrupts enabled. The first vadc channel to be sampled is selected according to vadcScanConfig. The interrupt routine VADC_ISR does the actual vadc measurements. Global interrupts need to be enabled in main for the vadc interrupt routine to be run.
Returns:
SUCCESS or FAILURE
Definition at line 175 of file vadc.c.
References CELL1, FAILURE, VADC_Status::state, SUCCESS, VADC0, VADC_ClearReadyFlags(), VADC_RUNNING, vadcScanConfig, vadcStatus, and VTEMP.
Referenced by main().
{
    err_t status = SUCCESS;
    // start set up for first channel.
    if ( vadcScanConfig & (1 << VTEMP) ) {
        VADMUX = VTEMP;
    } else if ( vadcScanConfig & (1 << VADC0) ) {
        VADMUX = VADC0;
    } else if ( vadcScanConfig & (1 << CELL1) ) {
        VADMUX = CELL1;
    } else {
        status = FAILURE;
    }
    if (status == SUCCESS) {
        VADCSR = (1<<VADCCIF);     //clear any pending interrupt
        VADCSR = (1<<VADEN) | (1<<VADSC) | (1<<VADCCIE);  //Start the first conversion & enable the vadc.
        // Global interrupts need to be enabled in main for the vadc interrupt routine to be run.
        vadcStatus.state = VADC_RUNNING;
        VADC_ClearReadyFlags();
    }
    return status;
}
bool VADC_VTempReady (void)
Return true if new core temperature reading s available.
Definition at line 326 of file vadc.c.
References vadcStatus, and VADC_Status::vtempReady.
Referenced by main().
{
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    bool flagState = vadcStatus.vtempReady;
    __restore_interrupt( interruptState );
    return flagState;
}
Variable Documentation
uint16_t cellGain[BATTPARAM_CELLS_IN_SERIES] [static]
Gain coefficients for Cells.
Definition at line 61 of file vadc.c.
Referenced by VADC_InitializeVadcCoefficients(), and VADC_readCellVoltage().
uint16_t cellMeasurement[BATTPARAM_CELLS_IN_SERIES] [static]
Cell input samples from the vadc ISR.
Definition at line 63 of file vadc.c.
Referenced by VADC_ISR(), and VADC_readCellVoltage().
int8_t cellOffset[BATTPARAM_CELLS_IN_SERIES] [static]
Offset for cells.
Definition at line 62 of file vadc.c.
Referenced by VADC_InitializeVadcCoefficients(), and VADC_readCellVoltage().
uint16_t cellVoltage[BATTPARAM_CELLS_IN_SERIES] [static]
Cell input voltage. Set to 0xFFFF if not calculated from latest cellMeasurement.
Definition at line 64 of file vadc.c.
Referenced by VADC_ISR(), and VADC_readCellVoltage().
uint8_t vadcScanConfig [static]
VADC channel sampling config.
Configuration of which VADC channels to be scanned. A bit is used for each input according to the MUX setting, e.g. (1 << CELL1) for cell1 measurements.
VADC_ScanConfig() configures this variable. It is used by VADC_StartScan() to select first input, while VADC_ISR() then scans the channels selected in a fixed order but only those selected in vadcScanConfig.
The highest MUX setting that can be contained in this 8 bit variable is 7, so it needs to be expanded for devices with more vadc inputs than ATmega16HVA. CELL1 is assumed to always be measured.
Definition at line 90 of file vadc.c.
Referenced by VADC_GetScanConfig(), VADC_ISR(), VADC_ScanConfig(), and VADC_StartScan().
struct VADC_Status vadcStatus
Definition at line 75 of file vadc.c.
Referenced by VADC_Cell1VoltageReady(), VADC_CellTempReady(), VADC_ClearReadyFlags(), VADC_ISR(), VADC_ScanState(), VADC_StartScan(), and VADC_VTempReady().
uint16_t vptatCoeff [static]
Internal temperature sensor coefficient.
Definition at line 72 of file vadc.c.
Referenced by VADC_InitializeVadcCoefficients(), and VADC_readSystemTemperature().
uint16_t vtempMeasurement [static]
VTEMP input sample from the vadc ISR.
Definition at line 73 of file vadc.c.
Referenced by VADC_ISR(), and VADC_readSystemTemperature().