@DOC_TITLE@
SmartBattery Device Application Note
vadc.h File Reference
Detailed Description
Headerfile for vadc_usage.c.
Contains defines and prototypes for vadc_usage.c.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file vadc.h.
#include "common.h"
#include "battery_pack_parameters.h"
Data Structures
struct VADC_Status
Defines
#define CELL_INPUTS BATTPARAM_CELLS_IN_SERIES
Number of adc Cell inputs. Defines size of many variables, so must be 2 if.
#define DEF_CELL1 1
#define DEF_CELL2 2
#define DEF_CELL3 3
#define DEF_CELL4 4
#define DEF_VADC0 6
#define DEF_VADC1 7
#define DEF_VTEMP 5
#define VADC_INPUTS CELLTEMPERATURE_INPUTS
Number of adc Cell inputs. Defines size of many variables, so must be 2 if.
#define VADC_SCALE_BITS 14
Number of bit for scaling results (16384). See VADC in datasheets for formulas.
#define VADC_TEMP_VOLTAGE_SCALING 1
#define VB_DUVR_DFET 500
Voltage across DFET diode.
Typedefs
typedef enum vadcIndex vadcIndex_t
Typedef used where number of cells is input to functions.
typedef enum vadcStateEnum vadcState_t
Enumerations
enum vadcIndex {
CELL1 = 1, CELL2 = 2, CELL3 = 3, CELL4 = 4,
VTEMP = 5, VADC0 = 6, VADC1 = 7
}
Typedef used where number of cells is input to functions.
enum vadcStateEnum { VADC_NOT_RUNNING = 0, VADC_RUNNING, VADC_SCAN_FAILED }
Functions
err_t DUVR_DisableCheck (void)
Check if DUVR mode can be disabled and if so disable it.
bool VADC_Cell1VoltageReady (void)
Return true if new cell1 voltage readings are available.
bool VADC_Cell2VoltageReady (void)
bool VADC_Cell3VoltageReady (void)
bool VADC_Cell4VoltageReady (void)
bool VADC_CellTempReady (void)
Return true if new cell temperature readings are available.
void VADC_ClearReadyFlags ()
Clear the ready flags.
uint8_t VADC_GetScanConfig ()
Return the current ScanConfig.
void VADC_InitializeVadcCoefficients (void)
Return true if new cell2 voltage readings are available.
uint16_t VADC_readCellVoltage (vadcIndex_t cellIndex)
Calculation of cell voltage.
uint16_t VADC_readSystemTemperature (void)
Calculation of chip temperature.
uint16_t VADC_readVadc (vadcIndex_t vadcIndex)
void VADC_ScanConfig (vadcIndex_t Cells, vadcIndex_t Vadcs, vadcIndex_t vtempScan)
Select VADC channels to be scanned.
vadcState_t VADC_ScanState (void)
Check VADC scan status.
err_t VADC_StartScan (void)
Start a scan of all VADC channels.
bool VADC_VTempReady (void)
Return true if new core temperature reading s available.
Define Documentation
#define CELL_INPUTS BATTPARAM_CELLS_IN_SERIES
Number of adc Cell inputs. Defines size of many variables, so must be 2 if.
Definition at line 69 of file vadc.h.
Referenced by VADC_readCellVoltage().
#define DEF_CELL1 1
Definition at line 91 of file vadc.h.
#define DEF_CELL2 2
Definition at line 92 of file vadc.h.
#define DEF_CELL3 3
Definition at line 93 of file vadc.h.
#define DEF_CELL4 4
Definition at line 94 of file vadc.h.
#define DEF_VADC0 6
Definition at line 96 of file vadc.h.
#define DEF_VADC1 7
Definition at line 97 of file vadc.h.
#define DEF_VTEMP 5
Definition at line 95 of file vadc.h.
#define VADC_INPUTS CELLTEMPERATURE_INPUTS
Number of adc Cell inputs. Defines size of many variables, so must be 2 if.
Definition at line 72 of file vadc.h.
#define VADC_SCALE_BITS 14
Number of bit for scaling results (16384). See VADC in datasheets for formulas.
Definition at line 61 of file vadc.h.
Referenced by VADC_readCellVoltage(), and VADC_readSystemTemperature().
#define VADC_TEMP_VOLTAGE_SCALING 1
Upscaling the result from VADC voltage measurements to increase accuracy in temperature measurements. In bits. (note that it is already scaled up by 10 due to the nature of the vadc)
Definition at line 65 of file vadc.h.
#define VB_DUVR_DFET 500
Voltage across DFET diode.
Definition at line 100 of file vadc.h.
Referenced by DUVR_DisableCheck().
Typedef Documentation
typedef enum vadcIndex vadcIndex_t
Typedef used where number of cells is input to functions.
typedef enum vadcStateEnum vadcState_t
Enumeration Type Documentation
enum vadcIndex
Typedef used where number of cells is input to functions.
Enumerator:
CELL1
CELL2
CELL3
CELL4
VTEMP
VADC0
VADC1
Definition at line 89 of file vadc.h.
{ CELL1 = 1, CELL2 = 2, CELL3 = 3, CELL4 = 4, VTEMP=5, VADC0 = 6, VADC1 = 7 } vadcIndex_t;
enum vadcStateEnum
Enumerator:
VADC_NOT_RUNNING
VADC_RUNNING
VADC_SCAN_FAILED
Definition at line 75 of file vadc.h.
{ VADC_NOT_RUNNING = 0, VADC_RUNNING, VADC_SCAN_FAILED } vadcState_t;
Function Documentation
err_t DUVR_DisableCheck (void)
Check if DUVR mode can be disabled and if so disable it.
If the voltage on the cells are sufficiently high after a reset the Deep Under-Voltage Recovery (DUVR) mode should be disabled and possibly the Charge FET (CFET) enabled. This function assumes a VADC scan has been performed and uses the cell samples to calculate cell voltages.
Returns:
SUCCESS or FAILURE
Definition at line 560 of file vadc.c.
References CELL1, CELL2, CELL3, CELL4, FAILURE, SUCCESS, VADC_readCellVoltage(), and VB_DUVR_DFET.
Referenced by disableDUVRIfPossible().
{
    bool disableDuvr;
    bool enableDischargeFet;
    uint16_t temp_cell;
    temp_cell = VADC_readCellVoltage(CELL1);
    if ( temp_cell > battParams.cellDuvrDisableVoltage ) {
        disableDuvr = true;
        //FCSR |= (1 << CFE) | (1 << DUVRD);
        if ( temp_cell > (battParams.cellDuvrDisableVoltage + VB_DUVR_DFET) ) {
            enableDischargeFet = true;
        } else {
            enableDischargeFet = false;
        }
    } else {
        disableDuvr = false;
    }
    // If cell1 was above duvr disable limits, check if cell2 is
# if BATTPARAM_CELLS_IN_SERIES >= 2
    temp_cell = VADC_readCellVoltage(CELL2);
    if( disableDuvr ) {
        if ( temp_cell <= battParams.cellDuvrDisableVoltage ) {
            disableDuvr = false;
        } else if(enableDischargeFet) {
            if ( temp_cell <= (battParams.cellDuvrDisableVoltage + VB_DUVR_DFET) ) {
                enableDischargeFet = false;
            }
        }
    }
# endif
# if BATTPARAM_CELLS_IN_SERIES >= 3
    temp_cell = VADC_readCellVoltage(CELL3);
    if( disableDuvr ) {
        if ( temp_cell <= battParams.cellDuvrDisableVoltage ) {
            disableDuvr = false;
        } else if(enableDischargeFet) {
            if ( temp_cell <= (battParams.cellDuvrDisableVoltage + VB_DUVR_DFET) ) {
                enableDischargeFet = false;
            }
        }
    }
# endif
# if BATTPARAM_CELLS_IN_SERIES >= 4
    temp_cell = VADC_readCellVoltage(CELL4);
    if( disableDuvr ) {
        if ( temp_cell <= battParams.cellDuvrDisableVoltage ) {
            disableDuvr = false;
        } else if(enableDischargeFet) {
            if ( temp_cell <= (battParams.cellDuvrDisableVoltage + VB_DUVR_DFET) ) {
                enableDischargeFet = false;
            }
        }
    }
# endif
    if( disableDuvr ) {
        if( enableDischargeFet ) {
            FCSR = (1<<CFE) | (1<<DFE) | (1<<DUVRD);
        } else {
            FCSR = (1<<CFE) | (1<<DUVRD);
        }
        return SUCCESS;
    } else {
        return FAILURE;
    }
}
bool VADC_Cell1VoltageReady (void)
Return true if new cell1 voltage readings are available.
Definition at line 339 of file vadc.c.
References VADC_Status::cell1VoltageReady, and vadcStatus.
Referenced by main().
{
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    bool flagState = vadcStatus.cell1VoltageReady;
    __restore_interrupt( interruptState );
    return flagState;
}
bool VADC_Cell2VoltageReady (void)
Referenced by main().
bool VADC_Cell3VoltageReady (void)
Referenced by main().
bool VADC_Cell4VoltageReady (void)
Referenced by main().
bool VADC_CellTempReady (void)
Return true if new cell temperature readings are available.
Definition at line 313 of file vadc.c.
References VADC_Status::cellTempReady, and vadcStatus.
Referenced by main().
{
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    bool flagState = vadcStatus.cellTempReady;
    __restore_interrupt( interruptState );
    return flagState;
}
void VADC_ClearReadyFlags ()
Clear the ready flags.
Definition at line 150 of file vadc.c.
References VADC_Status::cell1VoltageReady, VADC_Status::cell2VoltageReady, VADC_Status::cell3VoltageReady, VADC_Status::cell4VoltageReady, VADC_Status::cellTempReady, vadcStatus, and VADC_Status::vtempReady.
Referenced by main(), and VADC_StartScan().
{
#if CELL_INPUTS >= 4
    vadcStatus.cell4VoltageReady = false;
#endif
#if CELL_INPUTS >= 3
    vadcStatus.cell3VoltageReady = false;
#endif
#if CELL_INPUTS >= 2
    vadcStatus.cell2VoltageReady = false;
#endif
    vadcStatus.cell1VoltageReady = false;
    vadcStatus.cellTempReady = false;
    vadcStatus.vtempReady = false;
}
uint8_t VADC_GetScanConfig ()
Return the current ScanConfig.
Definition at line 144 of file vadc.c.
References vadcScanConfig.
{
    return vadcScanConfig;
}
void VADC_InitializeVadcCoefficients (void)
Return true if new cell2 voltage readings are available.
Return true if new cell3 voltage readings are available
Return true if new cell4 voltage readings are available
Initialization of variables for cell voltage, adc voltage and vtemp calculations. The coefficients are stored in (file) global variables. Interrupts are disabled and re-enabled if needed afterwards.
Definition at line 405 of file vadc.c.
References cellGain, cellOffset, READ_SIGNATUREBYTE(), READ_SIGNATUREWORD(), SIG_VADC_ADC0_GAIN_L, SIG_VADC_ADC0_OFFSET, SIG_VADC_ADC1_GAIN_L, SIG_VADC_ADC1_OFFSET, SIG_VADC_CELL1_GAIN_L, SIG_VADC_CELL1_OFFSET, SIG_VADC_CELL2_GAIN_L, SIG_VADC_CELL2_OFFSET, SIG_VADC_CELL3_GAIN_L, SIG_VADC_CELL3_OFFSET, SIG_VADC_CELL4_GAIN_L, SIG_VADC_CELL4_OFFSET, SIG_VPTAT_L, and vptatCoeff.
Referenced by main().
{
    uint8_t interrupt_status = __save_interrupt();  // Disable interrupts.
    __disable_interrupt();
    cellGain[0] = READ_SIGNATUREWORD(SIG_VADC_CELL1_GAIN_L);
    cellOffset[0] = READ_SIGNATUREBYTE(SIG_VADC_CELL1_OFFSET);
#if CELL_INPUTS >= 2
    cellGain[1] = READ_SIGNATUREWORD(SIG_VADC_CELL2_GAIN_L);
    cellOffset[1] = READ_SIGNATUREBYTE(SIG_VADC_CELL2_OFFSET);
#endif
#if CELL_INPUTS >= 3
    cellGain[2] = READ_SIGNATUREWORD(SIG_VADC_CELL3_GAIN_L);
    cellOffset[2] = READ_SIGNATUREBYTE(SIG_VADC_CELL3_OFFSET);
#endif
#if CELL_INPUTS >= 4
    cellGain[3] = READ_SIGNATUREWORD(SIG_VADC_CELL4_GAIN_L);
    cellOffset[3] = READ_SIGNATUREBYTE(SIG_VADC_CELL4_OFFSET);
#endif
    vptatCoeff = READ_SIGNATUREWORD(SIG_VPTAT_L);
#if VADC_INPUTS >= 1
    vadcGain[0] = READ_SIGNATUREWORD(SIG_VADC_ADC0_GAIN_L);
    vadcOffset[0] = READ_SIGNATUREBYTE(SIG_VADC_ADC0_OFFSET);
#endif
#if VADC_INPUTS >= 2
    vadcGain[1] = READ_SIGNATUREWORD(SIG_VADC_ADC1_GAIN_L);
    vadcOffset[1] = READ_SIGNATUREBYTE(SIG_VADC_ADC1_OFFSET);
#endif
    __restore_interrupt(interrupt_status);
}
uint16_t VADC_readCellVoltage (vadcIndex_t cellIndex)
Calculation of cell voltage.
Parameters:
cellIndex Which cell to calculate voltage for. The cellMeasurement array is used as source.
Returns:
Voltage for selected cell index [mV] or zero if not valid.
Definition at line 450 of file vadc.c.
References CELL1, CELL_INPUTS, cellGain, cellMeasurement, cellOffset, cellVoltage, and VADC_SCALE_BITS.
Referenced by BATTVMON_IsCellVoltageTooHigh(), BATTVMON_IsCellVoltageTooLow(), DUVR_DisableCheck(), GASG_AtRateOK(), handleNewCCADCResult(), handleNewCellVoltage(), handleSBSCommand(), SMBR_Voltage(), VBSoC_EstimatedSoC(), VBSoC_Init(), and VBSoC_Update().
{
    uint32_t calc;
    cellIndex -= CELL1;
    if (cellIndex < CELL_INPUTS) {
        uint8_t interruptState = __save_interrupt();
        __disable_interrupt();
        // If cellVoltage is invalid, get the measurement so we can calculate the cell voltage
        // If it's valid, return it as quick as possible
        // TODO: a bit ugly with the double __restore_interrupt, but i couldn't figure out a simplier (fast) way
        if (0xFFFF == cellVoltage[cellIndex] ) {
            calc = cellMeasurement[cellIndex];
        } else {
            __restore_interrupt(interruptState);
            return cellVoltage[cellIndex];
        }
        __restore_interrupt(interruptState);
        // Don't allow negative values
        if(calc < cellOffset[cellIndex]) {
            calc = 0;
        } else {
            calc -= cellOffset[cellIndex];
            calc *= cellGain[cellIndex];
            calc >>= VADC_SCALE_BITS;
        }
        cellVoltage[cellIndex] = (uint16_t)calc;
    } else {
        calc = 0;
    }
    return (uint16_t)calc;
}
uint16_t VADC_readSystemTemperature (void)
Calculation of chip temperature.
The vtempMeasurement variable sampled from the internal temperature sensor is used to calculate the chip temperature.
Returns:
Temperature in 0.1 kelvin [K].
Definition at line 535 of file vadc.c.
References VADC_SCALE_BITS, vptatCoeff, and vtempMeasurement.
Referenced by handleNewCoreTemperature().
{
    uint32_t calc;
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    calc = vtempMeasurement;
    __restore_interrupt(interruptState);
    calc *= (uint32_t)vptatCoeff*10; // Times 10 to get result in 0.1Kelvin
    calc >>= VADC_SCALE_BITS;
    return (uint16_t)(calc);
}
uint16_t VADC_readVadc (vadcIndex_t vadcIndex)
Referenced by handleNewCellTemperature().
void VADC_ScanConfig (vadcIndex_t CellInputs, vadcIndex_t VadcInputs, vadcIndex_t vtempScan)
Select VADC channels to be scanned.
Configuration of which VADC channel(s) to be sampled is stored in the file global variable vadcScanConfig. Enums used from vadcIndex_t .
Parameters:
CellInputs Name of highest cell to be sampled.
VadcInputs Name of Highest vadc input to be sampled.
vtempScan Scan internal temperature sensor if VTEMP.
Definition at line 108 of file vadc.c.
References CELL1, CELL2, CELL3, CELL4, VADC0, VADC1, vadcScanConfig, and VTEMP.
Referenced by configureVADC(), and main().
{
    vadcScanConfig = 0;
#if CELL_INPUTS >= 4
    if ( CellInputs == CELL4 ) {
        vadcScanConfig |= (1 << CELL4) | (1 << CELL3) | (1 << CELL2) | (1 << CELL1);
    }
#endif
#if CELL_INPUTS >= 3
    if ( CellInputs == CELL3 ) {
        vadcScanConfig |= (1 << CELL3) | (1 << CELL2) | (1 << CELL1);
    }
#endif
#if CELL_INPUTS >= 2
    if ( CellInputs == CELL2 ) {
        vadcScanConfig |= (1 << CELL2) | (1 << CELL1);
    }
#endif
    if ( CellInputs == CELL1 ) {
        vadcScanConfig |= (1 << CELL1);
    }
    if (VadcInputs == VADC1) {
        vadcScanConfig |= (1 << VADC1)| (1 << VADC0);
    }
    if (VadcInputs == VADC0) {
        vadcScanConfig |= (1 << VADC0);
    }
    if (vtempScan == VTEMP) {
        vadcScanConfig |= (1 << VTEMP);
    }
}
vadcState_t VADC_ScanState (void)
Check VADC scan status.
The internal VADC_Status struct
Returns:
vadcStatus.state
Definition at line 307 of file vadc.c.
References VADC_Status::state, and vadcStatus.
Referenced by handleNewCellVoltage(), and main().
{
    return vadcStatus.state;
}
err_t VADC_StartScan (void)
Start a scan of all VADC channels.
VADC is set up and interrupts enabled. The first vadc channel to be sampled is selected according to vadcScanConfig. The interrupt routine VADC_ISR does the actual vadc measurements. Global interrupts need to be enabled in main for the vadc interrupt routine to be run.
Returns:
SUCCESS or FAILURE
Definition at line 175 of file vadc.c.
References CELL1, FAILURE, VADC_Status::state, SUCCESS, VADC0, VADC_ClearReadyFlags(), VADC_RUNNING, vadcScanConfig, vadcStatus, and VTEMP.
Referenced by main().
{
    err_t status = SUCCESS;
    // start set up for first channel.
    if ( vadcScanConfig & (1 << VTEMP) ) {
        VADMUX = VTEMP;
    } else if ( vadcScanConfig & (1 << VADC0) ) {
        VADMUX = VADC0;
    } else if ( vadcScanConfig & (1 << CELL1) ) {
        VADMUX = CELL1;
    } else {
        status = FAILURE;
    }
    if (status == SUCCESS) {
        VADCSR = (1<<VADCCIF);     //clear any pending interrupt
        VADCSR = (1<<VADEN) | (1<<VADSC) | (1<<VADCCIE);  //Start the first conversion & enable the vadc.
        // Global interrupts need to be enabled in main for the vadc interrupt routine to be run.
        vadcStatus.state = VADC_RUNNING;
        VADC_ClearReadyFlags();
    }
    return status;
}
bool VADC_VTempReady (void)
Return true if new core temperature reading s available.
Definition at line 326 of file vadc.c.
References vadcStatus, and VADC_Status::vtempReady.
Referenced by main().
{
    uint8_t interruptState = __save_interrupt();
    __disable_interrupt();
    bool flagState = vadcStatus.vtempReady;
    __restore_interrupt( interruptState );
    return flagState;
}