@DOC_TITLE@
SmartBattery Device Application Note
voltage_based_SoC.c File Reference
Detailed Description
Functions for estimating State of Charge based on voltage.
Application note:
AVR474: SB202 Firmware user's guide.
Documentation
For comprehensive code documentation, supported compilers, compiler settings and supported devices see readme.html
Author:
Atmel Corporation: http://www.atmel.com
Support email: avr@atmel.com
Revision
5627
Date
2009-05-15 14:49:21 +0800 (Fri, 15 May 2009)
Copyright (c) 2009, Atmel Corporation All rights reserved.
Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:
1. Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
2. Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
3. The name of ATMEL may not be used to endorse or promote products derived from this software without specific prior written permission.
THIS SOFTWARE IS PROVIDED BY ATMEL "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE EXPRESSLY AND SPECIFICALLY DISCLAIMED. IN NO EVENT SHALL ATMEL BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
Definition in file voltage_based_SoC.c.
#include "common.h"
#include "vadc.h"
#include "ccadc.h"
#include "voltage_based_SoC.h"
#include "rtc.h"
#include "battery_current_monitoring.h"
Defines
#define VOLTAGE_EMPTY (VoltageTable[0][VOLTAGE_TABLE_SIZE-1])
#define VOLTAGE_FULL (VoltageTable[0][0])
#define VOLTAGE_TABLE_SIZE 21
Functions
int16_t ConvertDigitalToCurrent (void)
Current conversion.
int16_t ConvertDigitalToVoltage (void)
Voltage conversion.
uint16_t ConvertVoltageToSoC (uint16_t inputVoltage)
SoC conversion.
uint16_t VBSoC_ConvertSoCToVoltage (uint16_t inputsoc)
SoC-Voltage conversion.
uint16_t VBSoC_EstimatedSoC (void)
Returns the the latest estimated state of charge.
void VBSoC_Init (void)
Calculate the initial SoC.
uint16_t VBSoC_OCSoC (void)
Returns the the latest open circuit state of charge.
uint16_t VBSoC_OCSoCLastUpdated (void)
Returns how many seconds ago the open circuit voltage SoC was updated.
void VBSoC_ResetTimer (void)
Reset the relaxation timer.
bool VBSoC_Update (void)
Updates the SoC.
Variables
uint16_t LastUpdated
uint16_t OpenCircuitSoC
uint8_t relaxationTimer
__flash uint16_t VoltageTable [2][21]
Define Documentation
#define VOLTAGE_EMPTY (VoltageTable[0][VOLTAGE_TABLE_SIZE-1])
Definition at line 58 of file voltage_based_SoC.c.
Referenced by ConvertVoltageToSoC(), and VBSoC_ConvertSoCToVoltage().
#define VOLTAGE_FULL (VoltageTable[0][0])
Definition at line 59 of file voltage_based_SoC.c.
Referenced by ConvertVoltageToSoC(), and VBSoC_ConvertSoCToVoltage().
#define VOLTAGE_TABLE_SIZE 21
Definition at line 78 of file voltage_based_SoC.c.
Referenced by ConvertVoltageToSoC(), and VBSoC_ConvertSoCToVoltage().
Function Documentation
int16_t ConvertDigitalToCurrent (void)
Current conversion.
Conversion of digital value to current (in mA).
Returns:
Current (mA)
Definition at line 325 of file voltage_based_SoC.c.
References BATTCUR_GetOffsetCalibratedCurrent(), and BATTCUR_Ticks2mA().
Referenced by ConvertDigitalToVoltage().
{
    return BATTCUR_Ticks2mA(BATTCUR_GetOffsetCalibratedCurrent());
}
int16_t ConvertDigitalToVoltage (void)
Voltage conversion.
Conversion of digital value to voltage on battery internal resistor (mV).
Returns:
current (mA)
Definition at line 337 of file voltage_based_SoC.c.
References ConvertDigitalToCurrent(), and INTERNAL_BATT_RESISTOR_TIMES_128.
Referenced by VBSoC_EstimatedSoC().
{
    int32_t temp;
    temp = ConvertDigitalToCurrent();
    temp *= INTERNAL_BATT_RESISTOR_TIMES_128;
    if(temp < 0) {
        temp = -temp;
        temp += 64; // rounding
        temp >>= 7; // divide by 128
        temp = -temp;
    } else {
        temp += 64; // rounding
        temp >>= 7; // divide by 128
    }
    return ((int16_t) temp);
}
uint16_t ConvertVoltageToSoC (uint16_t inputVoltage)
SoC conversion.
Conversion of voltage to SoC by using conversion table.
Returns:
Soc (0 to 100)
Definition at line 282 of file voltage_based_SoC.c.
References VOLTAGE_EMPTY, VOLTAGE_FULL, VOLTAGE_TABLE_SIZE, and VoltageTable.
Referenced by VBSoC_EstimatedSoC(), VBSoC_Init(), and VBSoC_Update().
{
    uint16_t socval = 0;
    uint8_t i = 1;
    // Check if voltage is above treshold.
    if(inputVoltage >= VOLTAGE_FULL)
    {
        // Set SoC to 100%.
        socval = 100;
    }
    // Check if voltage is below treshold.
    else if(inputVoltage <= VOLTAGE_EMPTY)
    {
        // Set SoC to 0%.
        socval = 0;
    }
    // Look up interval in table and interpolate
    else
    {
        // Find the actual interval in the voltage-SoC table and interpolate.
        while((i<VOLTAGE_TABLE_SIZE) && (socval==0))
        {
            if(VoltageTable[0][i] <= inputVoltage)
            {
                socval = VoltageTable[1][i] + (inputVoltage - VoltageTable[0][i]) * ( VoltageTable[1][i-1] - VoltageTable[1][i] ) / (VoltageTable[0][i-1] - VoltageTable[0][i]);
                socval /= 10; // To get percent instead of 0.1percent
            }
            i++;
        }
    }
    return socval;
}
uint16_t VBSoC_ConvertSoCToVoltage (uint16_t inputsoc)
SoC-Voltage conversion.
Conversion of SoC to voltage by using conversion table.
Returns:
Voltage(OCV)in mV
Definition at line 365 of file voltage_based_SoC.c.
References VOLTAGE_EMPTY, VOLTAGE_FULL, VOLTAGE_TABLE_SIZE, and VoltageTable.
{
        uint16_t volval = 0;
    uint8_t i = 1;
    // Check if soc is above 1000.
    if(inputsoc >= 1000){
            // Set voltage to full voltage.
        volval = VOLTAGE_FULL;
    // Check if soc is below 0.
    }else if(inputsoc <= 0){
        // Set voltage to empty voltage.
        volval = VOLTAGE_EMPTY;
    // Look up interval in table and interpolate
    }else{
        // Find the actual interval in the voltage-SoC table and interpolate.
        while((i<VOLTAGE_TABLE_SIZE) && (volval==0))
        {
            if(VoltageTable[1][i] <= inputsoc)
            {
                //socval = VoltageTable[1][i] + (inputVoltage - VoltageTable[0][i]) * ( VoltageTable[1][i-1] - VoltageTable[1][i] ) / (VoltageTable[0][i-1] - VoltageTable[0][i]);
                volval = VoltageTable[0][i] + (inputsoc - VoltageTable[1][i]) * ( VoltageTable[0][i-1] - VoltageTable[0][i] ) / (VoltageTable[1][i-1] - VoltageTable[1][i]);
            }
            i++;
        }
    }
    return volval;
}
uint16_t VBSoC_EstimatedSoC (void)
Returns the the latest estimated state of charge.
Definition at line 238 of file voltage_based_SoC.c.
References CELL1, CELL2, CELL3, CELL4, ConvertDigitalToVoltage(), ConvertVoltageToSoC(), and VADC_readCellVoltage().
Referenced by main().
{
    int16_t result_volt;
    uint16_t lowestCellVoltage;
    // See which cell has the lowest voltage and use that in the calculations
#if BATTPARAM_CELLS_IN_SERIES == 2
    {
        uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
        uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
        lowestCellVoltage = (voltageCell1 < voltageCell2) ? voltageCell1 : voltageCell2;
    }
#elif BATTPARAM_CELLS_IN_SERIES == 3
    {
        uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
        uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
        uint16_t voltageCell3 = VADC_readCellVoltage(CELL3);
        lowestCellVoltage = (voltageCell1 < voltageCell2)      ? voltageCell1 : voltageCell2;
        lowestCellVoltage = (lowestCellVoltage < voltageCell3) ? lowestCellVoltage : voltageCell3;
    }
#elif BATTPARAM_CELLS_IN_SERIES == 4
    {
        uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
        uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
        uint16_t voltageCell3 = VADC_readCellVoltage(CELL3);
        uint16_t voltageCell4 = VADC_readCellVoltage(CELL4);
        lowestCellVoltage = (voltageCell1 < voltageCell2)      ? voltageCell1 : voltageCell2;
        lowestCellVoltage = (lowestCellVoltage < voltageCell3) ? lowestCellVoltage : voltageCell3;
        lowestCellVoltage = (lowestCellVoltage < voltageCell4) ? lowestCellVoltage : voltageCell4;
    }
#endif
    // Calculate the voltage drop from current (is negative while discharging, and positive while charging)
    result_volt = ConvertDigitalToVoltage();
    // Estimate the SoC bases on cell voltage and voltage drop
    return ConvertVoltageToSoC(lowestCellVoltage - result_volt );
}
void VBSoC_Init (void)
Calculate the initial SoC.
This function updates both the estimated and open circuit SoC, run when sure the voltage is a open circuit voltage (for example, at startup after being shut down for a couple of days)
Definition at line 108 of file voltage_based_SoC.c.
References CELL1, CELL2, CELL3, CELL4, ConvertVoltageToSoC(), OpenCircuitSoC, and VADC_readCellVoltage().
Referenced by main().
{
    uint16_t lowestCellVoltage;
    // See which cell has the lowest voltage and use that in the calculations
#if BATTPARAM_CELLS_IN_SERIES == 2
    {
        uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
        uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
        lowestCellVoltage = (voltageCell1 < voltageCell2) ? voltageCell1 : voltageCell2;
    }
#elif BATTPARAM_CELLS_IN_SERIES == 3
    {
        uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
        uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
        uint16_t voltageCell3 = VADC_readCellVoltage(CELL3);
        lowestCellVoltage = (voltageCell1 < voltageCell2)      ? voltageCell1 : voltageCell2;
        lowestCellVoltage = (lowestCellVoltage < voltageCell3) ? lowestCellVoltage : voltageCell3;
    }
#elif BATTPARAM_CELLS_IN_SERIES == 4
    {
        uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
        uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
        uint16_t voltageCell3 = VADC_readCellVoltage(CELL3);
        uint16_t voltageCell4 = VADC_readCellVoltage(CELL4);
        lowestCellVoltage = (voltageCell1 < voltageCell2)      ? voltageCell1 : voltageCell2;
        lowestCellVoltage = (lowestCellVoltage < voltageCell3) ? lowestCellVoltage : voltageCell3;
        lowestCellVoltage = (lowestCellVoltage < voltageCell4) ? lowestCellVoltage : voltageCell4;
    }
#endif
    OpenCircuitSoC = ConvertVoltageToSoC(lowestCellVoltage);
}
uint16_t VBSoC_OCSoC (void)
Returns the the latest open circuit state of charge.
Check how old this is with the VBSoC_OCSoCLastUpdated function
Definition at line 230 of file voltage_based_SoC.c.
References OpenCircuitSoC.
Referenced by handleNewCellVoltage().
{
    return OpenCircuitSoC;
}
uint16_t VBSoC_OCSoCLastUpdated (void)
Returns how many seconds ago the open circuit voltage SoC was updated.
Returns:
Seconds since last time OCV SoC was updated
Definition at line 221 of file voltage_based_SoC.c.
References LastUpdated.
{
    return LastUpdated;
}
void VBSoC_ResetTimer (void)
Reset the relaxation timer.
Run this function when device not is in standby mode
Definition at line 212 of file voltage_based_SoC.c.
References relaxationTimer, and RTC_GetMinutes().
Referenced by handleNewCCADCResult().
{
    relaxationTimer = RTC_GetMinutes() + battParams.openCircuitRelaxationTime;
}
bool VBSoC_Update (void)
Updates the SoC.
Should be run once a second
Updates open circuit SoC if have been in relaxation for battParams.openCircuitRelaxationTime
Returns:
Returns true if openCircuitSoC was updated
Definition at line 151 of file voltage_based_SoC.c.
References CELL1, CELL2, CELL3, CELL4, ConvertVoltageToSoC(), LastUpdated, OpenCircuitSoC, relaxationTimer, RTC_GetMinutes(), and VADC_readCellVoltage().
Referenced by handleNewCellVoltage().
{
    // Don't want LastUpdated to overflow back to zero, but that it stays at
    // 65534 seconds doesn't matter.
    // It shouldn't really be this long between LastUpdated is reset, but better
    // to be safe.
    if(LastUpdated < 65535) {
        ++LastUpdated;
    }
    // Check if it's time to update the open circuit SoC
    if(RTC_GetMinutes() == relaxationTimer) {
        // Only update if it was more than 30 seconds ago last time
        // TODO: maybe a define, but the actual value is not that important, its just to avoid
        //       doing the calculations every second. And since the current is low (or else
        //       it wouldn't get here) the state of charge changes very slowly
        if(LastUpdated >= 30) {
            // See which cell has the lowest voltage and use that in the calculations
            uint16_t lowestCellVoltage;
#if BATTPARAM_CELLS_IN_SERIES == 2
            {
                uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
                uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
                lowestCellVoltage = (voltageCell1 < voltageCell2) ? voltageCell1 : voltageCell2;
            }
#elif BATTPARAM_CELLS_IN_SERIES == 3
            {
                uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
                uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
                uint16_t voltageCell3 = VADC_readCellVoltage(CELL3);
                lowestCellVoltage = (voltageCell1 < voltageCell2)      ? voltageCell1 : voltageCell2;
                lowestCellVoltage = (lowestCellVoltage < voltageCell3) ? lowestCellVoltage : voltageCell3;
            }
#elif BATTPARAM_CELLS_IN_SERIES == 4
            {
                uint16_t voltageCell1 = VADC_readCellVoltage(CELL1);
                uint16_t voltageCell2 = VADC_readCellVoltage(CELL2);
                uint16_t voltageCell3 = VADC_readCellVoltage(CELL3);
                uint16_t voltageCell4 = VADC_readCellVoltage(CELL4);
                lowestCellVoltage = (voltageCell1 < voltageCell2)      ? voltageCell1 : voltageCell2;
                lowestCellVoltage = (lowestCellVoltage < voltageCell3) ? lowestCellVoltage : voltageCell3;
                lowestCellVoltage = (lowestCellVoltage < voltageCell4) ? lowestCellVoltage : voltageCell4;
            }
#endif
            OpenCircuitSoC = ConvertVoltageToSoC(lowestCellVoltage);
            LastUpdated = 0;
            return true;
        }
    }
    return false;
}
Variable Documentation
uint16_t LastUpdated
Definition at line 93 of file voltage_based_SoC.c.
Referenced by VBSoC_OCSoCLastUpdated(), and VBSoC_Update().
uint16_t OpenCircuitSoC
Definition at line 87 of file voltage_based_SoC.c.
Referenced by VBSoC_Init(), VBSoC_OCSoC(), and VBSoC_Update().
uint8_t relaxationTimer
Definition at line 96 of file voltage_based_SoC.c.
Referenced by VBSoC_ResetTimer(), and VBSoC_Update().
__flash uint16_t VoltageTable[2][21]
Initial value:
 {
    {4180,4112,4074,4013,3973,3922,3858,3810,3782,3762,3751,3725,3701,3684,3678,3663,3607,3511,3350,3200,2771 },
    {1000,950 ,900 ,850 ,800 ,700 ,600 ,500 ,400 ,300 ,250 ,200 ,150 ,120 ,100 ,80  ,60  ,40  ,20  ,10  ,0 } }
Definition at line 79 of file voltage_based_SoC.c.
Referenced by ConvertVoltageToSoC(), and VBSoC_ConvertSoCToVoltage().